### ISSUE TITLE
[Next.js] Error: Should provide a fetch function under Node.js

### ISSUE THREAD

**Issue by jacksonrakena** [logto-io/logto#1504]
Firstly, I'd like to say that Logto sounds like a great project. Excited for what could become of this.  
  
When running a Next.js app with the `logto-io/react` connector, I get this issue before I can even load the page:
![image](https://user-images.githubusercontent.com/44521335/178142977-ea8791cc-bd89-4764-a6ae-f2e9e1740092.png)
My LogtoProvider setup is fairly standard:
```ts
<LogtoProvider
        config={{
          endpoint: "https://id-v2-dev.animalswithcoolhats.com",
          appId: "u50kz2fnWde4KcxD1QdBM",
        }}
      >
```.

I suspect it's something to do with SSR, the page being rendered on the server is tripping some kind of error inside a dependency.

**Comment by gao-sun** [comment]
@demonzoo @wangsijie would you like to take a look?

**Comment by jacksonrakena** [comment]
Moved this to https://github.com/logto-io/js/issues/327 because it's probably more suited on that repo
