### ISSUE TITLE
feature request: Support pressing enter to submit

### ISSUE THREAD

**Issue by andersmmg** [logto-io/logto#1577]
### What problem did you meet?
When creating an account or logging in, the button seems to need to be manually clicked to submit the form, rather than being able to press the enter key to submit.

### Describe what you'd like Logto to have
Support for pressing enter to submit login and create account forms.

**Comment by simeng-li** [comment]
Thanks for the reporting.That is definitely something we expect to have.  Working on it

**Comment by demonzoo** [comment]
Yes, we have just talked about it internally couple days ago. More keyboard shortcuts support are on the way.
Thank you for your support. Stay tuned.

**Comment by simeng-li** [comment]
The fix is in the latest release now @andersmmg please check. Cheers.

**Comment by andersmmg** [comment]
Seems to work now!
