### ISSUE TITLE
feature request:   account login success notify api

### ISSUE THREAD

**Issue by zhouzhiqiangzzq** [logto-io/logto#1579]
### Describe what you'd like Logto to have
when a user login success or create a new account  success, other business service can get the notify and  can get user  info，can you provide  an  api  config  like this ?   or already have ?

**Comment by gao-sun** [comment]
we don't have this right now, but it's already on our [roadmap](https://github.com/orgs/logto-io/projects/5). Before it's available, you can head to [this doc](https://docs.logto.io/docs/recipes/manage-users/you-dont-need-a-user-table) to see if it helps.

**Comment by zhouzhiqiangzzq** [comment]
> we don't have this right now, but it's already on our [roadmap](https://github.com/orgs/logto-io/projects/5). Before it's available, you can head to [this doc](https://docs.logto.io/docs/recipes/manage-users/you-dont-need-a-user-table) to see if it helps.
----
thank you bro ,  it is really help me.

**Comment by akarapol** [comment]
@gao-sun how to send the custom-data of user with  id_token and access_token

**Comment by gao-sun** [comment]
@zhouzhiqiangzzq [hooks](https://docs.logto.io/docs/recipes/web-hooks/#hook-event) has been released, feel free to check it out.

@akarapol it'll be great if you can elaborate the issue you met - looks like this is not related to this thread, feel free to open a new issue if needed
