### ISSUE TITLE
feature request: Feature Suggestions

### ISSUE THREAD

**Issue by meimosor** [logto-io/logto#1595]
1、2FA Authentication Support
2、User Federation Support
3、Session management Support
4、Java SDK Support

**Comment by darcyYe** [comment]
You can follow the issue template we provided.
I'll manually close this one.
You may reopen it after reorg the contents to make it fit our templates.

**Comment by gao-sun** [comment]
Suggestions are great. Most are on our roadmap already. As @darcyYe said, if you want to keep the issue open, please follow our template.
