### ISSUE TITLE
feature request: i18n internationalization

### ISSUE THREAD

**Issue by Olyno** [logto-io/logto#1599]
### What problem did you meet?

When we arrive at the registration or login page, the text is in English, even though our platform is aimed at another language that does not speak English.

This problem also occurs with emails sent to users.

### Describe what you'd like Logto to have

Having an in-house system would allow us to create customized translations for our users. Logto could provide default translations, but let the admins create their own translations if needed.

I think that a configuration file similar to the one used for emails would do the job very well.

**Comment by gao-sun** [comment]
yes, this is on our Q3 roadmap

**Comment by demonzoo** [comment]
> The sign-in flow UI language can be set by the Admin Console sign-in-experience settings. By default, it will follow the system. However, only `en` and `zh-CN` translation resources are provided at the current release. It will fall back to en for all the rests for now.
> 
> <img alt="image" width="687" src="https://user-images.githubusercontent.com/36393111/179768945-1ee212e1-94f0-4eab-ac1a-565f2f56171c.png">
> 
> The related source file could be located under [phrases-ui](https://github.com/logto-io/logto/tree/master/packages/phrases-ui) and and [phrase](https://github.com/logto-io/logto/tree/master/packages/phrases). You may add any additionally supported languages as you like.
> 
> Meanwhile, we are still looking for a more handy solution for i18n, making it easier to add additionally supported languages.
> 
> In terms of the email template languages, the solution may vary, based on the different email connector interfaces I believe.

I think the OP mentioned email config as he thought a similar solution would be fit for the i18n as well. Imagine there would a page in admin console, where the admin can add/edit their own i18n phrases using our code editor...

**Comment by gao-sun** [comment]
should this be considered as resolved?

**Comment by gao-sun** [comment]
close as it is implemented :-)
