### ISSUE TITLE
feature request: 

### ISSUE THREAD

**Issue by KaveenAmarasekara** [logto-io/logto#1620]
CAN YOU JOIN OUR NETWORK........

*How to Solve*

Launching new Q & A site, Proudly present by ARM SOLUTIONS,
Including many features and stand to solve your problems with the best experts in world wide.

http://howtosolve.is-great.org

*Best features :*

• Ask any question for free.
• Free site membership.
• Create you own group/team.
• Earn/buy points by Answering.
• Vote others/ get votes.
• Grow your brand with Advertising programmes.

**Comment by gao-sun** [comment]
thanks for the issue. the product looks great. since we are just started, we would like to stick with GitHub Discussions and do a more comprehensive research before deciding to migrate our Q&A platform. we can stay connected with you!
