### ISSUE TITLE
bug: how to interminate with umijs

### ISSUE THREAD

**Issue by livepo** [logto-io/logto#1637]
error  in ./node_modules/@logto/client/lib/module.js

Module parse failed: Unexpected token (85:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class $19775a679e2952df$export$2e2bcd8739ae039 {
>     getOidcConfig = (0, $kqBTI$lodashonce)(this._getOidcConfig);
|     getJwtVerifyGetKey = (0, $kqBTI$lodashonce)(this._getJwtVerifyGetKey);
|     accessTokenMap = new Map();

 @ ./node_modules/@logto/browser/lib/module.js 1:0-378 44:22-60 55:59-77 57:30-52 70:0-347 70:0-347 70:0-347 70:0-347 70:0-347
 @ ./src/pages/index.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./node_modules/umi/node_modules/@umijs/preset-built-in/bundled/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./src/.umi/umi.ts

I use umijs and want to use the logto sdk. but not matter use logto/react or logto/browser. It always get the error  `currently no loaders ....`
Could you help me solve this?

**Comment by gao-sun** [comment]
closed until the content meets our template
