### ISSUE TITLE
feature request: Adding more db types like MongoDB, etc.

### ISSUE THREAD

**Issue by 0zul** [logto-io/logto#1661]
### What problem did you meet?
I've had an issue setting up Postgres DB URI to my remote server hence it's really impossible for me to use Postgres.

### Describe what you'd like Logto to have
Ability to use other DB like MongoDB, MySQL, etc.

**Comment by gao-sun** [comment]
Currently we'd like to leverage Postgres as an opinionated database choice since there are more features on the way. We'll consider this once we launch a stable version.

If you are interested about contribution on this feature feel free to discuss with us.

**Comment by gao-sun** [comment]
we decided to bond with Postgres for a while since it has a rich feature-set which other databases cannot provide all of them.

**Comment by clhey** [comment]
> Currently we'd like to leverage Postgres as an opinionated database choice since there are more features on the way. We'll consider this once we launch a stable version.
> 
> If you are interested about contribution on this feature feel free to discuss with us.

It's been a year already, has the situation changed at all?

**Comment by JakimLi** [comment]
Posgresql on cloud is much more expensive, if other db supported will be great.

**Comment by yangtuooc** [comment]
Still hoping for MySQL support in 2025! 🤞 Any updates on the roadmap?
