### ISSUE TITLE
bug:  sending http from console deployed into a https environment

### ISSUE THREAD

**Issue by CNLHC** [logto-io/logto#1663]
### Describe the bug

A `HTTP` request is sent to `http://<ENDPOINT>/oidc/token` while the console was behind a `https` endpoint, which will be prohibited by the browser. 

![image](https://user-images.githubusercontent.com/21005146/180596883-c07ab4fa-3eed-4e4b-bc02-dc3a52999faa.png)

Before calling to `/oidc/token`, a call to `/oidc/.well-known/openid-configuration` returns URL start with `http`. 

### Expected behavior

If one accesses the console via HTTPS, then the API call should be sent via HTTPS.
### How to reproduce?

You can just deploy an instance behind a HTTPS proxy then it can be reproduced.

### Context

OS:  Kubernetes

Environment: 
```
ALL_YES=1
NO_INQUIRY=0
TRUST_PROXY_HEADER=1
DB_URL_DEFAULT='...'
ENDPOINT=https://<blabla>
 
```

Logto version: 
prerelease

Node version:
v16.16.0

Postgres version: 
v14.0

Command of starting Logto: 
Default docker command

**Comment by CNLHC** [comment]
I just find the issue.
One should set `X-Forwarded-Proto` to tell the backend you are using `HTTPS`.

This error is a little bit weird and counterintuitive if the user already set the Endpoint to an `HTTPS://` thing.

It will be nice if we warn the user in the document to take care of `X-Forwarded-Proto`

**Comment by CNLHC** [comment]
[This doc](https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#trusting-tls-offloading-proxies) already warns the user to set this header. 

I will close this thread.

**Comment by gao-sun** [comment]
Thank you for the detailed issue description, and glad it works!
