### ISSUE TITLE
question: cannot start Logto since relation "connectors" doesn't exist

### ISSUE THREAD

**Issue by SilverHi** [logto-io/logto#1664]
### Describe the bug

I following the TUTORIALS ,use docker run logto. 
 I used``` docker run -it -p 3001:3001 --env-file=init.env  [ImagersId] ```  
console show me

```
Error while initializing app error: 关系 "connectors" 不存在
    at Parser.parseErrorMessage (/home/logto/logto/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/logto/logto/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/logto/logto/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/logto/logto/node_modules/.pnpm/pg-protocol@1.5.0/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 103,
  severity: '错误',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '53',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1384',
  routine: 'parserOpenTable',
  notices: []
}   
 ```

I try again without docker 
I used local ，when I enterd Postgres_url, the same error occurred
### How to reproduce?

run logto with docker  or local
### Context

OS: Centos7

Environment: 
Docker and local  
Logto version: 
[1.0.0-beta.1] (2022-07-19)
Node version:
16
Postgres version: 
14
Command of starting Logto: 
docker :```docker run -it -p 3001:3001 --env-file=init.env  [ImagersId]```

local : ``` node -e "$(printf "%s" "$(curl -fsSL https://raw.githubusercontent.com/logto-io/logto/HEAD/install.js)")" ```

**Comment by SilverHi** [comment]
I used new PostgreSQL and user is postgres

**Comment by gao-sun** [comment]
note: make sure your postgres instance has no database named `logto`.

looks like your database is not initialized. would you like to use the download script WITHOUT setting `DB_URL`?

when it shows:

```
No Postgres DSN (...) found in env variables. Would you like to set up a new Logto database?
```

answer `yes`, and for:

```
Please input the DSN _WITHOUT_ database name:
```

enter the DSN. then you'll be good to go.

**Comment by gao-sun** [comment]
a good issue though. will refine the database init process in docker.

**Comment by SilverHi** [comment]
Thanks!, I have started logto.
I created the database in advance，and named logto

**Comment by demonzoo** [comment]
OK, seems the issue has been resolved. I'm closing the ticket now.
Feel free to comment and reopen the ticket if necessary. Thanks

**Comment by gao-sun** [comment]
@SilverHi did you successfully start Logto?

**Comment by gao-sun** [comment]
@SilverHi feel free to connect with us again if it does't work, cheers

**Comment by SilverHi** [comment]
@gao-sun Thanks, I've started it, but I encountered some problems when integrating with Vue, but this seems to be my problem. If logto has a problem, I'll contact you. Thanks again~
