### ISSUE TITLE
bug: argon2@0.28.5 install fail for mac m1 run dev

### ISSUE THREAD

**Issue by paper-florent** [logto-io/logto#1699]
### Describe the bug

Having 
![Screen Shot 2022-07-28 at 9 59 14 AM](https://user-images.githubusercontent.com/104535887/181523922-ab88dc73-0d17-41b6-b19a-957e406ccf7c.png)

### Expected behavior

should be able to `pnpm dev` without issue

### How to reproduce?

Have a m1

`pnpm install` and `pnpm dev`

### Context

OS: macbook pro m1

Environment: 

Logto version: latest

Node version: 16

Postgres version: 

Command of starting Logto:

**Comment by demonzoo** [comment]
Hi @paper-florent , this is indeed a weird issue. Our team is also using M1 machines and we haven't experienced anything like this before.
Just want to check with you on several things real quick:
* Are you using the `install.js` script or did you clone the source code from GitHub?
* Can you try to remove your `node_modules` folders and retry `pnpm i && pnpm dev` again? 

Thanks!

**Comment by paper-florent** [comment]
Hey @demonzoo thanks for the fast answer ! From the root folder I did:
- cloned the repo
- nvm use 16
- pnpm i
- pnpm dev

Let me try your suggestion

**Comment by paper-florent** [comment]
Looks like it worked... Thanks !

**Comment by demonzoo** [comment]
Well, glad it works. But this indeed IS a weird issue. Feel free to let us know if you have any further questions or issues while using our code.
Happy hacking!
