### ISSUE TITLE
feature request: allow to disable registration

### ISSUE THREAD

**Issue by hengheng0haha** [logto-io/logto#1716]
### What problem did you meet?

My app doesn't require registration, is there a configuration to disable registration?
### Describe what you'd like Logto to have

Disable registration via environment variables such as `REGISTRATION_DISABLE=1`.  
Once disabled, it is hoped that users can still be added in the admin console.

**Comment by gao-sun** [comment]
thanks, it's valid. we'll figure out this.

**Comment by gao-sun** [comment]
i'm adding Q3 label for now since this looks not too much work. the timeline may change though

**Comment by gao-sun** [comment]
the PR has been merged, you can use `TAG=edge` to fetch to main branch image, or wait for the next release.

then go Admin Console -> Sign-in Experience -> Tab "Others"-> Authentication, and you'll see a switch to disable registration.

feel free to let us know if you have any questions. :-)
