### ISSUE TITLE
feature request: release docker image to DockerHub

### ISSUE THREAD

**Issue by waltcow** [logto-io/logto#1740]
### What problem did you meet?

```sh
docker pull ghcr.io/logto-io/logto:latest
Error response from daemon: manifest unknown
```

### Describe what you'd like Logto to have

use  Github Actions release image to DockerHub

**Comment by gao-sun** [comment]
- we don't have `latest` tag for now since we are still in beta stage. you can use `prerelease` tag instead - let me know if you meet any issue on that tag.
- ghcr will be fine for now, but yes, we'll upload to docker image as well

**Comment by waltcow** [comment]
Okay

**Comment by gao-sun** [comment]
no need for closing - definitely a valid request for docker registry :-)
