### ISSUE TITLE
feature request: Allow importing/exporting data through json file

### ISSUE THREAD

**Issue by mikarty** [logto-io/logto#1745]
### What problem did you meet?
Allow importing/exporting data through json file

### Describe what you'd like Logto to have

- Being able to export existing data from logto into json file

- Being able to import data into logto from json file

This could be beneficial when for example spinning up logto instance locally through docker and being able to provide versioned pre-configured data

Example from keycloak - https://www.keycloak.org/server/importExport

**Comment by gao-sun** [comment]
thanks @mikarty!
@wangsijie would you like to take a look?

**Comment by wangsijie** [comment]
Currently, Logto stores all data in a single source: database, the default engine is postgres. So import/export can be achived by db's import/export which is supported by most of the db clients and cloud services.

But still, I'll take a deep research on this with the team, and post updates in this thread once completed.

Thanks for the idea @mikarty

**Comment by wangsijie** [comment]
@mikarty the migration feature is ready: https://docs.logto.io/docs/recipes/migrations/

**Comment by wangsijie** [comment]
Feel free to reopen this issue at any time!
