### ISSUE TITLE
feature request: Kakao Connector

### ISSUE THREAD

**Issue by pemassi** [logto-io/logto#1758]
### Describe what you'd like Logto to have

Support `Kakao` social login.

https://developers.kakao.com/docs/latest/en/kakaologin/common#login-with-oidc

**Comment by charIeszhao** [comment]
Hmmm, we understand that KakaoTalk is very very popular in Korea, so this sounds a legit feature request. We'll take this into serious consideration and let you know once we work out a plan.

Thanks!

**Comment by pemassi** [comment]
@charIeszhao No worries! I am going to work on this feature!

**Comment by charIeszhao** [comment]
> @charIeszhao No worries! I am going to work on this feature!

Wow that's super cool! Thanks!
But we are currently refactoring our connector infrastructure, I recommend hold on for a couple days until we solidify our implementations. You can start research and register your testing account in kakao, though.

More details can be found in #1748. You can start your implementation once this PR merges.

**Comment by pemassi** [comment]
@charIeszhao Got it!
