### ISSUE TITLE
bug: Error after login to the admin console

### ISSUE THREAD

**Issue by polakmark** [logto-io/logto#1763]
### Describe the bug
After the initial setup following the instructions from the docs, I am not able to login. I got an invalid id token error. The account creation worked.

### Expected behavior
Login without error.

### How to reproduce?
```
podman run -e ALL_YES=1 -e NO_INQUIRY=0 -e TRUST_PROXY_HEADER=1 -e ENDPOINT=http://localhost:3001 -e DB_URL_DEFAULT=postgres://postgres:postgres@10.88.0.4:5432 -p 3001:3001 ghcr.io/logto-io/logto:prerelease
```

### Context

OS: mac OS
docker: podman version 4.1.1

### Screenshots
<img width="784" alt="Screenshot 2022-08-11 at 12 11 43" src="https://user-images.githubusercontent.com/40790346/184112595-a7111a95-b6f3-48e9-a9a3-19a301722a58.png">

**Comment by gao-sun** [comment]
@charIeszhao would you like to take a look? thanks

**Comment by charIeszhao** [comment]
Hi @polakmark, thanks for reporting. I will help investigate the issue.

Would you please let me know more of the details? I have some questions like:
* It seems you have successfully registered your admin account. Did this error happen when you tried to login with your newly created admin credentials?
* Is it possible to send me your idToken, which can be found in your localStorage?

Also, it would be great if you can join our [Discord Channel](https://discord.com/invite/UEPaF3j5e6).

Cheers

**Comment by polakmark** [comment]
@charIeszhao 
Yes I did register succesfully. yes the same thing happened when I tried to login, I even tried to login from a different browser and I got the same result.

It is interesting but I don't have an id token in my localstorage, but I got one from the token response. I included the whole response, and the content of my localstorage.

```json
{"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCIsImtpZCI6Ikl0ZkVpSEM3NlZVMU9GYlRVRXVrdGtBdC1KTTNHa19qZ2I4Wi1ZTTVkRlEifQ.eyJyb2xlX25hbWVzIjpbImFkbWluIl0sImp0aSI6IlJaNmNXVk8zYklHTlRYSzNtV0lBdyIsInN1YiI6InZtWGpwbm43UVFvUSIsImlhdCI6MTY2MDE0ODIxMSwiZXhwIjoxNjYwMTUxODExLCJzY29wZSI6IiIsImNsaWVudF9pZCI6ImFkbWluLWNvbnNvbGUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDEvb2lkYyIsImF1ZCI6Imh0dHBzOi8vYXBpLmxvZ3RvLmlvIn0.XwQasEqzottC_JPiKvUxUmxhmn_BOBv90w1n0xmU6Ffjwc-GLf2nyTvPDQOiE0tGJf1qpIbdH-eN4LigwVXhdPNUdvyweBx5eQ1i4JRY0ZSoor7XmJzW4GKBjLm6H7SlFICI1eIAWx1IgRK6TohV2NHTgwPhKakU7_Jtng9Q4zl9yOQNHNkjgnY0_Krq0gj7JFphqj7KY4lOohQpU6DL8ybvNncH2mo-_QMKbFkcydEgIoa1Lr4EgguZyVzOy2IvFQwBzyA3jL59OCSkflmpj7896AL3B-IS-nUYf_cRbNeiSXSBy-FU7XNXeIQFF-LaDPcZrIbpL03mvKsCeBJCgT3d7KnjJl3mczUjg6vwHeJ0QMigzkJbl30uT5sHprJVgT2iWn2b4oaV1YRUUKSpdNXk3Gzp0QxLsAL_h36UbBhY7xQIDH8WzsLSo66WkD5L-ZGS__UA19cWsjTgvvr35FYpehqLBdkSmq_YIjZnr8j0aDcNMwbDOFmGB171uNA-HV6opofWKgmRQ5SJIXA_y-Nl0ySfNljU6tdZloRpaAvzIudoXZocfv1hymiyctkPG0UM8Bfes7JA1nizKAO8PQJqeXOUiC-iaG6j8Eb47tU6Iy6Mwvp8kZWvZPoDlt3M1cMfkd_z_t_K1w66YcxtYNavx0JlLtccKv1VRWOgIt0","expires_in":3600,"id_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ikl0ZkVpSEM3NlZVMU9GYlRVRXVrdGtBdC1KTTNHa19qZ2I4Wi1ZTTVkRlEifQ.eyJzdWIiOiJ2bVhqcG5uN1FRb1EiLCJ1c2VybmFtZSI6IkJlYXJkZWRCZWFzdCIsIm5hbWUiOm51bGwsImF2YXRhciI6bnVsbCwicm9sZV9uYW1lcyI6WyJhZG1pbiJdLCJhdF9oYXNoIjoiNGM0S2VJS3JqWnBRSl9NblJUS1JYdyIsImF1ZCI6ImFkbWluLWNvbnNvbGUiLCJleHAiOjE2NjAxNTE4MTEsImlhdCI6MTY2MDE0ODIxMSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAxL29pZGMifQ.F_rQPpTB1-f-xIBYcCYhWjkt2HKasRjr-7wepErvFLwQjIupD3veE6XwC-pdbXFKGcOGue6jjvRXS7rZuFwgeRK7j5fM1DMmkzQT0U8OWyFywGB0iFFcw9TaI7RgI5lipOUnH8NSMBTT9MaWfgTTYEaswy887C1G-K8iBS0eGxEFglurRY7NIGvEFOda4QuNF2od-mPWu29PMjvAFdd6OgbbS-wVNdpavtEpy3sJq_73m5xb5oC1UZvmsgy1YTbtD1O9VlR3uVQXpbB9umY1lwg61FW9YXaXYFqgeFE0xtU2MqklOIpJfzYW6ZzEzOABV4neevpSFiAxzVEdI3U-5NAMFMLhvRzV53X9n3UcH7D2Yn--O_LcKJk3smtyzauCp8gvZ2_cJ38GonAlmVibU5bh0mZn9L_aNdV1rfVgqpFrCPj4FS4FLyuGLOurMuN9pfDsHmcP0XjFPLJ4ubRlryG4EsijP9etG86Uug-SThlJ02njD3Yh3qqES6rPLaL0IdTk2_nRyidgZDiUTsSd3vw3RDaqme0fi3s0XUbuJtqbP8ulZD0gjO65PJJSSeyAnUVxxziOJlBBxLy0bLflqQY6WJFxMW_DnCf0YBt0dtTG-Pz7rSkJn-cBOaDHpie85mctztViTA519URYyYSm2vkW3jtkkIb0FZd2g3YPKHA","refresh_token":"jnEQNluO-9DoR-7nMfx6_yelXG84FxJT94VKrb73TPX","scope":"","token_type":"Bearer"}
```
this is all I have in my localstorage after the error shows up

```yaml
i18nextLogtoAcLng=en-US
logto:admin_console:theme=system
i18nextLogtoUiLng=en-US
```

**Comment by charIeszhao** [comment]
Hmmm, the idToken doesn't show up in your localStorage because its verification failed in prior, which is totally expected. Should have thought about this earlier, haha.

However, this is still a weird issue, as I just tried to decode your idToken and it seemed it was valid... I can see your user ID and username

Btw, are you testing it on your local machine? Are you using macOS or linux?

**Comment by polakmark** [comment]
@charIeszhao 
I am on mac os, I run logto in docker, with podman, my time settings are correct on my machine, I am in the CET timezone. Can a docker container have a time drift or different timezone settings? Anyway I attached to the container, and the container is Running on UTC but somehow instead of whole hour differences, the container is in the future 2h and 13 minutes. The 2 hour difference is correct as now it is summer time, but I don't know about the 1 min difference, can that cause the issue?

**Comment by polakmark** [comment]
I also checked now a different source of UTC time, and it looks like the container has drifted time to the future by 4 hours and 13min.

(measurements were made approximately in the same time, manually)
Wed Aug 10 18:18:50 UTC 2022 (container)
Thu 11 Aug 2022 16:05:42 CEST (Local time)
14:04 Thursday, August 11, 2022 (UTC from web multiple sources)

**Comment by charIeszhao** [comment]
The different timezone is fine. However the 1 min (or 13 mins??) difference is weird, and IMO it's probable to cause the issue. Can you try to sync your time on your server? Thanks!

**Comment by charIeszhao** [comment]
No, it's not drifted to the future by 4 hours, but instead drifted to the past by 20 hours... It should be approximately Aug 11 14:12 now in UTC timezone, but your container is still on yesterday (Wed Aug 10)

**Comment by polakmark** [comment]
Oh didnt checked the date, good eyes. The thing is the container is running on my local machine, and docker should work with my hw time, I will check if there is any possibility to somehow sync it. I did multiple restarts of the container but I got the same result. I will try some things, I will let you know if I find any solution. Thanks, at least I know what the issue is.

**Comment by polakmark** [comment]
@charIeszhao Thanks for all the help, I am in. The podman virtual machine was somehow out of sync, I had to ssh into it and manually sync the time. But now it works.

**Comment by charIeszhao** [comment]
Cool, you're welcome. Glad it helped.
