### ISSUE TITLE
feature request: Allow Email SMS gateways

### ISSUE THREAD

**Issue by alejandroiam** [logto-io/logto#1775]
Allow users to add their phone number and choose an email gateway (email to sms) to save on messaging cost.
kinda like the open source version of [textbelt](https://textbelt.com/) and how Callcentric does its authentication

![image](https://user-images.githubusercontent.com/62250256/184456384-2f3b35db-860d-4c39-8906-752a7f39a753.png)

**Comment by gao-sun** [comment]
Good point! @fleuraly would you like to take a look?

**Comment by gao-sun** [comment]
a think this is kind of resolved by our new sign-in experience since we now provide APIs to update user profile. @alejandroiam feel free to double check if it meets your needs and let us know
