### ISSUE TITLE
feature request:  table schema name style

### ISSUE THREAD

**Issue by waltcow** [logto-io/logto#1777]
### What problem did you meet?

Currently table name have some very general name style like `Log` which may conflicts with other SDK predeclared identifier

### Describe what you'd like Logto to have

add prefix for all tables like `lgt`

**Comment by gao-sun** [comment]
thanks @waltcow. our recommendation is to use a dedicated database for Logto, but still your request is valid.

before we are settle on it, if you would like, you can directly contribute this feature.

**Comment by waltcow** [comment]
thanks @gao-sun 
use a dedicated database wont't fix my issue. I want to develop another backend server like console with GoLang. 
when I generate schema related struct with ORM generator, it conflicts with its predeclared identifier.

**Comment by gao-sun** [comment]
@simeng-li @charIeszhao would you guys like to follow this thread? thanks cc @xiaoyijun

**Comment by gao-sun** [comment]
we don't have enough resource to do this. let me know if you are interested on contributing.
