### ISSUE TITLE
feature request: use hash-wasm to avoid rebuild

### ISSUE THREAD

**Issue by SOVLOOKUP** [logto-io/logto#1778]
### What problem did you meet?

Rebuilding argon2 takes too much time on the arm64 build, see =>  https://github.com/logto-io/logto/pull/1578

### Describe what you'd like Logto to have

Using https://github.com/Daninet/hash-wasm to replace argon2

**Comment by gao-sun** [comment]
this is cool! before we're working on it, you can contribute if you'd like.
