### ISSUE TITLE
feature request: MFA

### ISSUE THREAD

**Issue by savchenko** [logto-io/logto#1780]
### What problem did you meet?
Lack of MFA support (FIDO, WebAuthn)

### Describe what you'd like Logto to have

> _"Login with a tap on your Yubikey!"_

- OTP (Google Authenticator, etc.)
- Yubikey
- WebAuthn

**Comment by gao-sun** [comment]
thanks @savchenko. we'll start the product design in Q3 and likely ship it in Q4.

**Comment by gao-sun** [comment]
due to the limited resource, we moved this to 23Q2

**Comment by wangsijie** [comment]
MFA is ready, please see https://logto.io/products/mfa
