### ISSUE TITLE
feature request: .NET SDK

### ISSUE THREAD

**Issue by hussamelvani** [logto-io/logto#1791]
### What problem did you meet?

I want to use .NET/C# to build cross-platform apps (Xamarin, ASP.NET Core, etc.) but found no SDK.

### Describe what you'd like Logto to have

Support .NET/C#

**Comment by gao-sun** [comment]
hi @hussamelvani, your request is valid. currently we don't have a plan for .NET SDK (yet), if you are familiar with .net, you are more than welcome to contribute the SDK by following our [SDK Convention](https://docs.logto.io/docs/references/sdk-convention/).

**Comment by hussamelvani** [comment]
Hi @gao-sun,
I am familiar.
Thanks for linking the SDK Convention, I'll start working on it in the near future.

**Comment by gao-sun** [comment]
ASP.NET Core SDK is now available in https://github.com/logto-io/csharp

**Comment by gao-sun** [comment]
looks some .NET behaviors vary per platform, so we'll need different SDK for other platforms like Xamarin

**Comment by wangsijie** [comment]
@hussamelvani I am closing this issue now, as @gao-sun mentioned, the core SDK is ready. Feel free to create other issues on specific platform.
