### ISSUE TITLE
feature request: Disable user to create account on sign-in page

### ISSUE THREAD

**Issue by akarapol** [logto-io/logto#1825]
### What problem did you meet?

Primary login with user and password allow user to register themselves that is not secure and may be attack by bot to create spam accounts

### Describe what you'd like Logto to have
I think it should be an option  on Sign-in Experience screen to disable self register

**Comment by gao-sun** [comment]
Duplicate #1716?

**Comment by akarapol** [comment]
@gao-sun sorry to open the duplicate issue. I pull the tag=edge to test and it's work. thanks for your fast response.

**Comment by gao-sun** [comment]
> @gao-sun sorry to open the duplicate issue. I pull the tag=edge to test and it's work. thanks for your fast response.

no worries! glad it works
