### ISSUE TITLE
Docs/Feature request: Missing efficient way for backend dev to get AK for test

### ISSUE THREAD

**Issue by spencercjh** [logto-io/logto#1829]
### What problem did you meet?

After I carefully read through:
1. https://docs.logto.io/docs/recipes/protect-your-api/
2. https://docs.logto.io/zh-cn/docs/recipes/protect-your-api/spring-boot.

I got the spring boot app ready, and started the logto server by docker-compose, I found that it was still hard to get the AccessToken to run the whole demo in [docs](https://docs.logto.io/docs/recipes/protect-your-api/spring-boot/#access-protected-api).
I try to add dependencies of client SDK to test to get AK but I failed.

![image](https://user-images.githubusercontent.com/29922079/187129942-ad7b7256-629c-4a77-8787-6517e9bc487b.png)

![image](https://user-images.githubusercontent.com/29922079/187129912-3dc6ecae-db30-4773-9c04-d3cf76a356cd.png)

### Describe what you'd like Logto to have

It is clearly against your product design to explain all Oauth requests to the user. But I think since you have a docker compose for demos, why don't you launch an extra web page with route like `/demo/oidc` or something else to help users get the AccessToken, which can also explain more about the processes.

I'm following your go sdk, if I'm right it should be more oriented towards the CLI software audience. It would be acceptable to give me a piece of Go code to get AK.

**I am a pure backend dev**, and I am not familiar with frontend/client techniques. I usually mainly use gRPC and write Java and Go in my full-time job.

**Comment by gao-sun** [comment]
we're working on Machine to Machine apps. then it'll be much easier to fetch an Access Token then.

**Comment by gao-sun** [comment]
Machine to machine has launched in beta.10. Let me know how it works and if the issue can be closed.

**Comment by charIeszhao** [comment]
Closing the issue due to inactivity. Let me know if you want to reopen this one. Thank you.
