### ISSUE TITLE
feature request: arm64 docker image support

### ISSUE THREAD

**Issue by charIeszhao** [logto-io/logto#1837]
### What problem did you meet?

Currently when building the docker image from source on arm64 machine (e.g. Oracle A1 instance), it will fail with errors from puppeteer and parcel image optimizer plugin.

```
#0 100.1 .../node_modules/puppeteer install$ node install.js
#0 100.4 .../node_modules/puppeteer install: The chromium binary is not available for arm64.
#0 100.4 .../node_modules/puppeteer install: If you are on Ubuntu, you can install with:
#0 100.4 .../node_modules/puppeteer install:  sudo apt install chromium
#0 100.4 .../node_modules/puppeteer install:  sudo apt install chromium-browser
#0 100.4 .../node_modules/puppeteer install: ERROR: Failed to set up Chromium r1022525! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
#0 100.4 .../node_modules/puppeteer install: Error
#0 100.4 .../node_modules/puppeteer install:     at handleArm64 (/etc/logto/node_modules/.pnpm/puppeteer@16.1.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:138:11)
#0 100.4 .../node_modules/puppeteer install:     at BrowserFetcher.download (/etc/logto/node_modules/.pnpm/puppeteer@16.1.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:283:13)
#0 100.4 .../node_modules/puppeteer install:     at async downloadBrowser (/etc/logto/node_modules/.pnpm/puppeteer@16.1.0/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:65:5)
#0 100.4 .../node_modules/puppeteer install: Failed
#0 100.4  ELIFECYCLE  Command failed with exit code 1.
```

```
#0 76.14 @logto/ui: > tsc --noEmit
#0 77.86 @logto/demo-app: Building...
#0 84.35 @logto/demo-app: Bundling...
#0 85.16 @logto/demo-app: 🚨 Build failed.
#0 85.18 @logto/demo-app: Error: Error relocating
#0 85.18 @logto/demo-app: /etc/logto/node_modules/.pnpm/@parcel+optimizer-image@2.7.0_@parcel+core@2.7.0/node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node:
#0 85.18 @logto/demo-app:  __crc32w: symbol not found
#0 85.19 @logto/demo-app:   Error: Error relocating
#0 85.19 @logto/demo-app:   /etc/logto/node_modules/.pnpm/@parcel+optimizer-image@2.7.0_@parcel+core@2.7.0/node_modules/@parcel/optimizer-image/parcel-image.linux-arm64-musl.node:
#0 85.19 @logto/demo-app:    __crc32w: symbol not found
#0 85.19 @logto/demo-app:       at Object.Module._extensions..node
#0 85.19 @logto/demo-app:   (node:internal/modules/cjs/loader:1210:18)
#0 85.19 @logto/demo-app:       at Module.load (node:internal/modules/cjs/loader:1004:32)
#0 85.19 @logto/demo-app:       at NodePackageManager.load
------
failed to solve: executor failed running [/bin/sh -c pnpm -- lerna run build --stream]: exit code: 1
```

### Describe what you'd like Logto to have

It would be nice if we can provide a way to get around this or a runnable arm64 image directly on ghcr or docker hub.

**Comment by Huskehhh** [comment]
Have been able to get it to work with the following Dockerfile, although not on Alpine.

```Dockerfile
# Build stage
FROM node:16-bullseye as builder
WORKDIR /etc/logto
ENV CI=true
COPY . .

# Install toolchain
RUN npm add --location=global pnpm@^7.2.1
# https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#node-gyp-alpine
RUN apt install -y python3 make g++

# Install dependencies and build
ENV PUPPETEER_SKIP_DOWNLOAD=1
RUN pnpm i
RUN pnpm ci:build

# Add official connectors
WORKDIR /etc/logto/packages/core
RUN pnpm add-official-connectors
WORKDIR /etc/logto

# Prune dependencies for production
RUN rm -rf node_modules packages/*/node_modules
ENV PUPPETEER_SKIP_DOWNLOAD=1
RUN NODE_ENV=production pnpm i

# Clean up
RUN rm -rf .parcel-cache pnpm-*.yaml

# Seal stage
FROM node:16-bullseye as app
WORKDIR /etc/logto
COPY --from=builder /etc/logto .
EXPOSE 3001
ENV NO_INQUIRY true
ENTRYPOINT ["npm", "start"]
```

**Comment by quiint** [comment]
Any update on ARM support? This would be a great feature to have in Logto

**Comment by gao-sun** [comment]
we didn't have resource on this, but it's open for bounty

**Comment by outranker** [comment]
I wanted to run this on my Raspberry Pi 4 but the image architecture was for only amd64. I tries building on my pi but when I did so I got the same error as OP. After some googling, I found out that the error has something to do with parcel image optimizer and it needs to be turned off? The link is [here](https://stackoverflow.com/questions/69783896/how-do-i-resolve-parcel-optimizer-image-error). The solution or rather workaround requires creating `.parcelrc` file whose contents are like below:
```js
{
  "extends": "@parcel/config-default",
  "optimizers": {
    "*.{jpg,jpeg,png}": []
  }
}
```
I placed this file in all packages that used (or I though it used) `parcel+image-optimizer` such as `demo-app`, `ui`, `console` etc.

It looks like that helped!

**Comment by gao-sun** [comment]
i think the biggest blocker now is the [looooong build time](https://github.com/logto-io/logto/actions/runs/3821409132/jobs/6500529987), as GitHub doesn't have arm64 runners (even for the paid plan)

**Comment by Huskehhh** [comment]
Oracle cloud free tier ARM instances could provide helpful here.

**Comment by pemassi** [comment]
@gao-sun Looks like this project might help to solve this problem. 

https://github.com/uraimo/run-on-arch-action

This action helps emulate arm64 architecture.

**Comment by Huskehhh** [comment]
> @gao-sun Looks like this project might help to solve this problem.
> 
> [uraimo/run-on-arch-action](https://github.com/uraimo/run-on-arch-action)
> 
> This action helps emulate arm64 architecture. And It may show better performance?

From the looks of things, QEMU is already being used to emulate arm64 but on an x86_64 runner. 
The pain point here is emulating ARM.

**Comment by maslow** [comment]
Perhaps you could start with a document explaining how to build an arm64 mirror manually, so that users with needs can build it themselves?

**Comment by quiint** [comment]
> Perhaps you could start with a document explaining how to build an arm64 mirror manually, so that users with needs can build it themselves?

In case this can help, I have a [Docker image](https://hub.docker.com/r/0xquii/logto) (that probably doesn't do it in the best way but it does work) that lets Logto work on ARM. 
It's worked for me so far, so it might work for you 🤷‍♂️

**Comment by gao-sun** [comment]
created #3116 to resolve this issue by building arm64 image per release

**Comment by gao-sun** [comment]
https://github.com/logto-io/logto/pkgs/container/logto/70777267?tag=1.0.0-rc.1
https://hub.docker.com/r/svhd/logto/tags

now arm is supported on `v1.0.0-rc.1`, and will be available in future releases
