### ISSUE TITLE
bug: Connection to SSL DB: Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by flobaader** [logto-io/logto#1842]
### Describe the bug
I use a DigitalOcean Managed Postgres database for the deployment, but get the following error when starting the logto container:

```
Error while initializing app Error: self signed certificate in certificate chain
at TLSSocket.onConnectSecure (node:_tls_wrap:1535:34)
at TLSSocket.emit (node:events:513:28)
at TLSSocket._finishInit (node:_tls_wrap:949:8)
at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:730:12) {
code: 'SELF_SIGNED_CERT_IN_CHAIN'
```

### Expected behavior
Logto should be able to connect to SSL only databases.

### How to reproduce?
1. Get a hosted DB at DigitalOcean
2. Configure the Logto Docker Container like this

### Alright tried

I tried to use the following env vars to circumvent the problem:

```
- NODE_TLS_REJECT_UNAUTHORIZED='0'
- PGSSLMODE=no-verify
```

### Context

OS: Linux
Docker: ghcr.io/logto-io/logto:1.0.0-beta.6

**Comment by flobaader** [comment]
There are a lot of people with the same problem:
https://www.digitalocean.com/community/questions/not-connected-error-self-signed-certificate-in-certificate-chain-while-connecting-to-postgres

https://www.digitalocean.com/community/questions/error-self-signed-certificate-in-certificate
https://www.adrianhorning.com/digital-ocean-app-platform-ssl-certificate-node-postgres/
https://www.digitalocean.com/community/questions/can-t-connect-to-managed-database-self_signed_cert_in_chain-error

**Comment by charIeszhao** [comment]
@flobaader I'm not quite sure about this one. Are you using a self-signed certificate? Will this still happen if you issue your certificate by a trusted CA?

**Comment by flobaader** [comment]
@charIeszhao If had this issue while connecting to a managed Digital Ocean DB and also a managed aiven.io database.

The hotfix would be to have an environment variable that allows to trust the SSL cert of the database. That env var has to be passed to the database client.

I am not sure what the underlying problem is, because many tools can easily connect to the databases without any problems. Probably missing root certificates in the docker container.

**Comment by flobaader** [comment]
Another option would be to allow to specify the CA Cert values in the env section.

**Comment by flobaader** [comment]
@charIeszhao The SSL signing is not in my hand on a managed Database. This is done by DigitalOcean, AWS or Google Cloud. So we just have to accept the SSL certs that are issued by them.

**Comment by charIeszhao** [comment]
But do you have access to the Digital Ocean instance? Can you change the way that they issue the cert?
I mean, you can always use something like `Let's Encrypt` to issue a trusted cert for free.

The digital ocean also has a step by step guide on it: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04

**Comment by flobaader** [comment]
@charIeszhao No it's not a VPS - its a managed Database https://www.digitalocean.com/products/managed-databases-postgresql

**Comment by flobaader** [comment]
@charIeszhao Basically LogTo will be unsable for our business usecase if those managed databases are not supported, because we rely on managed databases and do not host or control the database ourselves.

**Comment by charIeszhao** [comment]
Well, I still don't quite understand why the managed databases Digital Ocean provided are using self-signed certs. But anyways I'll give it a try today to see how it works.

**Comment by flobaader** [comment]
@charIeszhao did you succeed in connecting to the managed database?

**Comment by charIeszhao** [comment]
@flobaader I'm terribly sorry, that I wasn't able to do it recently, as we have some hard milestone to complete by the end of Q3, and the team is really dedicated right now to deliver the cool stuff.
I will try it next week during the national holidays, and let you know if I find anything. Thank you for your patience.

**Comment by flobaader** [comment]
@charIeszhao Alright thank you, looking forward to your results!

**Comment by akoenig** [comment]
@flobaader, just want to add my research results here. When connecting to a database with SSL you have to tell the Node.js runtime to "trust" the self-signed certificate which comes (in your case) from Digital Ocean:

```sh
NODE_EXTRA_CA_CERTS=/path/to/your/ca/from/digitalocean.crt
```

Had a similar issue today and want to share my experience 🙂 You can read more about this environment variable [here](https://nodejs.org/api/cli.html#node_extra_ca_certsfile).

**Comment by charIeszhao** [comment]
Thanks, @akoenig. I saw the discussion from you and Gao on Discord yesterday. This looks promising and we will document it on our docs site if that also works for @flobaader

**Comment by flobaader** [comment]
@charIeszhao Sorry for the long waiting time - I can confirm that the managed DB is now working with the  `NODE_EXTRA_CA_CERTS` option.

**Comment by charIeszhao** [comment]
Great! Thank you for the update. 👍
I'm closing this issue as resolved.

**Comment by DavidTheProgrammer** [comment]
> @charIeszhao Sorry for the long waiting time - I can confirm that the managed DB is now working with the `NODE_EXTRA_CA_CERTS` option.

This wasn't working for me for the better part of a day, If anybody else runs into an error that looks like the following:

`Warning: Ignoring extra certs from `"/opt/certs/do.crt"`, load failed: error:80000002:system library::No such file or directory` 

Make sure you're not mounting the path for the `NODE_EXTRA_CA_CERTS` env var as a string; `NODE_EXTRA_CA_CERTS="/opt/certs/do.crt"` won't work but `NODE_EXTRA_CA_CERTS=/opt/certs/do.crt` will.
