### ISSUE TITLE
Eliminate all `icons/*.tsx` files and use svg instead

### ISSUE THREAD

**Issue by charIeszhao** [logto-io/logto#1853]
Previously when we need to dynamically change the color of an SVG image, we had to wrap the SVG elements in a tsx file, and import it as a component in other page components.

But now we are using `@parcel/transformer-svg` plugin, which helps automatically transform a regular SVG file into a React component, and we are able to import it as component directly in other page components. (Example usage can be found in `src/pages/GetStarted/hook.ts`)

Therefore, we need to clean up the previously created *.tsx files in `src/icons`, and create *.svg files in `src/assets` instead.

**Comment by b4s36t4** [comment]
Did anyone started working on this?

**Comment by charIeszhao** [comment]
> Did anyone started working on this? 

Not yet. First come, first served!

**Comment by charIeszhao** [comment]
@b4s36t4 Hi, any updates? Let me know if you have any blocker and we can help you out

**Comment by charIeszhao** [comment]
@b4s36t4 I'm unassigning the ticket due to inactivity of more than 3 weeks. Please let me know if you still want to take this. Thanks!
