### ISSUE TITLE
Investigate the randomly spotted `dev: true` in pnpm-lock.yaml

### ISSUE THREAD

**Issue by charIeszhao** [logto-io/logto#1855]
When executing `pnpm i`, we notice that sometimes in pnpm-lock.yaml there are numerous `dev: true` lines added for each dependency.

This is a bit weird and totally unexpected. We would like to know the reason why and a possible solution to avoid this behavior.

For example this one: https://github.com/logto-io/logto/pull/1043#discussion_r888144674

**Comment by b4s36t4** [comment]
I think they might be added cause that the packages might be `devDependencies`. I've seen most of the packages that are mentioned under `devDependencies` are having the `dev:true` 

dev:true with devDependency
<img width="1015" alt="Screenshot 2022-09-01 at 11 23 18 PM" src="https://user-images.githubusercontent.com/59088937/187980433-50a77833-4bad-4907-8f1e-92ace2096098.png">

No `dev:true` for this one.
<img width="853" alt="Screenshot 2022-09-01 at 11 23 55 PM" src="https://user-images.githubusercontent.com/59088937/187980519-e5c1419b-734c-4026-a218-fea3875c0c95.png">

Just like so there are many under dev most of them are `devDependencies`.

I don't think there is nothing we can do.

**Comment by gao-sun** [comment]
@charIeszhao would you like to add more context?

**Comment by charIeszhao** [comment]
I think this one has been taken by Olyno last night [on Discord](https://discord.com/channels/965845662535147551/965845662979719198/1014875162597929082), though he hasn't commented yet on Github issues.
And I have provided detailed context on Discord, that sometimes even if we bump a dev dependency version (the package has always been in dev dependencies list), we still see these `dev: true` in pnpm lock file.

For example this one:
https://github.com/logto-io/logto/pull/1043#discussion_r888144674

**Comment by saiswaroopmaddi** [comment]
@charIeszhao @b4s36t4 @gao-sun 

I checked this issue in different projects, which is also addressed here in lerna: [https://github.com/lerna/lerna/issues/1256](https://github.com/lerna/lerna/issues/1256)

Even though it doesn't impact, `package-lock.json` will be shown changes and developer might push them to the repository. 
So, the quick workaround I found is to write a pre-commit script (or using husky) were we can check if `package.json` is changed or not if not then there is no point of pushing changes in `package-lock.json ` we just revert it back using the script itself, else we allow it in the file changes.

I hope this works. I can take up this task if my idea works for you guys.

**Comment by charIeszhao** [comment]
@saiswaroopmaddi Thanks for the information. But I think differently, as we are not using npm, but pnpm. And the issue is seen in pnpm's lock file (pnpm-lock.yml). According to pnpm, the `dev: true` indicates the package is used as a dev dependency.
However, our issue is, even if we are always using a package as devDependency, and sometimes we just bump the version of it, we still end up seeing tons of `dev: true` in the lock file.

**Comment by saiswaroopmaddi** [comment]
This issue is also there in npm too.
Ofcourse, yes if you change the version of one of the devDependency package, then we see this issue because npm re-check all devDependency packages and set this property to all the qualified packages.

**Comment by charIeszhao** [comment]
Hmmm, but if you check the link I provided, you'll see we only bumped our own package (@logto/react), and there was no related dev dependency changes at all in that upgrade.

**Comment by saiswaroopmaddi** [comment]
If you are using some devDependencies in your own package, then changing version of your own package will also trigger this check and adds this. You can try reproducing it. This is because one way or other packages depend on other (devDependencies or non-devDependencies) so npm or pnpm mark that as dev:true.

**Comment by saiswaroopmaddi** [comment]
@charIeszhao  Are you referring to this PR: [https://github.com/logto-io/logto/pull/1043](https://github.com/logto-io/logto/pull/1043)?

If so, then in my observation most of the sub-projects in log2 monorepo using devDependencies which causes this.

Here, where npm written the same thing: https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#:~:text=dev%2C%20optional%2C%20devOptional,and%20optional%20set.)

Now, the @logto/react is under devDependencies inside [packages/console/package.json](https://github.com/logto-io/logto/pull/1043/files#diff-b0a77b753d2866d9c2f906f689d07a056abc42f4e50d4a302d2b193889430522).

Dev: true will be set, if the this dependency is either a development dependency ONLY of the top level module or a transitive dependency of one. This is false for dependencies that are both a development dependency of the top level and a transitive dependency of a non-development dependency of the top level.

**Comment by charIeszhao** [comment]
Yes, but the `@logto/react` has always been a "top level module" in the `devDependencies` for months, before being added the `dev: true` label. What you said is true, but it can't explain the change from `dev: false` to `dev: true`, isn't it? @saiswaroopmaddi

**Comment by saiswaroopmaddi** [comment]
Hey, if you remember, can you tell me what command used for installation after changing the version? And is there any env used while installing?

**Comment by saiswaroopmaddi** [comment]
Along with the above comment AFAIK, possible reasons are:
- mismatch in Node version or NPM (or PNPM) version across the contributor will lead to these changes.
- Lock files are kind of indeterminant from machine to machine. Installing same packages on intel and installing on M1 creates a differences like this. [[Refer](https://stackoverflow.com/questions/44748073/npm5-package-lock-json-different-entries-on-different-machines)]

Proposed solution:
- Adding a pre-install script which forces developers to have particular versions of Node and NPM(or PNPM)
- Use `save-exact` while installing, else the default semver operator of (NPM or PNPM) will lead to these changes.

**Comment by charIeszhao** [comment]
> Hey, if you remember, can you tell me what command used for installation after changing the version? And is there any env used while installing or any flags?

The command is always `pnpm i`

**Comment by saiswaroopmaddi** [comment]
Cool, okey. Can you also verify this https://github.com/logto-io/logto/issues/1855#issuecomment-1254485643?

**Comment by charIeszhao** [comment]
In our team we are all using pnpm and M1 pro. So to me it's not due to the mix use of any of these

**Comment by saiswaroopmaddi** [comment]
And also the node and pnpm versions are same?

**Comment by gao-sun** [comment]
@charIeszhao

**Comment by charIeszhao** [comment]
> And also the node and pnpm versions are same?

Sorry for the late response. 

Yes, the node and pnpm versions are both the same, before and after... And even if we upgraded pnpm regularly, we can still see this occationally as of today. So to me this now seems to be a trivial bug on pnpm side. But since it doesn't break anything (except for being a bit weird), people really don't care about it that much.

I personally don't think we can do anything on our side, so I'm closing the ticket. Thank you all for scratching your head trying to figure it out. Much appreciated!

Please also take a look at other bounties that we posted. Thank you for supporting Logto!
