### ISSUE TITLE
bug: There is no reaction to signout button. 

### ISSUE THREAD

**Issue by TarzanZhao** [logto-io/logto#1856]
### Describe the bug

I try building my own react project with Logto. I follow the instruction from [React: Integrate @logto/react](https://docs.logto.io/docs/recipes/integrate-logto/react/) very carefully. However, when I pressed the signout button, nothing happened. I did not need to log in again after pressing the signout button.

**Comment by charIeszhao** [comment]
Hi @TarzanZhao , can you provide more context? It would be great if you can provide a minimum reproducible example

**Comment by TarzanZhao** [comment]
Thank you! This is my code repo: https://github.com/TarzanZhao/test_logto_reach
This [link](https://github.com/TarzanZhao/test_logto_reach/blob/9ec2f754e1dd21f710397a55cae6b1ae6ddbaf0e/src/Callback.js#L39-L45) is where I use signout.

This is a very simple project and it is only used for testing log in and log out.

**Comment by TarzanZhao** [comment]
I could not find signout logs in Postgres log table either.

**Comment by gao-sun** [comment]
would you like to follow the issue template? we still need to figure out these info even if you delete them manually.

**Comment by gao-sun** [comment]
feel free to contact us to re-open the issue once the template has been filled.

**Comment by TarzanZhao** [comment]
get it! sorry for not following the template.
