### ISSUE TITLE
bug: Admin console theme should follow its own settings, instead of being affected by "sign-in experience"

### ISSUE THREAD

**Issue by charIeszhao** [logto-io/logto#1858]
Logto admin console is a special app, independent from all the regular apps you can create / delete in the "Applications" page.

However, there's a bug that even though it is a special app, its sign-in page still inherit something from the general "sign-in experience" settings, which is for the "regular apps". The theme of the sign-in form is one of these things.

Currently, even you have configured "force dark theme" in admin console settings, its sign-in form will still load theme settings from sign-in experience. So in case that dark theme is not enabled in "sign-in experience", when signing in admin console, you will still see a "light theme" sign-in form, instead of the expected "dark theme" form.

**Expected behavior:**
Sign-in page of the admin console should load from admin console's own theme settings, not from "sign-in experience" theme settings, which is for "regular apps".

**Comment by gao-sun** [comment]
maybe we can provide some screenshots

**Comment by 5war00p** [comment]
Hey, @charIeszhao can I take up this?

**Comment by 5war00p** [comment]
I see we are using the `use-theme` hook for the entire admin console but in `signin-experience` components which seems a common component verifies whether the dark mode is enabled or using the SignInExperience Form FieldWatcher.

Correct me if I'm wrong.

**Comment by charIeszhao** [comment]
@5war00p Sorry for the late response. We had couple days off to celebrate national holidays, and just get back to work today. And sure yes, you can take this up and try to figure it out. 👌🏻

As for the root cause, you are almost there. In admin console, we use the `use-theme` hook wherever possible to determine the theme color.

However, the sign-in page of admin console is an independent webapp, called `ui` in our monorepo. So the sign-in page loads its theme from another source, which is used for all the "normal apps" that you created. And this causes the inconsistent between admin console app itself and its sign-in page.

I hope this clarifies things for you. And I'm assigning the ticket to you, please let me know if you have any further questions. You can also ping me any time on Discord.

Thanks,
Charles

**Comment by 5war00p** [comment]
PR: https://github.com/logto-io/logto/pull/2293

**Comment by charIeszhao** [comment]
Not an issue any more and instead is a by-design feature for admin console sign-in to always "auto detect" system theme settings.
