### ISSUE TITLE
Guard redirect URI for native apps with custom schemes

### ISSUE THREAD

**Issue by charIeszhao** [logto-io/logto#1860]
### Description

In admin console, we can configure `redirect URIs` for each application. However, per [RFC specs](https://www.rfc-editor.org/rfc/rfc8252#section-8.4), for native apps, the URI must be a reverse domain name based schemes, e.g. `com.mycompany.demo://callback`.

Currently, in admin console we do not have extra validation for these native app custom schemes, so that any valid URI format string will be accepted, e.g. `http://localhost:3000`. But our underline OIDC provider will check the URI for native app, and it will fail with an `invalid_redirect_uri` error if the format is invalid.

[Its validation logic](https://github.com/panva/node-oidc-provider/blob/d4ae0c74ab4b6212966b40ea8900a7943aff5ffc/lib/helpers/client_schema.js#L605-L621) is quite simple, though, as it only checks if the custom schems URI contains a `.`, any URI without a dot will be considered as invalid.

### Expected behavior:

We would like to add the validation guard on both admin console front-end and backend API, with the same logic. And prompt user friendly error messages to the end users.

**Comment by b4s36t4** [comment]
Can I work on this?

**Comment by charIeszhao** [comment]
> Can I work on this? 

Sure, why not? You are more than welcome to become our first bounty hunter.

**Comment by b4s36t4** [comment]
@charIeszhao @gao-sun Create PR for this one. Please leave a review.
