### ISSUE TITLE
feature request: new connector Naver

### ISSUE THREAD

**Issue by pemassi** [logto-io/logto#1867]
### Describe what you'd like Logto to have

`Naver` is a famous internet service provider like `Google` in South Korea

I believe that by adding `Naver` connector, Korean developers will use `Logto` more!

**Comment by pemassi** [comment]
I will work on this issue!

**Comment by charIeszhao** [comment]
Cool! 🚀

**Comment by darcyYe** [comment]
Cool! Looking forward to it!

**Comment by wangsijie** [comment]
@pemassi thanks! FYI: we introduced a new repo for [connectors](https://github.com/logto-io/connectors) together with a breaking change, which is expected to ship after next week.

**Comment by pemassi** [comment]
@wangsijie Got it. I will work on that repo.
