### ISSUE TITLE
feature request: spring boot starter

### ISSUE THREAD

**Issue by pemassi** [logto-io/logto#1870]
### Describe what you'd like Logto to have
I have looked roadmap and the team decided to not build SDK. ([logto-io/roadmap/#22](https://github.com/logto-io/roadmap/issues/22))

I think make `logto-spring-boot-starter` helps a lot of developers to build their project in short time like `Keycloak` (https://mvnrepository.com/artifact/org.keycloak/keycloak-spring-boot-starter)

**Comment by IceHe** [comment]
@pemassi you want to use `spring-boot-starter` to build a Tradition web app (like Spring Boot + JSP/[Thymeleaf](https://www.thymeleaf.org/)) or a resource server only?

**Comment by simeng-li** [comment]
Hey @pemassi. Thx for asking. We have a [Protect your API on Spring Boot
](https://docs.logto.io/docs/recipes/protect-your-api/spring-boot) backend integration guide provided. Which gives detailed instructions on how to use `spring security` and Logto authorization token to apply authorization to the Spring Boot server. 

In terms of client SDK for a SpringBoot-based traditional web, we did some brief research and very few Spring traditional web applications were found. So we decide not to mark the Spring client SDK in our roadmap so far. 

Let me know if this makes sense to you, and any use cases you may find.

**Comment by pemassi** [comment]
@IceHe Resource server only!

@simeng-li The documentation is well documented. However, it looks like there is no rule-based API resource protection. This instructor explains the features that I want. 

https://www.baeldung.com/spring-boot-keycloak

**Comment by simeng-li** [comment]
Got you. Absolutely, it's a hard requirement to have rule-based API resource protection on a spring server. A fully functioned Role-based access control is on our Q4 road map. We will fulfill this Spring Integration Guided with more `rule-based` validation instructions by that time.   Thx for your report.  Let's keep the thread open and we will keep you posted once it's done. Any feather feedbacks are welcome.

**Comment by gao-sun** [comment]
@pemassi @simeng-li can this be considered as resolved since we added a dedicated spring book tutorial? feel free to let me know your thoughts.

**Comment by pemassi** [comment]
@gao-sun LGTM!
