### ISSUE TITLE
bug: vue2 LogtoClient  getOidcConfig

### ISSUE THREAD

**Issue by zhoutaiping** [logto-io/logto#1886]
ERROR  Failed to compile with 1 error                                                                      上午10:23:51

 error  in ./node_modules/@logto/client/lib/module.js

Module parse failed: Unexpected token (87:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| class $19775a679e2952df$export$2e2bcd8739ae039 {
>     getOidcConfig = (0, $kqBTI$lodashonce)(this._getOidcConfig);
|     getJwtVerifyGetKey = (0, $kqBTI$lodashonce)(this._getJwtVerifyGetKey);
|     accessTokenMap = new Map();

 @ ./node_modules/@logto/browser/lib/module.js 1:0-378 44:22-60 55:59-77 57:30-52 70:0-347 70:0-347 70:0-347 70:0-347 70:0-347
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options!./src/views/login/index.vue?vue&type=script&lang=js&
 @ ./src/views/login/index.vue?vue&type=script&lang=js&
 @ ./src/views/login/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://172.20.1.136:4670&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by charIeszhao** [comment]
Hi @zhoutaiping , thanks for reaching out. But please DO follow our issue template when creating new tickets, and fill in the necessary information such as "Steps to reproduce". This will help us better understand your issue and quickly jump in to it.

Vue 2 is currently not supported. Please refer to our Vue SDK documentation for more details: https://docs.logto.io/docs/recipes/integrate-logto/vue

I'm closing the ticket right now. Feel free to contact us to re-open the issue **once the template has been filled**, and you would like Logto to support Vue 2.

Thanks!

**Comment by zhoutaiping** [comment]
my vue2 project user @logto/browser   
node.js version v14.18.2
main.js ->   import LogtoClient from '@logto/browser'
console error  ->
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
getOidcConfig  not loader

**Comment by zhoutaiping** [comment]
Vue2 project should be use   import LogtoClient from '@logto/browser',
use '@logto/browser' Will report an error
But I don't know what NPM package he lacks

**Comment by charIeszhao** [comment]
Hi @zhoutaiping , as what we stated in the @logto/browser [README](https://github.com/logto-io/js/tree/master/packages/browser#what-is-this-and-how-does-it-work), the browser SDK is not expected to be used directly in your client application.

Please consider upgrading to Vue 3 as we have official Vue SDK for Vue 3 and its composition APIs. If you have to use Vue 2 I think you can only convert this ticket into a "Feature Request" and we'll evaluate the need and probably put it on the roadmap.

You can also consider contributing the Vue SDK to make it compatible for Vue 2. We'll appreciate that and send you an Amazon gift card as a reward.

Best,
Charles
