### ISSUE TITLE
bug: cannot open Settings

### ISSUE THREAD

**Issue by Alecyrus** [logto-io/logto#1890]
I can not open `Settings`.

### Describe the bug
<img width="652" alt="CleanShot 2022-09-07 at 01 42 31@2x" src="https://user-images.githubusercontent.com/13865581/188703580-b07b5a3b-4a03-48bd-b70f-b81d5f36224a.png">

<img width="908" alt="CleanShot 2022-09-07 at 01 39 47@2x" src="https://user-images.githubusercontent.com/13865581/188703231-85061893-7d8f-48b0-b243-ea52113a6962.png">

Logto version:  svhd/logto:prerelease
Postgres version: 14

**Comment by gao-sun** [comment]
Thanks for reporting. @charIeszhao would you like to take a look?

@simeng-li can you add an issue for AC smoke tests to make sure every tab can be rendered? Thanks

**Comment by simeng-li** [comment]
Added
