### ISSUE TITLE
Add unit test cases to our regular expressions

### ISSUE THREAD

**Issue by charIeszhao** [logto-io/logto#1906]
In `@logto/shared` package, there are several regular expressions defined in `src/regex.ts`. Create unit test cases to ensure the correctness of the expressions.

**Comment by charIeszhao** [comment]
> @charIeszhao, Happy to work on it, can I be assigned?

Sorry, buddy. I think you have taken too many bounties right now. Leave something for the others, will ya? 🤣 
Will find some more challenging task for you in the next few weeks, since you are already a veteran now. Stay tuned!

**Comment by waveywaves** [comment]
Can I take this one up ? :)

**Comment by charIeszhao** [comment]
> > > @charIeszhao, Happy to work on it, can I be assigned?
> > 
> > 
> > Sorry, buddy. I think you have taken too many bounties right now. Leave something for the others, will ya? 🤣 Will find some more challenging task for you in the next few weeks, since you are already a veteran now. Stay tuned!
> 
> Ahaha, right. Okay np, I'm sorry

lol, no worries

**Comment by charIeszhao** [comment]
Hi @waveywaves, how's is going man?

I'm writing to let you know that the `@logto/shared` has been moved to `@logto/core-kit` in [logto-io/toolkit](https://github.com/logto-io/toolkit).

Feel free to let me know if you have any questions. Thanks!
Charles
