### ISSUE TITLE
bug: Error installing Logto Dev Encironment on macOS Monterey 12.5.1

### ISSUE THREAD

**Issue by jackm9367** [logto-io/logto#1911]
### Describe the bug
Attempting to download source and run dev server results in an app crash of @logto/core. It seems as though this is during the key generation process for first-startup. Unable to access ui (port 5001), console (5002), or demo-app (5003)

### Expected behavior
Expected dev server to compile code and prompt for first-time key generation (with bug as per contributing guidelines), with console, ui, and demo-app accessible on their respective ports. 

### How to reproduce?
1. Fork and clone source
2. Run `pnpm i` to install dev dependencies
3. Run `pnpm dev` to attempt to run dev server
4. Error

### Context

OS: macOS 12.5.1 Monterey

Environment: Local from source

Logto version: Built from source

Node version: v16.17.0

Postgres version: 14.5

Command of starting Logto: `pnpm dev`

### Screenshots
<img width="534" alt="Screen Shot 2022-09-09 at 11 08 39 pm" src="https://user-images.githubusercontent.com/42113446/189363261-c4810ecf-9ee8-40ff-b382-3b137433a3ea.png">
- Screenshot of console when trying to access UI

### Console output
$ pnpm dev

\> @logto/root@ dev /Users/jackmiller/logto-1859
\> lerna run --stream prepack -- --incremental && lerna --ignore=@logto/integration-test run --parallel dev

lerna notice cli v5.0.0
lerna info Executing command in 5 packages: "pnpm run prepack --incremental"
@logto/shared: > @logto/shared@1.0.0-beta.9 prepack /Users/jackmiller/logto-1859/packages/shared
@logto/shared: > pnpm build "--incremental"
@logto/shared: > @logto/shared@1.0.0-beta.9 build /Users/jackmiller/logto-1859/packages/shared
@logto/shared: > rm -rf lib/ && tsc -p tsconfig.build.json "--incremental"
@logto/phrases-ui: > @logto/phrases-ui@1.0.0-beta.9 prepack /Users/jackmiller/logto-1859/packages/phrases-ui
@logto/phrases-ui: > pnpm build "--incremental"
@logto/connector-core: > @logto/connector-core@1.0.0-beta.9 prepack /Users/jackmiller/logto-1859/packages/connector-core
@logto/connector-core: > pnpm build "--incremental"
@logto/phrases: > @logto/phrases@1.0.0-beta.9 prepack /Users/jackmiller/logto-1859/packages/phrases
@logto/phrases: > pnpm build "--incremental"
@logto/phrases-ui: > @logto/phrases-ui@1.0.0-beta.9 build /Users/jackmiller/logto-1859/packages/phrases-ui
@logto/phrases-ui: > rm -rf lib/ && tsc "--incremental"
@logto/phrases: > @logto/phrases@1.0.0-beta.9 build /Users/jackmiller/logto-1859/packages/phrases
@logto/phrases: > rm -rf lib/ && tsc "--incremental"
@logto/connector-core: > @logto/connector-core@1.0.0-beta.9 build /Users/jackmiller/logto-1859/packages/connector-core
@logto/connector-core: > rm -rf lib/ && tsc "--incremental"
@logto/schemas: > @logto/schemas@1.0.0-beta.9 prepack /Users/jackmiller/logto-1859/packages/schemas
@logto/schemas: > pnpm build "--incremental"
@logto/schemas: > @logto/schemas@1.0.0-beta.9 build /Users/jackmiller/logto-1859/packages/schemas
@logto/schemas: > pnpm generate && rm -rf lib/ && tsc -p tsconfig.build.json "--incremental"
@logto/schemas: > @logto/schemas@1.0.0-beta.9 generate /Users/jackmiller/logto-1859/packages/schemas
@logto/schemas: > rm -rf src/db-entries && ts-node src/gen/index.ts && eslint "src/db-entries/**" --fix
lerna success run Ran npm script 'prepack' in 5 packages in 37.7s:
lerna success - @logto/connector-core
lerna success - @logto/phrases-ui
lerna success - @logto/phrases
lerna success - @logto/schemas
lerna success - @logto/shared
lerna notice cli v5.0.0
lerna notice filter excluding "@logto/integration-test"
lerna info filter [ '!@logto/integration-test' ]
lerna info Executing command in 9 packages: "pnpm run dev"
@logto/demo-app: > @logto/demo-app@1.0.0-beta.9 dev /Users/jackmiller/logto-1859/packages/demo-app
@logto/demo-app: > cross-env PORT=5003 parcel src/index.html --public-url /demo-app --no-cache --hmr-port 6003
@logto/console: > @logto/console@1.0.0-beta.9 dev /Users/jackmiller/logto-1859/packages/console
@logto/console: > cross-env PORT=5002 parcel src/index.html --public-url /console --no-cache --hmr-port 6002
@logto/connector-core: > @logto/connector-core@1.0.0-beta.9 dev /Users/jackmiller/logto-1859/packages/connector-core
@logto/connector-core: > tsc --watch --preserveWatchOutput --incremental
@logto/schemas: > @logto/schemas@1.0.0-beta.9 dev /Users/jackmiller/logto-1859/packages/schemas
@logto/schemas: > tsc -p tsconfig.build.json --watch --preserveWatchOutput --incremental
@logto/shared: > @logto/shared@1.0.0-beta.9 dev /Users/jackmiller/logto-1859/packages/shared
@logto/shared: > tsc -p tsconfig.build.json --watch --preserveWatchOutput --incremental
@logto/phrases: > @logto/phrases@1.0.0-beta.9 dev /Users/jackmiller/logto-1859/packages/phrases
@logto/phrases: > tsc --watch --preserveWatchOutput --incremental
@logto/core: > @logto/core@1.0.0-beta.9 dev /Users/jackmiller/logto-1859/packages/core
@logto/core: > rm -rf build/ && pnpm run copyfiles && nodemon
@logto/ui: > @logto/ui@1.0.0-beta.9 dev /Users/jackmiller/logto-1859/packages/ui
@logto/ui: > cross-env PORT=5001 parcel src/index.html --no-cache --hmr-port 6001
@logto/phrases-ui: > @logto/phrases-ui@1.0.0-beta.9 dev /Users/jackmiller/logto-1859/packages/phrases-ui
@logto/phrases-ui: > tsc --watch --preserveWatchOutput --incremental
@logto/shared: 23:07:16 - Starting compilation in watch mode...
@logto/connector-core: 23:07:16 - Starting compilation in watch mode...
@logto/phrases: 23:07:16 - Starting compilation in watch mode...
@logto/schemas: 23:07:16 - Starting compilation in watch mode...
@logto/phrases-ui: 23:07:16 - Starting compilation in watch mode...
@logto/core: > @logto/core@1.0.0-beta.9 copyfiles /Users/jackmiller/logto-1859/packages/core
@logto/core: > copyfiles -u 1 src/**/*.md build
@logto/demo-app: Server running at http://localhost:5003
@logto/demo-app: Building...
@logto/ui: Server running at http://localhost:5001
@logto/console: Server running at http://localhost:5002
@logto/ui: Building...
@logto/console: Building...
@logto/core: [nodemon] 2.0.19
@logto/core: [nodemon] to restart at any time, enter `rs`
@logto/core: [nodemon] watching path(s): ../*/lib/**/* src/**/* node_modules/**/* .env
@logto/core: [nodemon] watching extensions: json,js,jsx,ts,tsx
@logto/core: [nodemon] starting `tsc -p tsconfig.build.json --incremental && node ./build/index.js`
@logto/phrases-ui: 23:07:30 - Found 0 errors. Watching for file changes.
@logto/phrases: 23:07:32 - Found 0 errors. Watching for file changes.
@logto/shared: 23:07:33 - Found 0 errors. Watching for file changes.
@logto/connector-core: 23:07:35 - Found 0 errors. Watching for file changes.
@logto/schemas: 23:07:35 - Found 0 errors. Watching for file changes.
@logto/demo-app: Bundling...
@logto/demo-app: Packaging & Optimizing...
@logto/demo-app: ✨ Built in 21.16s
@logto/ui: Bundling...
@logto/ui: Packaging & Optimizing...
@logto/ui: ✨ Built in 28.92s
@logto/core: ? No cookie keys array found in env `OIDC_COOKIE_KEYS`, would you like to genera
@logto/core: te a new one? (Y/n)                                                                                 [nodemon] app crashed - waiting for file changes before starting...

@logto/console: Bundling...
@logto/console: Packaging & Optimizing...
@logto/console: ✨ Built in 52.29s

**Comment by charIeszhao** [comment]
You need to have both `OIDC_COOKIE_KEYS` env and a `oidc-private-key.pem` before you are able to run the core service.

The easiest way is to auto-generate them by executing `pnpm dev` command in `<logto_root>/packages/core` directory. The command line tool will prompt if you want to generate them. Answering `Y` to both questions and you will be all set to go. Execute `pnpm dev` again in the logto root, and you will have all the packages building and running.

Finally, don't try to run logto on port 5001/5002, run it on 3001 instead. E.g. `http://localhost:3001`

**Comment by jackm9367** [comment]
All sorted thanks to @charIeszhao
