### ISSUE TITLE
bug: connectors  social  " Alipay Web"  config " charset : UTF8 "  can't save

### ISSUE THREAD

**Issue by dzp-java** [logto-io/logto#1915]
### Describe the bug

api url : `https://<host>/api/connectors/alipay-web`

Official tips:
```
{
  "appId": "<app-id>",
  "signType": "<signing-algorithm-either-RSA-or-RSA2>",
  "privateKey": "<private-key>",
  "charset": "<OPTIONAL-charset-either-GBK-or-UTF8>"
}
```

request payload:
```
{
  "appId": "<app-id>",
  "signType": "RSA2",
  "privateKey": "<private-key>",
  "charset": "UTF8"
}
```

response body:
```
{
    "message": "连接器配置错误",
    "code": "connector.invalid_config",
    "data": {
        "issues": [
            {
                "code": "invalid_enum_value",
                "options": [
                    "GBK",
                    "utf8"
                ],
                "path": [
                    "charset"
                ],
                "message": "Invalid enum value. Expected 'GBK' | 'utf8'"
            }
        ],
        "name": "ZodError"
    }
}
```

### Expected behavior

Official tips:  ` "charset": "<OPTIONAL-charset-either-GBK-or-UTF8>"`

Error response:  ` "message": "Invalid enum value. Expected 'GBK' | 'utf8'"`

Hope to be consistent with the official statement.  "utf8  -> UTF8 "

### Context

OS:  docker images latest  prerelease

Environment: 

Logto version:  v1.0.0-beta.9

**Comment by charIeszhao** [comment]
@darcyYe Would you like to take a look? Might just need to support both `UTF8` and `utf8` in the enum?

**Comment by darcyYe** [comment]
Aligned README.md and code, and use lower-cased `gbk` and `utf8` as character encoding.
https://github.com/logto-io/connectors/pull/12

**Comment by darcyYe** [comment]
[v1.0.0-beta.9 is released for @logto/connectors](https://github.com/logto-io/connectors/releases/tag/v1.0.0-beta.9), update the dependency of this package to fix this.
