### ISSUE TITLE
📍 Public roadmap 📌

### ISSUE THREAD

**Issue by gao-sun** [logto-io/logto#1937]
> **Note**
> This purpose of this issue is to discuss or show the future plans and iterations. If you are new to Logto, feel free to check out our [website](https://logto.io/) or [docs](https://docs.logto.io/) for more information about the status quo of Logto.

## Major releases

| Feature | Planned release date |
|--------|--------|
| MFA #1780 | 2023-11-13 |
| Organizations #3741 | 2023-11-20 |
| Enterprise SSO #3740 | 2023-11-27 |
| Token exchange #2880 | 24Q1 |
| Backchannel auth<br/>(e.g. WhatsApp, QR code) | 24Q1 |

## Issue labels

For categorization, you may find some issues have the following labels:

### Components

See [this link](https://github.com/logto-io/logto/labels?q=component%2F) for full component labels.

| Label | Description |
|--------|--------|
| [component/core](https://github.com/logto-io/logto/labels/component%2Fcore) | Issues regarding Logto core services. |
| [component/sie](https://github.com/logto-io/logto/labels/component%2Fsie) | Issues regarding Sign-in Experience. |
| [component/console](https://github.com/logto-io/logto/labels/component%2Fconsole) | Issues regarding web console. |
| [component/connector](https://github.com/logto-io/logto/labels/component%2Fconnector) | Issues regarding Logto connectors. |
| [component/integration](https://github.com/logto-io/logto/labels/component%2Fintegration) | Integrate Logto with other projects and products. |
| [component/misc](https://github.com/logto-io/logto/labels/component%2Fmisc) | Other issues. | 

### Status

See [this link](https://github.com/logto-io/logto/labels?q=status%2F) for full status labels.

| Label | Description |
|--------|--------|
| [status/wip](https://github.com/logto-io/logto/labels/status%2Fwip) | We are working on it. |
| [status/planned](https://github.com/logto-io/logto/labels/status%2Fplanned) | We decided to do it. If the issue also has a time label such as `2023-Q3`, it means we planned to deliver by the end of that time. Remember, it is not a promised time. |
| [status/on-our-radar](https://github.com/logto-io/logto/labels/status%2Fon-our-radar) | It's in our mind, we're likely to do it. Further discussion is needed. |
| [status/not-planned](https://github.com/logto-io/logto/labels/status%2Fnot-planned) | Currently we have no resource to do it. But contribution is welcome. | 

---

For any new feature requests, please create a new issue directly.

**Comment by imkarthikk** [comment]
@gao-sun The Notion roadmap is cool. But it doesn't allow the community to interact with the maintainers. Maybe a tool like Hellonext for logto's roadmap will work better?

URL: https://hellonext.co

**Comment by gao-sun** [comment]
> @gao-sun The Notion roadmap is cool. But it doesn't allow the community to interact with the maintainers. Maybe a tool like Hellonext for logto's roadmap will work better?
> 
> URL: https://hellonext.co

thanks for your suggestion. we'll evaluate it!

**Comment by gao-sun** [comment]
> Is there any timeline when organizations are set to be released in the OSS version?

it has been released in the latest version

**Comment by gao-sun** [comment]
we are iterating the public roadmap to use something more maintainable. close this issue for housekeeping.
