### ISSUE TITLE
feature request: Support for non-root path deployments

### ISSUE THREAD

**Issue by myesn** [logto-io/logto#1997]
### What problem did you meet?

Since I only have the HTTPS certificate for the top-level domain, when I use nginx for reverse proxy, I need nginx to match the URL starting with `/logto` before forwarding to the Logto application, and as of now, some style files and js files are directly requesting the `/` root path, which prevents them from loading successfully

```
location /logto {
    proxy_pass         http://logto_upstream;
}
```

![image](https://user-images.githubusercontent.com/18598579/192103786-35790372-1526-44e3-92ab-5120dde7af6d.png)

### Describe what you'd like Logto to have

Support for non-root path deployments

**Comment by gao-sun** [comment]
duplicate #1969?
