### ISSUE TITLE
How to grant admin permission to a user ？

### ISSUE THREAD

**Issue by huanlirui** [logto-io/logto#2107]
![image](https://user-images.githubusercontent.com/40491203/194984182-a515d696-1b60-446a-8b7d-f0959d391aed.png)

**Comment by huanlirui** [comment]
i want to use API Resource but i dont have permistion 
![image](https://user-images.githubusercontent.com/40491203/194984666-6b71608c-a472-435a-9432-8544baa6dcf0.png)

**Comment by huanlirui** [comment]
if i switch to admin user
![image](https://user-images.githubusercontent.com/40491203/194990458-bfcd591f-1858-4771-b0d1-54f9abd6817e.png)

i can get users list  ,But the administrator can only have one? ?

**Comment by huanlirui** [comment]
![image](https://user-images.githubusercontent.com/40491203/194991328-d10c638f-175d-44eb-970b-aad810e04a01.png)
I want to know that other users have two roles, and how to generate this role? Like magic, I didn't find any documents or instructions

**Comment by charIeszhao** [comment]
This seems to be more like a "Discussion" instead of an "Issue".

Please be noted that we DO have a template to fill in before you open up any issue in Logto. Thus I'm going to close this ticket and feel free to create a discussion thread instead.

Thanks
