### ISSUE TITLE
feature request: search user by IDs/usernames/phones/emails

### ISSUE THREAD

**Issue by gao-sun** [logto-io/logto#2167]
### What problem did you meet?

`/api/users?search=` only supports fuzzy search on multiple fields. Sometimes life needs to be more accurate, e.g., search a user by a specific ID, or a batch of usernames, etc.

### Describe what you'd like Logto to have

Support something like `/api/users?search=id:1,2,3&mode=exact` to return the exact search result on a specific field.

This issue includes:

- Search by multiple values with `or` logic
- The result should exactly match the input
- Support id, username, phone and email match
- Integration test cases to cover all new features

To discuss (we can figure them it together):

- The search pattern (`search=id:1,2,3` or `search=1|2|3&field=id` or something else? we are not sure yet)

**Comment by RutsuKun** [comment]
maybe better something like:

/api/users?**search[id]=1**&**search[id]=2**&**search[id]=3**&**search[username]=Test**

then if I'm not mistaken, will be able to automatically convert this to an array of ids usernames.

what do you think?

**Comment by gao-sun** [comment]
> maybe better something like:
> 
> /api/users?**search[id]=1**&**search[id]=2**&**search[id]=3**&**search[username]=Test**
> 
> then if I'm not mistaken, will be able to automatically convert this to an array of ids usernames.
> 
> what do you think?

looks great! i have no concern if it this works.

**Comment by 5war00p** [comment]
Even though the URL length doesn't matter, I still feel like keeping it like this is simpler and still readable,
/users?ids=[1,2,3]&usernames=[a,b,c]&mode=exact

this makes maintaining code easier by directly doing JSON.parser from the URL params and passing it to the API.

**Comment by 5war00p** [comment]
And also if it's not assigned to anyone I can take this up.

**Comment by gao-sun** [comment]
@5war00p here you go. let's confirm the tech design before you code. one of our engineers will follow this issue

**Comment by gao-sun** [comment]
@wangsijie will follow this issue.

**Comment by wangsijie** [comment]
As for "serch by ID", we can add a new route: `/api/users/:userId`

**Comment by 5war00p** [comment]
> /users?ids=[1,2,3]&usernames=[a,b,c]&mode=exact

@wangsijie will this be good to go?

**Comment by wangsijie** [comment]
@5war00p sorry for the late reply.

I prefer @RutsuKun's idea which can take advantage of the common HTML standard. But some changes are needed, I tried:

`/api/users?id=1&id=2&id=3&username=foo`

and the `ctx.query` would be this without any additional parser:

```json
{
  "id": ["1", "2"],
  "username": "foo"
}
```

What do you think about this? I was worried that the JSON way may not be popular and is a bit heavy because we only need an array.

**Comment by 5war00p** [comment]
Yes, this also makes sense, by using `.getAll` with the same key will give an array. No need to do any additional effort like JSON.parse and wrapping it under a try-catch block.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/57614947/200165740-7ad46336-36a7-430d-8cd1-4bd01068bd9e.png">

But the only thing is URL will have more redundancy, while sharing URL it looks more lengthy. (but this is not a problem as per functionality).

**Comment by wangsijie** [comment]
The "redundancy" is OK? Only when the array have a large length. And even for that case, it will still work.

**Comment by 5war00p** [comment]
Cool, then we can make in that way. How the UX will be for this? means how users will give mutliple ids or usernames, will it be space separated?

**Comment by wangsijie** [comment]
Let's start with the API part.

As for the UI, @fleuraly will take a look and post updates here.

**Comment by ihsanguldur** [comment]
hello, is this issue in development phase? @wangsijie

**Comment by wangsijie** [comment]
@5war00p is working on this, could you post some updates?

**Comment by saiswaroopmaddi** [comment]
Yeah, I've started it. 

But I got stuck with DB issues after updating my pnpm version.

I have to fix that and move forward.

**Comment by 5war00p** [comment]
Yeah, I've started it.

But I got stuck with DB issues after updating my pnpm version.

I have to fix that and move forward.

**Comment by kentio** [comment]
how is the progress?

**Comment by wangsijie** [comment]
@5war00p any updates?

**Comment by gao-sun** [comment]
i think @5war00p was busy for this issue, no worries!
according to our bounty rules and the popular demand on this feature, we'll take back the claim and our team will be responsible for implementation. we'll release the feature with the next version.

**Comment by gao-sun** [comment]
we'll publish this feature with our December release. feel free to open a new issue if it doesn't work. cheers
