### ISSUE TITLE
bug: set USER_DEFAULT_ROLE_NAMES will make admin console unusable

### ISSUE THREAD

**Issue by codehz** [logto-io/logto#2179]
### Describe the bug

I'm trying follow this [tutorial](https://silverhand.notion.site/Logto-x-Hasura-How-to-use-open-source-auth-GraphQL-solution-to-boost-your-project-0badddb711624a9fb814a5ca83f8b701) to connect logto with hasura, but after adding the environment variable 'USER_DEFAULT_ROLE_NAMES=user', I cannot use admin console anymore (even after drop database and start over again).

### Expected behavior

able to use admin console

### How to reproduce?

add env 'USER_DEFAULT_ROLE_NAMES=user' and restart logto instance

### Context

OS: linux

Environment: docker

Logto version: logto:prerelease 

Node version: (docker)

Postgres version: 14

Command of starting Logto: 

```
docker run --rm --name logto --net host -e ALL_YES=1 -e NO_INQUIRY=0 -e TRUST_PROXY_HEADER=1 -e ENDPOINT=https://demo.logto.test -e DB_URL_DEFAULT=postgres://postgres@127.0.0.1:5432 -e USER_DEFAULT_ROLE_NAMES='user' ghcr.io/logto-io/logto:prerelease
```

### Logs

```
  <-- GET /api/.well-known/sign-in-exp
  --> GET /api/.well-known/sign-in-exp 200 48ms 550b
  <-- POST /api/session/register/username-password
  --> POST /api/session/register/username-password 200 5,138ms 72b
  <-- GET /oidc/auth/-pETAlKEMGd-mQAKDpCfH
  --> GET /oidc/auth/-pETAlKEMGd-mQAKDpCfH 303 105ms 63b
  <-- GET /sign-in/consent
  --> GET /sign-in/consent 200 40ms 522b
  <-- GET /api/.well-known/sign-in-exp
  --> GET /api/.well-known/sign-in-exp 200 42ms 548b
  <-- POST /api/session/consent
  --> POST /api/session/consent 200 160ms 72b
  <-- GET /oidc/auth/_KeBiaujuix-VNBS54bRV
  --> GET /oidc/auth/_KeBiaujuix-VNBS54bRV 303 122ms 493b
  <-- GET /console/callback?code=gAMysobFnPBKCxd0fcDZ4_pttVhupwvRbXBJwgiDIZn&state=bhe8RNo_MJ8Pdg7zgy3YHBzRMmLB5v7QtbEv2XpJDMdU4RyJwtA6JwOD8jChknLM4Npur0K2r1YAcWgO0uaMFQ&iss=https%3A%2F%2Fdemo.logto.test%2Foidc
  --> GET /console/callback?code=gAMysobFnPBKCxd0fcDZ4_pttVhupwvRbXBJwgiDIZn&state=bhe8RNo_MJ8Pdg7zgy3YHBzRMmLB5v7QtbEv2XpJDMdU4RyJwtA6JwOD8jChknLM4Npur0K2r1YAcWgO0uaMFQ&iss=https%3A%2F%2Fdemo.logto.test%2Foidc 200 25ms 530b
  <-- GET /oidc/.well-known/openid-configuration
  --> GET /oidc/.well-known/openid-configuration 200 21ms 1.78kb
  <-- POST /oidc/token
  --> POST /oidc/token 200 209ms 1.3kb
  <-- GET /oidc/jwks
  --> GET /oidc/jwks 200 14ms 789b
  <-- GET /api/settings
  xxx GET /api/settings 401 11ms -
  <-- GET /api/users/1kNSR7dK5QDz/custom-data
  xxx GET /api/users/1kNSR7dK5QDz/custom-data 401 10ms -
  <-- GET /api/settings
  xxx GET /api/settings 401 21ms -
  <-- GET /api/applications/demo-app
  xxx GET /api/applications/demo-app 401 13ms -
  <-- GET /console/avatar-010.e760a9d3.png
  <-- GET /api/users/1kNSR7dK5QDz/custom-data
  xxx GET /api/users/1kNSR7dK5QDz/custom-data 401 10ms -
```

### Screenshots

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/13158903/196322644-8f1468ee-e29a-4f0c-b91f-a924aad256e7.png">

**Comment by gao-sun** [comment]
Thanks for reporting. Will take a look soon.

**Comment by gao-sun** [comment]
i cannot reproduce locally. either an existing Logto instance or a new one.

the `USER_DEFAULT_ROLE_NAMES` only affect adding new users, so:

1. did you use a non-admin account to sign in to the console? you can check the `users` table -> `role_names` column
2. if you are using the admin account, would you like to provide a step-by-step list to reproduce?

**Comment by codehz** [comment]
> i cannot reproduce locally. either an existing Logto instance or a new one.
> 
> the `USER_DEFAULT_ROLE_NAMES` only affect adding new users, so:
> 
> 1. did you use a non-admin account to sign in to the console? you can check the `users` table -> `role_names` column
> 2. if you are using the admin account, would you like to provide a step-by-step list to reproduce?

I have only created a user (since no application have been created yet), that must be admin, right?

btw, after clear browser data and everything workin, so I cannot repro either

the step:
1. start a empty instance with empty database (no default role env)
2. register the first user
3. set application key for hasura
4. change the env and restart server
5. refresh browser, and got 401 in every page
6. click log out, got another error (forgot to copy that)
7. try re login, but still 401 (as screenshot)
8. ... finally I tried to clear both browser data and database (so I don't know which step "fix" this problem)
9. repeat above step
10. it just work, **but I don't know why**

**Comment by gao-sun** [comment]
that's really strange. I think i might be some cache issue, we met it today too (most likely related to the signing key). feel free to let us know if it happens again.
