### ISSUE TITLE
feature request: support options in `@logto/create`

### ISSUE THREAD

**Issue by gao-sun** [logto-io/logto#2206]
### What problem did you meet?

Now `npm init @logto` doesn't support options like `-p`, only `npx @logto/cli` supports.

### Describe what you'd like Logto to have

- Support options in `@logto/create`, thus we can use commands like:

`npm init @logto -- -p ./logto --db-url postgresql://your-postgres-dsn:5432/logto --oc`

- Update English docs accordingly

**Comment by KaviiSuri** [comment]
Hey, I'd like to pick this issue up, is it still available?

**Comment by gao-sun** [comment]
yes
