### ISSUE TITLE
feature request: Support wildcards in redirect URIs

### ISSUE THREAD

**Issue by Monikaa1909** [logto-io/logto#2270]
### What problem did you meet?
I am developing my application using gitpod.io and the application's url changes with every new workspace. Hence I do not know the exact redirect URI. I do not want to change it every time.

I've already tried using wildcards like `https://*.gitpod.io`, though I always got `redirect_uri did not match any of the client's registered redirect_uris` error message

### Describe what you'd like Logto to have
It would be great if logto supported wildcards in redirect URIs. Like: `https://*.gitpod.io`

**Comment by simeng-li** [comment]
Hi, Monika thanks for using Logto. 

First of all, redirect URIs are used not only just for post-sign-in or post-sign-out redirection purposes but also play an important security role in OAuth2.0 to prevent phishing attacks.  Wildcard redirect URIs are a violation of the [OAuth2 spec.](https://www.rfc-editor.org/rfc/rfc6749#section-3.1.2) . 

`The redirection endpoint URI MUST be an absolute URI`

Back to your cases, there are a couple of things that cross my mind:
1. Our admin console does allow you to provide multiple redirect URIs for your application.  Whenever your workspace address changes you just need to add a new one or replace the old one using the Admin Console.
2. As for the SDK, maybe you could set a global env variable that will pick up the workspace host address URL dynamically. Then pass it to the Logto SDK configs.

**Comment by wvffle** [comment]
@simeng-li: Thanks for the awesome work on Logto!

Chaninging the URIs manually with every new PR will result in a lot of maintenance. In our team, we want the developers to focus on their work rather than configuring services we use.

If wildcards are a violation of 0Auth2 spec, maybe the CLI could have a command to manage the URIs? That way only admins who have the access to the machine could update the URIs. When it comes to gitpod development deployment, we could integrate the command into the `.gitpod.yml`'s task and automatically add/replace the URIs.

**Comment by simeng-li** [comment]
Hey, @wvffle  Had some discussions with the team.  One quick solution, following your insights.

1. Create a [M2M](https://docs.logto.io/docs/recipes/integrate-logto/machine-to-machine) app for authorization use through admin console. You will get a consistent M2M client credential.  (be careful with that)

2. Write a gitpod deployment job. 
 - Use that M2M client credential to retrieve an access token. 
 - Call Logto's [management API](https://docs.logto.io/docs/recipes/interact-with-management-api/)  to [post a new application](https://docs.logto.io/api#tag/Applications/paths/~1api~1applications/post) instance using the current pod id and the address as it's redirect URI.
 
 Each new development would have a new related app instance created in your Logto. 
  
 How does that sound?

**Comment by anbraten** [comment]
Couldn't you "simply" add a logto deployment to each gitpod workspace. This is how we do it.
