### ISSUE TITLE
feature request: open standard connectors

### ISSUE THREAD

**Issue by MyWay** [logto-io/logto#2330]
### What problem did you meet?
Say I have an existing 3rd party auth system, I may want to connect it. 

### Describe what you'd like Logto to have
If you could allow the setup of a generic OAuth 2, everybody could easily connect/integrate its own auth system. 

### What we'll implement
TBD

**Comment by gao-sun** [comment]
it's on the way!

**Comment by gao-sun** [comment]
@MyWay we just released a new version which supports multiple OAuth 2 and OIDC connectors. would you like to give it a try?
