### ISSUE TITLE
feature request: webhooks events

### ISSUE THREAD

**Issue by MyWay** [logto-io/logto#2339]
### What problem did you meet?
Let's say we want to connect multiple systems, e.g. Log an event when a new user is added, or execute a remote job when an email was sent. 

Edit: that could also handle cases such as #1795 

### Describe what you'd like Logto to have
I would like to have a list of multiple events available in logto which I can use to create a new webhook action to post payload to a remote server with basic auth/signing methods optionally available.

**Comment by gao-sun** [comment]
yes! it's already on our roadmap and we'll start to implement this quarter

**Comment by gao-sun** [comment]
should this be considered as done? (we still need to add connector event hooks though. you can demonstrate more events if needed)

**Comment by gao-sun** [comment]
we've implemented web hooks and you can see the docs [here](https://docs.logto.io/docs/recipes/web-hooks/). feel free to create a new issue if you need more events
