### ISSUE TITLE
bug: User email missing in response from oidc/me

### ISSUE THREAD

**Issue by vavido** [logto-io/logto#2545]
### Describe the bug
The React SDK for Logto provides a function `fetchUserInfo()` that returns `Promise<UserInfoResponse | undefined>`.
Among some other things, `UserInfoResponse` contains an optional field `email`.
However, even for a user that has a primary email set & showing up in the admin console, the field is not set in the API response:

### Expected behavior
When the email is set in Logto, I would expect it to show up in the `fetchUserInfo` response

### How to reproduce?
1. Set up a react app as per the docs
2. Create a new user via the SMTP connector
3. Verify that the mail shows up in the admin console
4. Log in with the newly created user
5. Call the `fetchUserInfo` function in your react app

### Context

OS: Docker Compose
Environment: 

Logto version: 1.0.0-beta.14

Node version: 

Postgres version: 

Command of starting Logto: 

### Screenshots
<img width="612" alt="grafik" src="https://user-images.githubusercontent.com/7227663/204239107-7de4e9bb-d830-4096-b25a-54b9cc0f779a.png">

<img width="166" alt="grafik" src="https://user-images.githubusercontent.com/7227663/204239190-94e45255-dbf8-407a-a00a-c9409af28c99.png">

**Comment by gao-sun** [comment]
thanks for reporting, will take a look soon

**Comment by vavido** [comment]
That solved the problem, thank you!
