### ISSUE TITLE
feature request: support aws ses

### ISSUE THREAD

**Issue by kentio** [logto-io/logto#2633]
### What problem did you meet?

Amazon Web Services (AWS) is the world's most comprehensive and broadly adopted cloud platform

### Describe what you'd like Logto to have

Support ses(aws) send email

**Comment by darcyYe** [comment]
Hi @kentio, thanks for contributing the AWS ses connector, we will review the PR these days and give you feedback!

**Comment by kentio** [comment]
https://github.com/logto-io/connectors/pull/42
