### ISSUE TITLE
bug: Android Native App doesn't launch redirect uri

### ISSUE THREAD

**Issue by miguelpark** [logto-io/logto#2646]
### Describe the bug

Im trying to apply logto into android client app and I found
after signing in done, it doesn't call redirect uri.

I create custom uri. and registered to logto server and also put it on one of client activity manifest.

### Expected behavior

should launch activity matched redirect uri

### How to reproduce?

test with android client 
sign up with new account

### Context

OS: 

Environment: 

Logto version: 

Node version:

Postgres version: 

Command of starting Logto:

**Comment by gao-sun** [comment]
feel free to let us re-open when the content body follows the template and the context is more clear
