### ISSUE TITLE
bug: Android Native App doesn't launch redirect uri

### ISSUE THREAD

**Issue by miguelpark** [logto-io/logto#2647]
### Describe the bug

Im trying to apply logto into android client app and I found
after signing in done, it doesn't call redirect uri.

I create custom uri. and registered to logto server and also put it on one of client activity manifest.

maybe i made a mistake?

### Expected behavior

should launch activity matched redirect uri

### How to reproduce?

test with android client 
sign up with new account

### Context

OS: Ubuntu 22.04, Android 12

Environment:  Docker Compse

Logto version: 1.0.0-beta.16

Node version:16.18.1

Postgres version: 14-alpine

Command of starting Logto: docker compose up

**Comment by gao-sun** [comment]
it'll be great if you can share both Admin Console app configs and Android code snippets

**Comment by gao-sun** [comment]
@xiaoyijun would like to take a look?

**Comment by miguelpark** [comment]
Thx @xiaoyijun .

it means I don't need to handle sign-in result?
so I wonder if I want to get more info from user such as name, birthday etc, just launch another page on  EmptyCompletion.onComplete callback in logtoClient.signIn?
(and send extra info to server?)

**Comment by xiaoyijun** [comment]
My pleasure.
It seems that you keep the `logtoClient` instance on an activity, which is not recommended, for the instance will be released when the activity is refreshed.

You can refer to our [Java sample](https://github.com/logto-io/kotlin/tree/master/android-sample-java) or [Kotlin sample](https://github.com/logto-io/kotlin/tree/master/android-sample-kotlin) for some inspiration.

As for getting user information, refer to the [Fetch UserInfo](https://github.com/logto-io/kotlin/tree/master/android-sample-kotlin) doc or use [`logtoClient.getIdTokenCliams`](https://github.com/logto-io/kotlin/blob/8883591c3343bf4c161c0cb1e5dba6dc06b081ea/android-sample-java/app/src/main/java/io/logto/demo4j/viewmodel/LogtoViewModel.java#L86-L94) API ( retrieve some basic data from the id token).

@miguelpark

**Comment by miguelpark** [comment]
okay, I got how to get userinfo response and token.
one thing I still wonder is sign-up(create new account) case.

Currently, by admin console, username, email or phone number  can be set as identifier for user account
but I cant find any other way to get more user information fields(e.g. birthday , address) after sign up done.

is there any guide or sample for it?
(normally I think other web site or native app sign-up procedure is get create and verify id/password then show form for getting extra information)

Thanks in advance. @xiaoyijun

**Comment by xiaoyijun** [comment]
Currently, we do not support extra user information, but a new feature for setting up user profiles is WIP, and we are still researching. cc @fleuraly @charIeszhao 

You can use the [management API](https://docs.logto.io/docs/recipes/manage-users/management-api) to add some [custom data](https://docs.logto.io/docs/references/users/custom-data) for users, please refer to the [`GET /api/users/:userId/custom-data`](https://docs.logto.io/api/#tag/Users/paths/~1api~1users~1:userId~1custom-data/get) and [`PATCH /api/users/:userId/custom-data`
](https://docs.logto.io/api/#tag/Users/paths/~1api~1users~1:userId~1custom-data/patch)
