### ISSUE TITLE
feature request: Create non existing user during passwordless login

### ISSUE THREAD

**Issue by jirisykora83** [logto-io/logto#2650]
When use (only) passwordless or social login option and user does not exist, it throws error. It would be nice if there was an option to "create" account in logto automatically at the moment when email code, social login is validated.

**Comment by fleuraly** [comment]
Thanks for pointing that out! 
For email passwordless sign-in, just to clarify, are you referring to the flow that you try to sign in through a non-existing account via verification code, it just throws you a dialog that says the account does not exist?

For social sign-in, would you mind sharing the screenshot you have? If I understand correctly, we support the path to creating an account when the account has not been registered, but it needs optimization to shorten the path and flows.

**Comment by jirisykora83** [comment]
To be honest i assume that social login has the same behavior as email passwordless sign-in so i try it now and it works.

But as you wrote, it detects that the user does not exist and asks to create an account. It would be nice if this could happen without user interaction. This most likely doesn't work for all scenarios but for example in case you need just user email, this should be possible request during login (from social login provider)?

**Comment by fleuraly** [comment]
That's a great suggestion, and actually where we are optimizing right now! For example, if the social provider passes through a verified email, it should automatically create that account for you. Our team agrees on this.

But one thing to clarify, from your perspective, for the case you just mentioned, what does creating that account without interaction mean? Does it mean it will direct users to the app automatically without any confirmation or way to change and edit the email address? We could do different level of "automation", just curious to hear your thoughts.

**Comment by jirisykora83** [comment]
Yes, basically use email verified by social login provider without confirmation by user. That makes the whole process simpler for majory of users. And rest have to logout and login via email. As i for example I would not expect to be able login with my personal google account into the account created (not created yet) via work email, for example for managing same order/booking. And i am not sure if i would want to provide that option as an app owner. But i am not an expert in this area.

**Comment by gao-sun** [comment]
i think the current version will automatically use verified email from social identity providers. @jirisykora83 can we consider this issue as resolved? feel free to let us know if there's anything i missed
