### ISSUE TITLE
bug / feature request: session.not_found

### ISSUE THREAD

**Issue by jirisykora83** [logto-io/logto#2651]
### Describe the bug (?)
Calling `http://localhost:3001/api/session/sign-in/passwordless/email` directly (from postman) returns

```
{
    "message": "Session not found. Please go back and sign in again.",
    "code": "session.not_found",
    "data": {
        "error_description": "interaction session id cookie not found"
    }
}
```

### Expected behavior
If this is intended behavior, is there any options to build custom sign-in form without using any cookies (or how is "session" pass to logto)?

**Comment by wangsijie** [comment]
Our session APIs (start with `/api/session`) rely on cookies. The cookies can only be initialized by calling `authorization_endpoint`, this is usually done by our SDKs or other OIDC helper.

Unfortunately, you can not build custom sign-in form without using cookies. Is there any reason that you are not able to use cookies? Can you share some stories and what you are planning to do?

**Comment by jirisykora83** [comment]
Ok i did not notice the redirection during opening demo-app. Cookies are fine.
