### ISSUE TITLE
bug: Docker Build Error 

### ISSUE THREAD

**Issue by kelvin6365** [logto-io/logto#2747]
### Describe the bug
When i try to build the app by docker, the pnpm -r build comes up error

### Expected behavior
use npx to init the project, and build the docker image

### How to reproduce?
`npx @logto/cli db seed --db-url postgresql://your-database-url `
`docker build -t test-image .`

### Context

OS: 

Environment: Window 10

Logto version: latest

Node version: 16

Postgres version: 14

Command of starting Logto: npm start

### Screenshots

![image](https://user-images.githubusercontent.com/26310008/209713176-106aee80-6c53-4f75-be98-0435b680e553.png)

**Comment by gao-sun** [comment]
for manual docker build, you need to clone the repo instead of using `npm init @logto`
