### ISSUE TITLE
feature request: support google authenticator

### ISSUE THREAD

**Issue by 99Kies** [logto-io/logto#2806]
I want to add google verifier to the login system. (After login, you need to enter the authentication code of google authenticator to login successfully).

**Comment by 99Kies** [comment]
https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en_US&gl=US

**Comment by gao-sun** [comment]
Yes, we're going to implement MFA which support Google Authenticator

**Comment by 99Kies** [comment]
> Yes, we're going to implement MFA which support Google Authenticator

Has this part started development yet, and is there a `pr` that is being built?

**Comment by gao-sun** [comment]
this is a complex feature since it will affect the current Sign-in experience and we need to build the Admin console support as well.

we already have some internal product research and design, but didn't start the development yet. currently we are targeting to deliver MFA by the end of 23Q1.

**Comment by gao-sun** [comment]
duplicate #1780
