### ISSUE TITLE
bug: android 28 can't open logto login

### ISSUE THREAD

**Issue by future-lj** [logto-io/logto#2862]
OPPO R17  android 9
[INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token f", source: https:/login.molbreeding,com/index.afe64989s(1)

PIXEL 5 API28
[INFO:CONSOLE(1)] "Uncaught TypeError: Object.fromEntries is not a function", source: https://login.molbreeding.com/index.afe64989.js (1)

log has only these two relevant information

![微信图片_20230108172204](https://user-images.githubusercontent.com/10300114/211188825-0c056311-8035-4a6e-9dd1-43c76b4bca3c.png)

**Comment by future-lj** [comment]
Huawei, Xiaomi's api 28 can log in normally。
红米 7/Redmi 7(Android 9) 
P10/VTR-AL00(Android 9)

**Comment by gao-sun** [comment]
1. please double check the [browser support](https://caniuse.com/?search=Object.fromEntries) for `Object.fromEntries` in these devices
2. for housekeeping purpose, we'll close issues don't follow the template or provide limited context. feel free to contact us to re-open once the content has been updated.

**Comment by future-lj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
