### ISSUE TITLE
feature request: SvelteKit SDK

### ISSUE THREAD

**Issue by alteregogi** [logto-io/logto#3008]
### What problem did you meet?

I was trying to integrate open source Auth to my web app and found logto trying it and have great UI, but no SDK for SvelteKit

### Describe what you'd like Logto to have

add support to SvelteKit

**Comment by j2l** [comment]
yes please! :smile:

**Comment by gao-sun** [comment]
someone has a sample project: https://github.com/vocamen/svelte-logto

let me know if it helps

**Comment by j2l** [comment]
Perfect :smile:

**Comment by jay-dee7** [comment]
@gao-sun @j2l I have a super early version of sveltekit sdk here:
1. Repo -> https://github.com/cheqd/logto-js-sdks
2. NPM Package - https://www.npmjs.com/package/@cntr/sveltekit

The only downside right now is that our version of the sdk assumes all logto logic to be handled at server side plus you manually need to handle the SvelteKit redirect throws but it seems to be working pretty much good for us. When I get some time, I'll rewrite it again from scratch but I'm running short of bandwidth right now.

**Comment by oronoa** [comment]
Can you share a full example please ?

**Comment by jay-dee7** [comment]
@oronoa `isSvelteKitRedirect` is a type guard and this is what it is:

```typescript
export const isSvelteKitRedirect = (val: any): val is Redirect => {
	return val && val.status !== undefined && val.location !== undefined;
};
```

I'll put the whole thing in an example project and share it here

**Comment by jay-dee7** [comment]
@oronoa here's a repository the combines the above comments into a bare-minimum SvelteKit project - https://github.com/jay-dee7/logto-sveltekit-example

**Comment by oronoa** [comment]
Hi, Thanks for the example, was able to integrate logto to my app using your code, but I'm still confused as to how I'm syncing the logto users to what they do on my app. For example the user now sets some custom property on one of my DB tables like 'color_pref', how do I tell my backend which user this is, I'm used to JWT all around but here I can't see how I get the JWT token for that user.

**Comment by jay-dee7** [comment]
@gao-sun Looks like this one is completed now? I just realized that we finally have an official implementation for SvelteKit, super excited about this 🥳 🥳
