### ISSUE TITLE
bug: passcode request timeout with custom connector

### ISSUE THREAD

**Issue by evist0** [logto-io/logto#3009]
Hello everyone, I've tried to implement custom SMS connector in [this repo](https://github.com/evist0/logto-connector-repro).

This connector sends SMS, but I can't confirm code after that because `passcode` request fails on timeout.

![image](https://user-images.githubusercontent.com/32814970/214832282-952f5391-4033-4dcd-a883-bfae1342879b.png)

Initially, I thought about the "SMSAero" service lag, but according to Postman it's not because of that.

![image](https://user-images.githubusercontent.com/32814970/214832879-a104a741-14f0-4f20-9b06-b3fb3def9989.png)

**Comment by gao-sun** [comment]
the link is not available - would you like to update? thanks

**Comment by evist0** [comment]
yeap, sorry, forgot to change repo visibility. now it's should be ok.

**Comment by darcyYe** [comment]
Hi @evist0 , thanks for posting the problem, and I apologize for the late response. Would you like to manually set the timeout time for the HTTP request you've made in your SMS connector's implementation like we showed in the following screenshot?
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/15182327/215933244-abe2a25f-72d6-4d88-8a1c-a6656112e934.png">
And it would be better if you could also attach the response or the detailed error message you got :D

**Comment by evist0** [comment]
indeed, got doesn't returns response and fails on a timeout, thanks

**Comment by evist0** [comment]
replaced `got` with `node-fetch` and it work as expected, thanks again
