### ISSUE TITLE
bug: @logto/vue install fails on node LTS 

### ISSUE THREAD

**Issue by PhE** [logto-io/logto#3055]
### Describe the bug

`@logto/vue` is not installable on node LTS.

`yarn add @logto/vue` fails with node LTS (also fails with node 16).

### Expected behavior

`yarn add @logto/vue` should succeed on node LTS (18).

### How to reproduce?

```shell
# nvm install --lts
# nvm use --lts
# node --version
v18.14.0
# yarn add @logto/vue
[...]
error @logto/core-kit@1.0.0-beta.20: The engine "node" is incompatible with this module. Expected version "^16.0.0". Got "18.14.0"
error Found incompatible module.
# nvm use 16
Now using node v16.19.0 (npm v8.19.3)
# yarn add @logto/vue
[...]
error @semantic-release/gitlab@10.1.4: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.19.0"
error Found incompatible module.
```

### Context

OS:  Ubuntu 22.04 LST

Environment: node installed with nvm

Logto version: Expecting 1.0.0-rc.1 but log shows @logto/core-kit@1.0.0-beta.20 and @logto/language-kit@1.0.0-rc.0 !!

Node version: 18.14.0 (LTS) and 16.19.0

Postgres version: N/A

Command of starting Logto: N/A

**Comment by gao-sun** [comment]
Thanks for reporting. We’ll update the engines filed soon.

**Comment by gao-sun** [comment]
would you like to try `@logto/vue@1.0.0-rc.0`? just removed problematic dependencies

**Comment by PhE** [comment]
it works for node LTS. thanks !!
