### ISSUE TITLE
Parcel's polyfill issue

### ISSUE THREAD

**Issue by tuoxiansp** [logto-io/logto#3059]
### Describe the issue

Our project are facing some compatibility problem with Logto. It was caused by parcel's polyfill issue

see: [Parcel does not include polyfill for older browsers even when browserslist is declared in the package.json](https://github.com/parcel-bundler/parcel/issues/7419)
> Parcel doesn't include any polyfill at all, even though browserslist is declared in the package.json.

An effective workaround just for us was patching logto and import `core-js` from the entry point;

----
edit:
### Describe the bug
Got white screen on some Android device when user login.
We have 200+ users for now. There were at least 10 users got the white screen problem.
It was caused by the unsupported `Object.fromEntries` when I reproduced this on Chrome 66.

### Expected behavior
User can open login page.

### How to reproduce?

Login on Chrome 66.

### Context

OS: 

Environment: 
Docker

Logto version: 
v1.0.0-beta.19

Node version:
v16

Postgres version: 
v15

Command of starting Logto: 
npm start

### Screenshots

I'm sorry cannot provide screenshot here because it was fixed already with some workaround.

**Comment by gao-sun** [comment]
can you follow the template to provide more context?

**Comment by tuoxiansp** [comment]
> can you follow the template to provide more context?
done.

**Comment by gao-sun** [comment]
@tuoxiansp thanks! Chrome 66 is old enough as it was published on [April, 2018](https://developer.chrome.com/blog/new-in-chrome-66/). but this reminds us to test browser compatibility and mark it on the docs

**Comment by gao-sun** [comment]
opened #3079 for convenience. close the issue since there's nothing Logto can do to fix
