### ISSUE TITLE
bug: error while admin account create

### ISSUE THREAD

**Issue by miguelpark** [logto-io/logto#3094]
### Describe the bug

after install logto with npm
error comes while creating admin account
and cant sign in with entered with admin account/password as well

### Expected behavior

No error 

### How to reproduce?

install logto
connect address and create admin account

### Context

OS: 

Environment: local rasberry pi

Logto version: v1.0.0-rc.1

Node version: v18.14.0

Postgres version: psql (PostgreSQL) 15.1 (Debian 15.1-1.pgdg110+1)

Command of starting Logto:  npm start

### Screenshots

console log attached

```
  --> GET / 302 48ms 107b
  <-- GET /welcome
  --> GET /welcome 302 499ms 123b
  <-- GET /console/welcome
  --> GET /console/welcome 200 43ms 593b
oidc-provider WARNING: x-forwarded-proto header detected but not trusted, you must set proxy=true on the provider. See the documentation for more details.
  <-- GET /oidc/.well-known/openid-configuration
  --> GET /oidc/.well-known/openid-configuration 200 11ms 1.53kb
  <-- GET /sign-in
  --> GET /sign-in 200 30ms 579b
  <-- GET /api/.well-known/sign-in-exp
  --> GET /api/.well-known/sign-in-exp 200 441ms 695b
  <-- GET /api/phrase
  --> GET /api/phrase 200 47ms 5.45kb
  <-- PUT /api/interaction
  --> PUT /api/interaction 204 569ms 
  <-- POST /api/interaction/submit
  --> POST /api/interaction/submit 422 108ms 137b
  <-- PATCH /api/interaction/profile
  --> PATCH /api/interaction/profile 204 505ms 
  <-- POST /api/interaction/submit
trySafe() caught error RequestError: The applications with ID `admin-console` does not exist.
    at file:///home/mingoon0da/logto/packages/core/build/database/find-entity-by-id.js:21:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/mingoon0da/logto/packages/core/build/libraries/hook.js:33:83
    at async Promise.all (index 1)
    at async triggerInteractionHooksIfNeeded (file:///home/mingoon0da/logto/packages/core/build/libraries/hook.js:31:37) {
  expose: true,
  code: 'entity.not_exists_with_id',
  status: 404,
  data: undefined

```

**Comment by gao-sun** [comment]
@simeng-li would you like to take a look? thanks

**Comment by simeng-li** [comment]
Hi, @miguelpark  sorry for the late response. Can't reproduce it on my local server with a brand-new DB. Are you using a clean db or migration from an existing Logto DB?

**Comment by simeng-li** [comment]
Latest update. I am able to observe the same error you paste above. The reason is our admin-console app is no longer stored in DB, so the query method throws an entity not found error. This will be addressed soon in our next release.

However, as you can see, the whole block is wrapped up in a `trySafe()`, which means it won't block the main user sign-in flow.  That is sth I am not able to reproduce.  Can you provide some more context?  This error should not lead to a sign-in/register failure.
