### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by tushar1998** [logto-io/logto#3110]
### Expected behavior

Should start a server on port 3001 with logto ui

### How to reproduce?

`curl -fsSL https://raw.githubusercontent.com/logto-io/logto/HEAD/docker-compose.yml | TAG=prerelease docker compose -p logto -f - up`

### Context

OS: 

Environment: Docker Compose

Logto version: Pre-release

Node version: v18.14.0

Postgres version: as in docker compose

Command of starting Logto: in reproduce step

### Screenshots

<img width="964" alt="image" src="https://user-images.githubusercontent.com/22202489/218805853-4c120a13-41cb-4a07-888a-0c1e78929ca3.png">

**Comment by gao-sun** [comment]
duplicate #1837
