### ISSUE TITLE
feature request: Allow upload of custom background

### ISSUE THREAD

**Issue by florian-glombik** [logto-io/logto#3164]
### What problem did you meet?

It is currently _([v1.0.0-rc.1](https://github.com/logto-io/logto/releases/tag/v1.0.0-rc.1))_ not possible to upload a custom background image for the login page.

### Describe what you'd like Logto to have

Add the option `Background image URL` within the `Sign-in experience` within the `Branding Area`.
Similar to the `App logo image URL`, the `Background image URL` can be added to use a custom background.

If a valid background image URL is supplied, the custom background image is used.

The solution could look like this 

<kbd>![image](https://user-images.githubusercontent.com/63976129/220144784-8abb5345-f8bc-4f09-8c83-172f1a69dce7.png)</kbd>

**Comment by gao-sun** [comment]
for sure, we're planning to support more customization options in the near future.

before we deliver the implementation in Admin Console, i think you can leverage the "Custom CSS" feature in the next version (`v1.0.0-rc.1`, we will release this week) to achieve the same result. i'll paste the link here once it's ready.

**Comment by gao-sun** [comment]
[v1.0.0-rc.2](https://github.com/logto-io/logto/releases/tag/v1.0.0-rc.2) has been released. feel free to give it a try!

**Comment by gao-sun** [comment]
i think this is resolved by the Custom CSS feature (rather than upload, you can fill out arbitrary url for that). feel free to let us know if it doesn't meet your requirement

**Comment by florian-glombik** [comment]
The Custom CSS feature is great and meets the requirement, thank you for your quick responses and active maintenance of this repository!
