### ISSUE TITLE
Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a stringbug: 

### ISSUE THREAD

**Issue by liushunshun** [logto-io/logto#3180]
![image](https://user-images.githubusercontent.com/8638224/220520726-41ae02ac-015b-4eef-9fb6-e51e6f1f5d18.png)

**Comment by gao-sun** [comment]
https://stackoverflow.com/questions/3582552/what-is-the-format-for-the-postgresql-connection-string-url

**Comment by liushunshun** [comment]
@gao-sun  thank you very much.
