### ISSUE TITLE
bug: logto admin page cors

### ISSUE THREAD

**Issue by Muromi-Rikka** [logto-io/logto#3250]
### Describe the bug

admin always use logto api,but it's cors

### Expected behavior
admin use own api

### Context

OS: 

Environment:  docker compose

Logto version:  edge

Node version: in docker 

Postgres version: 15

Command of starting Logto: in docker

### Screenshots

![image](https://user-images.githubusercontent.com/22149502/221904839-37c552db-aca9-41a4-bf41-06931173446c.png)

traefik config

![image](https://user-images.githubusercontent.com/22149502/221905255-12fb2567-fac6-44ff-9530-c4625b8f0683.png)

**Comment by charIeszhao** [comment]
Which version of Logto are you using? We've just fixed several CORS related bugs in rc.3 as well as in the master branch

**Comment by Muromi-Rikka** [comment]
![image](https://user-images.githubusercontent.com/22149502/222078084-06d08bb3-4a03-4e8d-9a71-9b3bdd03add4.png)

**Comment by simeng-li** [comment]
We did have some minor CORS rule updates. Could you pull the latest image and try again? P.S. edge might not be stable. If you prefer a stable version of the Logto instance, please try rc.3 instead.

**Comment by waltcow** [comment]
this issue can still reproduce
