### ISSUE TITLE
bug: Error: Unexpected response error from the server.

### ISSUE THREAD

**Issue by zedzhu** [logto-io/logto#3259]
### Describe the bug

I got an error after I sign in logto admin:
![image](https://user-images.githubusercontent.com/6426766/222097709-fb9dac20-3fa7-4fb6-9c9b-664777fc3b61.png)

POST /oidc/token 400 10ms 95b:
{"error":"invalid_request","error_description":"mismatch in body and authorization client ids"}

### Expected behavior

Login Success.

### Context

OS: 

Environment: 
      - ALL_YES=1
      - NO_INQUIRY=0
      - TRUST_PROXY_HEADER=1
     
Logto version: 
docker image: ghcr.io/logto-io/logto:prerelease

Node version:

Postgres version: 
postgres:15

Command of starting Logto: 
["sh", "-c", "npm run cli db seed -- --swe && npm start"]

**Comment by gao-sun** [comment]
a request sample including full payload and response will be appreciated

**Comment by zedzhu** [comment]
It's OK in Chrome, but still not work in MS Edge. Below are request and response info:

Request URL: URL: https://xxx.com/oidc/token
Request Headers:
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Authorization: Basic c3VwYWJhc2U6c3VwZXJncmVhdDg4OA==
Connection: keep-alive
Content-Length: 273
Content-Type: application/x-www-form-urlencoded
Cookie: _interaction=idmOJSVZP2u8VvZIBJ80T; _interaction.sig=mj9o69_xlRX4SBXPL3lj4Q0o4FM; _session=NE5zxlhGC07RpnZzm8gio; _session.sig=NnzounYjAKZ_M31wXpsP-Q9BcDE
Host: xxx.com
Origin: https://xxx.com
Referer: https://xxx.com/console/callback?code=W7brDZaatLQb5JOXoa0n4gkIHZTSoQNLM0uk-3v_FLk&state=z5NWAeUi5GWrDC9K8PCy1ju0yAfYDgPSaXGs0P-wbu5OxaKPLz2f7lW6Nl57bRhyOYp3rWHjIPlvTRlU0WU1mg&iss=https%3A%2F%2Fxxx.com%2Foidc
sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Microsoft Edge";v="110"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50

Response Header:
Access-Control-Allow-Origin: https://xxx.com
Access-Control-Expose-Headers: WWW-Authenticate
cache-control: no-store
Connection: keep-alive
Content-Length: 95
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Mar 2023 03:26:25 GMT
Server: nginx/1.18.0 (Ubuntu)
Vary: Origin

Response Body:
{"error":"invalid_request","error_description":"mismatch in body and authorization client ids"}

**Comment by charIeszhao** [comment]
@zedzhu Do you still have this issue right now? Can you try it real quick in the latest version (1.4.0) or [Logto Cloud](https://cloud.logto.io/)?
