### ISSUE TITLE
bug: "manifest unknown" in Interactive demo

### ISSUE THREAD

**Issue by zedzhu** [logto-io/logto#3266]
I clicked Interactive demo link(https://logtoio-demo-haqw6z7u29l.ws-us89.gitpod.io/) and it didn't work:
### Screenshots

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/6426766/222316978-da3ed40a-decf-48b8-a133-f22f362a1ecc.png">

**Comment by gao-sun** [comment]
let me take a look

**Comment by gao-sun** [comment]
thanks. looks like ghcr registry is not available in gitpod, strange

**Comment by gao-sun** [comment]
should work now
