### ISSUE TITLE
bug: auth.unauthorized ERR_JWT_CLAIM_VALIDATION_FAILED

### ISSUE THREAD

**Issue by zedzhu** [logto-io/logto#3267]
docker image:
ghcr.io/logto-io/logto:prerelease
entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]

{"message":"Unauthorized. Please check credentials and its scope.","code":"auth.unauthorized","data":{"code":"ERR_JWT_CLAIM_VALIDATION_FAILED","name":"JWTClaimValidationFailed","claim":"aud","reason":"check_failed"}}

My JWT info in request header:
Header:
{
    "alg": "ES384",
    "typ": "at+jwt",
    "kid": "WPFYCi_gMjTvN2g2FRbXrt7AoX84wkV2L8O0DFbPOvY"
}

Payload:
{
    "jti": "8sjwewQAPMJJ4U7JGpe_P",
    "sub": "aQUG7XmojpgU",
    "iat": 1677671800,
    "exp": 1677675400,
    "scope": "all",
    "client_id": "admin-console",
    "iss": "https://xxx.com/oidc",
    "aud": "https://default.logto.app/api"
}

My resources table:
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/6426766/222322789-fa450752-4026-49ca-a7b8-00069dd25b39.png">

**Comment by gao-sun** [comment]
more context is appreciated, like which endpoint were you accessing

**Comment by dadvir** [comment]
hi,

I'm facing a similar situation.
I've created a machine to machine api and I'm trying to access some management resources.
I took the steps illustrated at https://docs.logto.io/sdk/m2m/ and I'm getting a similar response.

I've successfully called `/oidc/token` and got a valid response:
```json
{
    "access_token": "eyJhbG......zR8",
    "expires_in": 3600,
    "token_type": "Bearer"
}
```

when I tried to call `/api/applications` I got the following 401 response:
```json
{
    "message": "Unauthorized. Please check credentials and its scope.",
    "code": "auth.unauthorized",
    "data": {
        "code": "ERR_JWT_CLAIM_VALIDATION_FAILED",
        "name": "JWTClaimValidationFailed",
        "claim": "aud",
        "reason": "check_failed"
    }
}
```

I've also tried some other api calls and got the same response.
Your help will be highly appreciated.
