### ISSUE TITLE
bug: npm init @logto@latest

### ISSUE THREAD

**Issue by mrchenxxx** [logto-io/logto#3273]
When I run npm init on Windows@ logto@latest Error will be reported
PS C:\Users\83448\Desktop> npm init @logto@latest
系统找不到指定的路径。
npm ERR! code 1
npm ERR! path C:\Users\83448\Desktop
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c logto-create

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\83448\AppData\Local\npm-cache\_logs\2023-03-02T13_11_33_464Z-debug-0.log

0 verbose cli D:\soft\node\node.exe D:\soft\node\node_modules\npm\bin\npm-cli.js
1 info using npm@9.3.1
2 info using node@v18.14.1
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:D:\soft\node\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\83448\Desktop\.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:C:\Users\83448\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\83448\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 11ms
17 timing npm:load:configload Completed in 11ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm init @logto@latest
21 verbose argv "init" "@logto@latest"
22 timing npm:load:setTitle Completed in 2ms
23 timing config:load:flatten Completed in 4ms
24 timing npm:load:display Completed in 5ms
25 verbose logfile logs-max:10 dir:C:\Users\83448\AppData\Local\npm-cache\_logs\2023-03-02T13_11_33_464Z-
26 verbose logfile C:\Users\83448\AppData\Local\npm-cache\_logs\2023-03-02T13_11_33_464Z-debug-0.log
27 timing npm:load:logFile Completed in 7ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 29ms
31 silly logfile start cleaning logs, removing 2 files
32 timing arborist:ctor Completed in 1ms
33 silly logfile done cleaning log files
34 http fetch GET 200 https://registry.npmjs.org/@logto%2fcreate 2403ms (cache revalidated)
35 timing arborist:ctor Completed in 0ms
36 timing arborist:ctor Completed in 0ms
37 timing command:init Completed in 2766ms
38 verbose stack Error: command failed
38 verbose stack     at ChildProcess.<anonymous> (D:\soft\node\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
38 verbose stack     at ChildProcess.emit (node:events:513:28)
38 verbose stack     at maybeClose (node:internal/child_process:1091:16)
38 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
39 verbose cwd C:\Users\83448\Desktop
40 verbose Windows_NT 10.0.22000
41 verbose node v18.14.1
42 verbose npm  v9.3.1
43 error code 1
44 error path C:\Users\83448\Desktop
45 error command failed
46 error command C:\Windows\system32\cmd.exe /d /s /c logto-create
47 verbose exit 1
48 timing npm Completed in 2866ms
49 verbose code 1
50 error A complete log of this run can be found in:
50 error     C:\Users\83448\AppData\Local\npm-cache\_logs\2023-03-02T13_11_33_464Z-debug-0.log

**Comment by whwnow** [comment]
I got the same error. how can i fix it?
