### ISSUE TITLE
feature request: provide response data document in API doc

### ISSUE THREAD

**Issue by waltcow** [logto-io/logto#3279]
### What problem did you meet?

Currently, the [API doc](https://docs.logto.io/zh-cn/api#tag/Users/paths/~1api~1users~1:userId/patch) is missing response data structure part, which is very inconvenient to use

### Describe what you'd like Logto to have

Provide more details on  api response structure

**Comment by gao-sun** [comment]
sure. we'll gradually add response types on 23H1
