### ISSUE TITLE
feature request: More responsive login screen

### ISSUE THREAD

**Issue by Tc-001** [logto-io/logto#3287]
### What problem did you meet?
Currently the desktop version of the login screen is almost unusable  on smaller screens. 
Logto uses `react-device-detect` to mitigate it somewhat, but that isn't ideal because certain desktop usecases would still want the non-mobile version to be small (like using a popup or an iframe to authenticate)

Firefox devtools mobile preview:
![image](https://user-images.githubusercontent.com/55956895/222904732-751dc9af-0e5d-46a3-adc9-ebc7989e47f2.png)

Electron-based popup authentication
![image](https://user-images.githubusercontent.com/55956895/222905112-ce439d99-f123-40d6-886a-5d53ee157446.png)

### Describe what you'd like Logto to have

I would like the desktop version of the login page to work both on bigger and smaller screens, it could be as simple as replacing `react-device-detect` with a screen width check, or re-working the CSS to be responsive

**Comment by Rany0101** [comment]
Thank you for your feedback about the responsive screen issue. We will resolve this problem as soon as possible.

**Comment by gao-sun** [comment]
it looks like we have a PR merged for this issue. can we consider it as resolved? @Tc-001 @Rany0101 @simeng-li

**Comment by Tc-001** [comment]
Hello!
Sorry for the late response, got lost in my notifications.
Yes, the issue has been solved.
