### ISSUE TITLE
feature request: SAML support

### ISSUE THREAD

**Issue by adyanth** [logto-io/logto#3336]
### What problem did you meet?
No support for SAML

### Describe what you'd like Logto to have
Support for SAML

**Comment by gao-sun** [comment]
https://github.com/logto-io/connectors/tree/master/packages/connector-saml

**Comment by adyanth** [comment]
Hey @gao-sun, I mean for Logto to be a SAML IdP, not an SP. I want my application to connect to logto over SAML instead of OIDC.

**Comment by gao-sun** [comment]
thanks for clarifying @adyanth. Logto was designed for first-party apps currently, so there's no official support to use Logto as an IdP. in the long run, Logto may support to be used as IdP since it's widely requested. i created #3344 for tracking
