### ISSUE TITLE
feature request: use Logto as third-party IdP

### ISSUE THREAD

**Issue by gao-sun** [logto-io/logto#3344]
### What problem did you meet?

Logto was designed for first-party apps currently, so there's no official support to use Logto as an IdP. Since the demands are increasing, we created this issue for tracking.

### Describe what you'd like Logto to have

- use Logto as an OpenID Connect IdP

---

## Update 2023-05-27

With the release of Logto v1.4.0, you can now utilize Logto as a third-party OAuth or OpenID Connect (OIDC) IdP for authentication in most products. We have written several blog articles that cover these integrations:

- [Streamline OAuth and OIDC Authentication with Logto](https://blog.logto.io/oauth-and-oidc-authentication/?utm_source=github&utm_medium=pr)
- [Implement ChatGPT plugins user authentication with Logto](https://blog.logto.io/implement-chatgpt-plugins-user-authentication-with-logto/?utm_source=github&utm_medium=pr)
- [Simplify Outline authentication with Logto](https://blog.logto.io/simplify-outline-authentication-with-logto/?utm_source=github&utm_medium=pr)

While the general tutorial should address most situations, we welcome new tutorials specific to certain products. If you would like to contribute or request a tutorial, please feel free to contact our team.

## How about authorization?

In the realm of OAuth, scopes are commonly used for access control. However, Logto utilizes [Resource Indicators](https://www.rfc-editor.org/rfc/rfc8707) and requires a `resource` for Role-based Access Control (RBAC).

We understand that not all products have adopted Resource Indicators. Therefore, we are actively working on a backward-compatible update. Once we reach a final conclusion, we will update this description and close the issue accordingly.

## I want to control user access for certain apps

Once again, Logto was primarily designed for first-party apps, focusing on Customer IAM. The out-of-the-box support for managing third-party resources is currently beyond the scope of Logto. However, we remain optimistic about expanding into this area in the future and welcome any ideas or discussions you may have.

**Comment by rundx** [comment]
You're only missing SAML to cover almost all Enterprise products

**Comment by gao-sun** [comment]
> You're only missing SAML to cover almost all Enterprise products

thank you! SAML is another topic - since Logto itself is built on top of an OIDC provider, it's natural to use it as an OAuth/OIDC IdP.

created #4106 to track this.
