### ISSUE TITLE
feature request: deploy on kubernetes

### ISSUE THREAD

**Issue by lingdie** [logto-io/logto#3404]
### What problem did you meet?
How can I deploy logto on k8s？

**Comment by gao-sun** [comment]
this is not related to Logto i think

**Comment by lingdie** [comment]
I mean, I can provide a solution to deploy logto on k8s if you need.

**Comment by gao-sun** [comment]
@lingdie thanks, that will be highly appreciated.

**Comment by gao-sun** [comment]
@lingdie do you have any plan on this?

**Comment by Mohit21GoJs** [comment]
@gao-sun Is there a way we can deploy self hosted version on kubernetes? i would like to implement this in our cloud.
