### ISSUE TITLE
bug: Invalid JWK HTTP Content-Type Header

### ISSUE THREAD

**Issue by feropeterko** [logto-io/logto#3473]
### Describe the bug
KrakenD API gateway does not accept JWK URL (e.g. http://auth.server.com/oidc/jwks) during validation process. It fails with error "Unable to validate the token: should have a JSON content type for JWKS endpoint".

Current HTTP Header is set to "application/jwk-set+json".

### Expected behavior
Set HTTP header to simple "application/json"

### How to reproduce?
Validate JWT token using KrakenD endpoint. Sample krakend.json configuration

```    {
      "__description__": "Test operation",
      "endpoint": "/v1/test",
      "method": "GET",
      "output_encoding": "json",
      "extra_config": {
        "auth/validator": {
          "alg": "ES384",
          "jwk_url": "http://logto:3001/oidc/jwks",
          "disable_jwk_security": true,
          "operation_debug": true
        }
      },
      "backend": [
        {
          "url_pattern": "/api/users/1",
          "encoding": "json",
          "method": "GET",
          "host": [
            "http://api"
          ],
          "deny": [ "password" ]
        }
      ]
    }
```

### Context

OS: Alpine

Environment: Docker

Logto version: 1.0.0-rc.3

Node version: 18

Postgres version: 14

Command of starting Logto: [ "sh", "-c", "npm run cli db seed -- --swe && npm start" ]

**Comment by gao-sun** [comment]
i think this is [standard](https://datatracker.ietf.org/doc/html/rfc7517#section-8.5.1) for JWK response?
