### ISSUE TITLE
How can i init the project ? 

### ISSUE THREAD

**Issue by liushunshun** [logto-io/logto#3480]
## I encountered the following issues during initialization , please help me, thank you very much . 
<img width="785" alt="0ec77827a3b2b97e2f76d386de19b78" src="https://user-images.githubusercontent.com/8638224/226087652-9e970ed6-6e62-4a3e-ad68-44d6fe8d48c1.png">

![image](https://user-images.githubusercontent.com/8638224/226087849-cc03ebd0-e57c-4d40-ada5-06961b644a39.png)

**Comment by liushunshun** [comment]
node version 18.12.0

**Comment by gao-sun** [comment]
kindly remind this is not a support forum, you can ask for help in elsewhere
