### ISSUE TITLE
bug: Init success but home page 404 

### ISSUE THREAD

**Issue by liushunshun** [logto-io/logto#3482]
![image](https://user-images.githubusercontent.com/8638224/226092504-a0d22934-26b9-488e-8a15-f9d0f6cad05c.png)

![image](https://user-images.githubusercontent.com/8638224/226092679-893907f6-6697-4266-b72a-24beffc75d29.png)

# http://localhost:3002/

![image](https://user-images.githubusercontent.com/8638224/226092574-34d6607a-1f39-49e7-8d0f-2d3af8143ee7.png)

**Comment by gao-sun** [comment]
please follow our issue template and let us know if you updated
