### ISSUE TITLE
bug: Init success but home page 404

### ISSUE THREAD

**Issue by liushunshun** [logto-io/logto#3483]
### Describe the bug
Init success but home page 404

### Expected behavior
Admin home page success 

### How to reproduce?

1. npm init @logto@latest
2. cd logto
3. npm start
4. access the URL http://localhost:3002/

### Context

OS: 	
Ubuntu Server 22.04 LTS 64

Environment:  

Logto version: @logto/create@1.0.0-rc.2

Node version:  v18.12.0

Postgres version:  postgresql 15

Command of starting Logto:   npm start

### Screenshots

<img width="854" alt="1679126650128" src="https://user-images.githubusercontent.com/8638224/226093471-75fa5272-ac09-4369-8a11-b07aed3ccf14.png">

<img width="792" alt="92b088fd53e091de3dbbc9c981452f9" src="https://user-images.githubusercontent.com/8638224/226093483-e6952fd4-530b-435d-9eaa-07407a5f6574.png">

<img width="647" alt="42d7c3df5f61d299b14a60395c3bd41" src="https://user-images.githubusercontent.com/8638224/226093493-80c6f9df-c24e-4425-ab85-0d78c86a57b5.png">

**Comment by liushunshun** [comment]
I also encountered this problem using docker compose ,  So it shouldn't be a code bug .  Does the server require special settings ？

**Comment by monyuan** [comment]
I also encountered this problem。 docker+nginx

**Comment by liushunshun** [comment]
Config the env  "ADMIN_ENDPOINT" , it works . Thanks for your help  @gao-sun
