### ISSUE TITLE
bug: docker&nginx run with 404

### ISSUE THREAD

**Issue by monyuan** [logto-io/logto#3490]
nginx config:

` proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://logto_upstream;
    proxy_redirect off;`

docker log:
`> start
> cd packages/core && NODE_ENV=production node .

(node:17) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Core app is running at http://localhost:3001/
Core app is running at https://***/
Admin app is running at http://localhost:3002/
Admin app is running at https://***/
Init tenant: default
  <-- GET /
  --> GET / 200 18ms 579b
  <-- GET /
  --> GET / 200 3ms 579b`

404 

`
      GET https://***/api/.well-known/sign-in-exp 404
        
Uncaught (in promise) HTTPError: Request failed with status code 404
    at r (Ky.ts:51:17)
    at async gh._retry (Ky.ts:254:4)
    at async a.<computed> [as json] (Ky.ts:87:11)
    at async qS (sign-in-experience.ts:26:10)
    at async App.tsx:45:13`

**Comment by monyuan** [comment]
please remove

location ~ /.well-known {
            allow all;  
	 }

**Comment by gao-sun** [comment]
please follow the template

**Comment by gao-sun** [comment]
for courtesy, you can try setting env `TRUST_PROXY_HEADER=1`

**Comment by JZLeung** [comment]
same, i set the env `TRUST_PROXY_HEADER=1` and `ADMIN_ENDPOINT=https://admin-endpoint.com/`, when i visit `https://admin-endpoint.com/`, it will redirect to `https://logto-endpoint.com/`
