### ISSUE TITLE
bug: Custom OAuth 2.0 prompt missing token_type

### ISSUE THREAD

**Issue by AiOkk** [logto-io/logto#3518]
### Describe the bug

Custom OAuth 2.0 Wechat web page authorization, callback error, prompt missing token_type

`{"message":"连接器错误响应","code":"connector.invalid_response","data":{"issues":[{"code":"invalid_type","expected":"string","received":"undefined","path":["token_type"],"message":"Required"}],"name":"ZodError"},"details":"Error in key path \"token_type\": (invalid_type) Expected string but received undefined."}`

### How to reproduce?

You can apply for Wechat test number at the test link:
Https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login
And view Wechat's documentation at the following link:
Https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html

Paste your JSON code:
`{
  "scope": "snsapi_userinfo",
  "clientId": "<appid>",
  "profileMap": {
    "id": "openid",
    "name": "nickname",
    "avatar": "headimgurl"
  },
  "clientSecret": "<secret>",
  "customConfig": {
    "appid": "<appid>",
    "secret": "<secret>"
  },
  "tokenEndpoint": "https://api.weixin.qq.com/sns/oauth2/access_token",
  "userInfoEndpoint": "https://api.weixin.qq.com/sns/userinfo",
  "authorizationEndpoint": "https://open.weixin.qq.com/connect/oauth2/authorize",
  "tokenEndpointResponseType": "json"
}`

### Screenshots
![image](https://user-images.githubusercontent.com/11790369/226197308-72b5571f-afd6-4f0c-893e-c9de716cb8c6.png)

**Comment by wangsijie** [comment]
According to the [WeChat official doc](https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Wechat_Login.html), the token response does not have "token_type", it is like:

```json
{ 
  "access_token":"ACCESS_TOKEN", 
  "expires_in":7200, 
  "refresh_token":"REFRESH_TOKEN",
  "openid":"OPENID", 
  "scope":"SCOPE",
  "unionid": "o6_bmasdasdsad6_2sgVt7hMZOPfL"
}
```

But in OAuth 2 standard, the `token_type` is required (usually `Bearer`). So it seems that WeChat does not followt he standard OAuth 2 standard.

@AiOkk You can take a look at our implementation of WeChat connector: https://github.com/logto-io/connectors/blob/2fbb57815406bace113617a6304eafcfc5db2d61/packages/connector-wechat-web/src/types.ts#LL7C3-L7C3

Can you share more details on why you choose OAuth connector instead of "WeChat Web"?

**Comment by AiOkk** [comment]
Is there a way to customize the parameters? This can better support non-standard OAuth 2 interfaces on the market. Using WeChat Official Account's web authorization allows for silent authorization if the WeChat Official Account has been authenticated. If authentication and authorization need to be obtained through the Open Platform, independent developers will incur additional expenses. Can logto provide an additional choice in the current WeChat connector, such as native, web, and official account?

**Comment by AiOkk** [comment]
The login logic for the official account in my current project is as follows: when a user opens a page in the official account or WeChat client, it checks whether the user is a registered user. If not, it redirects to snsapi_userinfo to obtain the user's basic information, including openid, avatar, and nickname. If the user is already registered, it performs a silent login and redirects to snsapi_base. This ensures the best login experience for users in WeChat official accounts without being disturbed repeatedly.

**Comment by wangsijie** [comment]
In this case, I'll sugguest you create a connector: https://docs.logto.io/docs/recipes/create-your-connector/

**Comment by wangsijie** [comment]
And if the only problem in the OAuth connector is `token_type`, we can consider upgrate the existing OAuth connector to support it

**Comment by AiOkk** [comment]
Thank you, you can upgrade and try it first. Based on the current error message, the problem should be caused by the non-existent `token_type` field, but it is uncertain if there are any other issues in the next step. It would be even better if the official could support the WeChat Official Account connector I described above.

**Comment by wangsijie** [comment]
Yeah, the second proposal looks better, I'll take a look and discuss it with the team. Progress will be updated there.

**Comment by wangsijie** [comment]
@AiOkk After discussion, I think the best way for you is to create a "Wechat Official Account" connector, the `getAuthorizationUri` function has a "userAgent" param for you to determine if it is in a WeChat web browser:

```
export type GetAuthorizationUri = (payload: {
    state: string;
    redirectUri: string;
    connectorId: string;
    connectorFactoryId: string;
    jti: string;
    headers: {
        userAgent?: string;
    };
}, setSession: SetSession) => Promise<string>;
```

Feel free to reopen if you have eny problems.
