### ISSUE TITLE
bug: Custom domain name, always visit 404

### ISSUE THREAD

**Issue by dh-free** [logto-io/logto#3525]
### Describe the bug
Custom domain name, after deployment, always visit 404

### Expected behavior

docker + nginx  deployment，Normal visit https://admin.elites.ink/
### Context

OS: 

Environment: 
docker + nginx
Logto version: 
svhd/logto:prerelease
Node version:

Postgres version: 
14-alpine
Command of starting Logto: 

### Screenshots

![image](https://user-images.githubusercontent.com/48708512/226238684-5931a28c-c133-4230-8ba4-ceccd9f36bb9.png)
![image](https://user-images.githubusercontent.com/48708512/226238728-047b12a1-7bc9-49f3-a38f-6d1ff04be5d5.png)
![image](https://user-images.githubusercontent.com/48708512/226238739-124d3e20-5e24-424b-a80f-f2ce3a000ce9.png)
![image](https://user-images.githubusercontent.com/48708512/226238771-5bf51168-306e-4402-bd72-47e0c41174a8.png)

**Comment by gao-sun** [comment]
try set `TRUST_PROXY_HEADER=1`
