### ISSUE TITLE
feature request: Redirect URIs wildcard

### ISSUE THREAD

**Issue by feropeterko** [logto-io/logto#3551]
### What problem did you meet?
It would be great to allow wildcards in redirect URIs

### Describe what you'd like Logto to have
Allow to write https://app.company.com/* as sign-in and sign-out redirect URIs. Also trailing slashes could be ignored.

**Comment by gao-sun** [comment]
sorry i think it's not possible per [OAuth 2.0](https://www.rfc-editor.org/rfc/rfc6819#section-5.2.3.5):

> ... and the "redirect_uri" should be the full URI as
   defined in [[RFC6749](https://www.rfc-editor.org/rfc/rfc6749)]

we would like to use wildcard as well, but we decided to follow the protocol
