### ISSUE TITLE
feature request: Support custom/private connector imported at runtime

### ISSUE THREAD

**Issue by exotfboy** [logto-io/logto#3558]
### What problem did you meet?
We need to integrate a third IDP derived from OAuth2, however the protocol exposed for auth is different from OAuth2. So we can not connect it with logto directly.

### Describe what you'd like Logto to have

Maybe Logto should provide a plugin mechanism for custom connectors at runtime. Since some private connector is not suitable for open source.

**Comment by simeng-li** [comment]
We do allow the import of custom connectors. cc: @wangsijie might have more context

**Comment by wangsijie** [comment]
We do support install custom (or private) connector, here is the doc: https://docs.logto.io/docs/recipes/create-your-connector/connector-implementation-guide#install-your-own-connectors

Notice that after installation, you need to restart the Logto instance. Let me know if you have any further questions.

**Comment by exotfboy** [comment]
Thanks, we will have a try.
