### ISSUE TITLE
bug: Enable access to the Management API. Encountered a 500 error.

### ISSUE THREAD

**Issue by AiOkk** [logto-io/logto#3562]
### Describe the bug

After creating the Machine to Machine application in Applications, I am unable to open "Enable admin access" and receive a prompt as shown in the image.
Both self-deployment and the official cloud platform are experiencing the same 500 error.

### Screenshots

![image](https://user-images.githubusercontent.com/11790369/226535792-b9f31460-f6f6-48ba-b875-1d2f083a6a45.png)

**Comment by gao-sun** [comment]
thanks, taking a look

**Comment by gao-sun** [comment]
please try cloud again. should be fixed. we're working on OSS

**Comment by gao-sun** [comment]
OSS 1.0.1 launched, please check again
