### ISSUE TITLE
bug: Issues with social account binding and caching affecting debugging

### ISSUE THREAD

**Issue by songhn233** [logto-io/logto#3572]
### Describe the bug

Hey, I have been using this project recently, and for the most part, it has been working well. However, there are some issues that have been affecting my experience. 

When linking social accounts, the guidance provided is insufficient for some platforms (such as GitHub), which can be confusing for people who are not familiar with the process, and also makes debugging difficult. 

The oidc system also attempts to automatically log in when binding social accounts, but if the OAuth app information is incorrect, it can result in errors after the callback. I have not found an easy way to remove the cached social account binding, except by debugging in incognito mode every time.

Additionally, since the API and admin console use the same third-level domain, clearing cookies or cache sometimes affects the console's status and prevents login. Furthermore, it is not possible to clear cached social account login information.

Thank you for your time and consideration.

**Comment by songhn233** [comment]
> @songhn233 could you provide some additional context? Which particular flow or process were you having difficulty understanding? Were you trying to set up your own GitHub connector?

@simeng-li, Firstly, apologies for the delayed response. I have not been able to reproduce this issue in my testing after reported it (although it is strange that containers deployed in Docker do not support hot reloading 😂). The application is currently working fine.

Let me elaborate on the problem I encountered earlier. After logging in using the GitHub connector, subsequent logout and login attempts would automatically use the previous GitHub credentials, causing problems with revalidating the OAuth application information if the information was entered incorrectly. However, this issue seems to have disappeared now. I'm not sure if the auto-login behaviour described above is a feature or just a bug I happened to find. 

In any case, there are currently no issues, and each login attempt now takes you to the default landing page for selection:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/47357585/227799630-eb2b60ef-ea2d-4e6e-9c8d-364434bffc30.png">

As for the previous GitHub configuration issue, it was mainly due to my lack of familiarity with configuring third-party authentication components. For example, I did not realise that logging out of GitHub would force a revalidation of OAuth. 

The main issue is incorrect filling of the `Homepage URL` and `Authorization Callback URL`. During testing, I used `localhost` which caused problems with the login redirect because the configuration was set to `http://localhost:xxxx` and `https://{logto_url}/callback/${connector_id}`. In fact, changing the `homepage URL` to `https://{logto_url}` solved the problem. Auth0 has [similar documentation](https://marketplace.auth0.com/integrations/github-social-connection):

<img width="758" alt="image" src="https://user-images.githubusercontent.com/47357585/227800063-1aefc31e-4bf7-4279-babb-8e2bb94ef684.png">

**Comment by simeng-li** [comment]
No worries. Thank you for your feedback, and glad to know you have worked it out. 

1. Auto-login, also known as auto-consent, is a typical process in OIDC. When you log out of Logto, all sign-in sessions and cookies are cleared from Logto's server. However, your sign-in status remains active on the GitHub authentication server, allowing the GitHub authentication app to consent to sign-in requests from Logto automatically. This is why you are logged in automatically every time, even after signing out from Logto.

2. In terms of setting up a new connector configuration, I fully understand how confusing it could be, especially for someone with complicated configs. As the configs may vary, we try our best to provide detailed instructions on every connector. Better go through the instruction panel on the left before setting up your new connectors.  

<img width="662" alt="image" src="https://user-images.githubusercontent.com/36393111/227831821-469af9f6-9def-4162-82e2-e9ae023fc7fb.png">


[docs](https://docs.logto.io/docs/recipes/configure-connectors/configure-social-connector)

Let me know if this helps. Any further suggestions are welcomed.
