### ISSUE TITLE
bug: did not receive the register mail

### ISSUE THREAD

**Issue by feitas** [logto-io/logto#3601]
### Describe the bug

Did not receive the register mail.
I tried two mail provider:
- Tencent enterprise mail
- dingtalk mail
ps: I checked the trash box

### How to reproduce?

https://auth.logto.io/sign-in
![image](https://user-images.githubusercontent.com/9913069/227721370-938ebd81-0419-4d6e-b110-f85664a111ea.png)

### Context

OS: 

Environment: 

Logto version: 

Node version:

Postgres version: 

Command of starting Logto:

**Comment by gao-sun** [comment]
more context is appreciated

**Comment by feitas** [comment]
I tried again, Tencent Exmail is ok, Dingtalk Mail does not work. So I closed this issue.
