### ISSUE TITLE
bug: CORS error 

### ISSUE THREAD

**Issue by waltcow** [logto-io/logto#3618]
### Describe the bug

 CORS issue occur when integrate logto v1.0.3 with next-js

### How to reproduce?

![image](https://user-images.githubusercontent.com/3941174/228120637-29bfa9fe-119d-40e7-b5d3-e65ec5b1c5ee.png)

![image](https://user-images.githubusercontent.com/3941174/228120663-0f6acead-7028-4ba8-814a-09e6b0570bca.png)

![image](https://user-images.githubusercontent.com/3941174/228120686-7466c584-1d51-4e6f-97c0-76eb5a051910.png)

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/3941174/228120840-76235dc8-38d9-43e9-ba54-34e0c8cde12b.png">

<img width="1805" alt="image" src="https://user-images.githubusercontent.com/3941174/228148525-c4e95e0d-b05b-4d7f-9f77-ca2bbd4c39ec.png">

### Context

OS: 

Environment: 

Logto version: 
v1.0.3

Node version:

Postgres version: 

Command of starting Logto:

**Comment by wangsijie** [comment]
I'll take a look later.

**Comment by wangsijie** [comment]
Check this PR: https://github.com/logto-io/js/pull/465

**Comment by wangsijie** [comment]
The sample code updated. Use `location.assign` to prevent "prefetch".
