### ISSUE TITLE
feature request: can not create user with email manually when email address is set to signup identifier

### ISSUE THREAD

**Issue by ditschedev** [logto-io/logto#3650]
### Describe the bug
After setting the sign-in identifier to the e-mail address and e-mail address only it is not possible to create users in the user management with the email as an identifier. Instead it is forced that the username is provided, which does not accept emails.
In the user detail it is also not possible to set the identifier or e-mail address. This only works, when the identifier is set to email and the user does a self-registration in the browser. 

### Expected behavior
When the only defined identifier is set to the email address of the user, then it should be possible to create users manually by providing their email address instead of a username.

### How to reproduce?
1. Connect Email Provider (Connector)
2. Set sign-up identifier to email
3. add email to sign in methods
4. remove username sign in method
5. try to create a user in the user management

### Context

Logto version: latest docker tag (as of the creation of the issue)

**Comment by gao-sun** [comment]
thanks, @fleuraly will take a look

**Comment by charIeszhao** [comment]
This is a bit out-of-date. I just double checked the logic in the latest version of admin console, and it worked as expected now.
