### ISSUE TITLE
bug: The "--skip-seed" option does not work

### ISSUE THREAD

**Issue by LinLin00000000** [logto-io/logto#3657]
### Describe the bug

I used the "--skip-seed" option when creating the project and it didn't work, it still tried to manipulate the database.
### Expected behavior

Skip Feed Database.
### How to reproduce?

I initially tried the docker deployment solution and followed the tutorial to execute "npx @logto/cli db seed", which worked, but I had a little problem connecting to the database while running docker, so I switched to the npm init solution, but it failed.
### Context

OS: 

Environment: 
Linux version 5.15.0-56-generic (buildd@lcy02-amd64-004) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) # 62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
Logto version: 
1.1.0
Node version:
v18.15.0
Postgres version: 
psql (PostgreSQL) 15.2 (Ubuntu 15.2-1.pgdg22.04+1)
Command of starting Logto: 
npm init @logto@latest --skip-seed

### Screenshots

![image](https://user-images.githubusercontent.com/51076594/229267273-78b79a32-eeeb-46a4-9496-b9ead30ece08.png)

**Comment by LinLin00000000** [comment]
I solved the database connection problem of docker later, but a new problem came up.
![image](https://user-images.githubusercontent.com/51076594/229292724-469b0350-90ff-4c3a-be56-e948f669642f.png)
Then I followed the instructions and executed "npx @logto/cli db alteration deploy", and it gave me another error. I went to the official website to check the documentation, but there is very little information about database alterationd.
![image](https://user-images.githubusercontent.com/51076594/229292774-09993033-433c-4eca-b7c4-c5557483dab9.png)
After a day of work, the deployment was not successful. I'm sad that it seems like every command is reporting an error. 🥲

**Comment by LinLin00000000** [comment]
I tried again to delete the database and refeed, and another error was waiting for me.
![image](https://user-images.githubusercontent.com/51076594/229293488-a1025f4e-5315-4e48-ad01-b158cd9a3e81.png)
![image](https://user-images.githubusercontent.com/51076594/229293532-50de92d5-a2e1-468f-b1a6-330b15fa7d70.png)
Execute other commands, the error remains.
I'm tired, good night.

**Comment by gao-sun** [comment]
`--skip-seed` is for skipping data seeding, not table. for the latest error you posted, simple delete the role it shows, or you can use a fresh database to seed
