### ISSUE TITLE
feature request: Telegram Connector

### ISSUE THREAD

**Issue by jay-dee7** [logto-io/logto#3669]
### What problem did you meet?
Telegram is definitely one of the most popular chatting platform. While going through the connectors list, I realised there's none for Telegram.
I even went on to try and build a custom Connector for Telegram but I'm not able to wrap my head around how to do it. I went through the docs but no luck so far.

### Describe what you'd like Logto to have
Would it be possible to add Telegram as a connector? I've seen other projects to simply ignore it based on complexity of the how Telegram does OAuth (which is totally a pain-point).
For eg: https://github.com/nextauthjs/next-auth/issues/2406

Can support for Telegram be added? I'd be happy to contribute but I need some help since I can't quite get the flow right 

Telegram success API returns the following response in query params:
```
id=<number, userid>
first_name=<string>
username=<telegram username>
photo_url=<profile_pic_url, string>
auth_date=<unix timestamp>
hash=<hash of the data, useful for checksum validation>
```

They do not return an auth token (at least I'm not aware of it). All you can do is an integrity check on the response you receive (something like a checksum validation). I can go a bit more in detail if someone's up for the task or maybe help me with it?

**Comment by PouyaEvan** [comment]
any active update on this
