### ISSUE TITLE
feature request: customize id generation method

### ISSUE THREAD

**Issue by rockey2020** [logto-io/logto#3671]
### Describe the bug

1.The id of my user table is uuid data type
<img width="941" alt="image" src="https://user-images.githubusercontent.com/64777114/229565964-fce3ea89-c97a-4c1d-a2bf-1cc0a278f790.png">
<img width="863" alt="image" src="https://user-images.githubusercontent.com/64777114/229566071-23ef930b-1061-4a5e-a863-27c9369775f2.png">

2.When I initiate the request, the data type error occurs
invalid input syntax for type uuid: \"ZUnIm3tHexoJ\"
<img width="905" alt="image" src="https://user-images.githubusercontent.com/64777114/229566363-787c1bc1-3a88-4140-9c82-68e4c3273f7f.png">

3.When I get my user information, I see the corresponding string, and I don't understand why I don't use a separate id to store the userId
<img width="743" alt="image" src="https://user-images.githubusercontent.com/64777114/229566463-66d1c62d-f17d-4132-8047-ab68ff4b8aa4.png">

### Expected behavior

succee

### Context

OS: 

Environment: 
Docker

Logto version: 
1.1.0

Node version:
19

Postgres version: 
15

Command of starting Logto:

**Comment by rockey2020** [comment]
Can you provide option setting about user id generation, allow user to define int, string or uuid generation type

**Comment by simeng-li** [comment]
If you are trying to keep Logto as the SSOT of your user data, I would prefer following the original user ID's data source type when adding new mapping fields in a foreign table. Will you be able to change the id type in your own table?

**Comment by rockey2020** [comment]
@simeng-li 
yes As you said, when I change the id type of my own table to text, it will work.
But logto's id rules should be able to be generated by the user, for example, by exposing a variable in docker-compose for the user to choose the type or something

**Comment by gao-sun** [comment]
@rockey2020 are you interested in contributing?

**Comment by rockey2020** [comment]
@gao-sun sure This week I took the time to look at the code and submit a commit

**Comment by rockey2020** [comment]
@gao-sun after I read your code structure, I will explain how I will modify your code and ask for your opinion before I start writing it
![image](https://user-images.githubusercontent.com/64777114/231212540-d1b44f51-52c3-435c-ac70-420ae8071bbd.png)

**Comment by gao-sun** [comment]
@rockey2020 sounds awesome

**Comment by Zyles** [comment]
Implemented in PR here: https://github.com/logto-io/logto/pull/7962
