### ISSUE TITLE
feature request: enterprise sso

### ISSUE THREAD

**Issue by gao-sun** [logto-io/logto#3740]
### What problem did you meet?

Logto now supports the SSO experience across your apps, but yet the SSO services from your customers need to be integrated as well. For example, your customer requires that all emails end with `@foo.com` need to be authenticated by Google Workspace.

Please see [CIAM 101: Authentication, Identity, SSO](https://docs.logto.io/blog/ciam-101-intro-authn-sso/) for detailed explanation.

### Describe what you'd like Logto to have

For clarity, we call the feature of "integrating with your customer's SSO provider" Enterprise SSO. Logto needs to provide it.

**Comment by charIeszhao** [comment]
Enterprise SSO has been officially supported. Please check our documentation for more details: https://docs.logto.io/docs/recipes/single-sign-on/
