### ISSUE TITLE
feature request: organization (i.e. multi-tenancy or workspace)

### ISSUE THREAD

**Issue by gao-sun** [logto-io/logto#3741]
### What problem did you meet?

Finally we come to this far. These terms are confusing and even interchangeable between products.

For clarity, Organization and Tenant are two different things in Logto. Both of them have a precise definition, please see [CIAM 101: Authentication, Identity, SSO](https://docs.logto.io/blog/ciam-101-intro-authn-sso/) for details.

In short:

- Tenants are "physically isolated", usually they are not aware of each other.
- An organization is a group of identities in a Tenant.

You can see a lot of SaaS providers are using the Organization model for managing their users.

### Describe what you'd like Logto to have

Support Organization.

### Related issue

- #3603

**Comment by rannn505** [comment]
@gao-sun any ETA here? this feat will convince me to integrate Logto into our platform to replace Auth0

**Comment by gao-sun** [comment]
> @gao-sun any ETA here? this feat will convince me to integrate Logto into our platform to replace Auth0

@rannn505 thank you for you interest. we just reviewed the first version of the organization product design. we are now targeting late Oct this year.

btw, are you using Auth0's organization feature now? which part is most important to you? this will help us to have a better understanding on priorities.

**Comment by rannn505** [comment]
@gao-sun Thank you for the update on the timeline. Yes, I am currently using Auth0's organization feature. The most crucial aspects for me are the ability to group users under an organizational entity and assign a domain for IdP-initiated login with SSO. These capabilities would sufficiently meet our needs. Looking forward to the late October release!

**Comment by gao-sun** [comment]
@rannn505 NP and thank you! The feature you describe is exactly on our roadmap. Looking forward to your feedback then.

**Comment by kswzr** [comment]
Nice work @gao-sun! I am very excited to integrate Logto in our application, when this feature is available.

**Comment by gao-sun** [comment]
@kswzr thank you! This feature will be available in Q4.

**Comment by insulationman** [comment]
This is great!😃😃

**Comment by insulationman** [comment]
In case you want some ideas, this could be a good sign in experience for an org sign in (and it's what I use on Auth0):

1 username entry
1b select org if part of multiple orgs.
2 Password or federated sign in.

Applications are set up as using organizational sign in, individual accounts or both.

Hugs

**Comment by gao-sun** [comment]
@insulationman thank you for letting us know your expectation. let me know if i understand correctly, does it mean a username can have both password and federated sign-in for authentication? i.e. the following situation may exist:

- for org A, the user MUST sign in with password
- for org B, the user MUST sign in by a federated method, say AAD/Okta

**Comment by insulationman** [comment]
@gao-sun Thank you for your reply. I would say that is correctly understood. An organization is set to use an enterprise connector or the default Logto identity provider, or maybe social (multiple connectors per org is rarely needed from my experience).

I would however say that just being able to group user into orgs and having some org metadata json field would cover most use cases to begin with. Just having this would have been great for me. The enterprise connection is requested by a few end users in my experience, but I work with small businesses.

**Comment by rannn505** [comment]
> > @gao-sun any ETA here? this feat will convince me to integrate Logto into our platform to replace Auth0
> 
> @rannn505 thank you for your interest. we just reviewed the first version of the organization product design. we are now targeting late Oct this year.
> 
> btw, are you using Auth0's organization feature now? which part is most important to you? this will help us to have a better understanding on priorities.

@gao-sun How is it going?

**Comment by gao-sun** [comment]
> @gao-sun Thank you for your reply. I would say that is correctly understood. An organization is set to use an enterprise connector or the default Logto identity provider, or maybe social (multiple connectors per org is rarely needed from my experience).
> 
> I would however say that just being able to group user into orgs and having some org metadata json field would cover most use cases to begin with. Just having this would have been great for me. The enterprise connection is requested by a few end users in my experience, but I work with small businesses.

thank you. we are working on this feature and it'll be released later this month

**Comment by gao-sun** [comment]
> > > @gao-sun any ETA here? this feat will convince me to integrate Logto into our platform to replace Auth0
> > 
> > 
> > @rannn505 thank you for your interest. we just reviewed the first version of the organization product design. we are now targeting late Oct this year.
> > btw, are you using Auth0's organization feature now? which part is most important to you? this will help us to have a better understanding on priorities.
> 
> @gao-sun How is it going?

we experienced some delay (you know software development :-) ), and here's the latest schedule:

- Nov 14th: MFA
- Nov 21st: Organizations
- Nov 28th: Enterprise SSO

the schedule is final, you can follow us on [ProductHunt](https://www.producthunt.com/products/logto) or subscribe to the newsletter to get notified once it's live.

**Comment by insulationman** [comment]
@gao-sun Great work with this, and delivered on time too!

I have a few notes on the beta for my specific use case.

I think that the ability to immediately get a token for a given organization in the sign in flow important, you mentioned in the documentation that you were working on something like that i think.

Also, it would be great if the "regular" roles could be assigned on an organizational level, and if the token could contain scopes from those roles in the claim. 

I let my customers interact with my API so these things would be more straightforward for them if it was done in this way.

**Comment by charIeszhao** [comment]
Organizations feature has been official launched. Hence I'm closing the ticket.

Please check out our documentation for more details: https://docs.logto.io/docs/recipes/organizations/
