### ISSUE TITLE
bug:  How to set  redirect_uris with OIDC

### ISSUE THREAD

**Issue by Macfee** [logto-io/logto#3747]
### Describe the bug

I try to deploy logto, using oidc as the certification of outline with OIDC service. The outline domain name  is https://outline.test.com, and the logto domain name is http://localhost:3001. When using oidc to log in, it keeps prompting :
` {"message":"Invalid return link, the redirect_uri has not been registered by this application.","code":"oidc.invalid_redirect_uri","data":{"error_description":"redirect_uri did not match any of the client's registered redirect_uris"}}'. `
What should I do, I don't know where redirect_uris is set

### Expected behavior

authorization success.

### Context

 Container (Docker image)

**Comment by gao-sun** [comment]
https://docs.logto.io/docs/tutorials/get-started/#quick-troubleshooting
