### ISSUE TITLE
bug: How implement LogTo into Electron?

### ISSUE THREAD

**Issue by afk-cob** [logto-io/logto#3754]
### Describe the bug
I am using Electron with Vite and with Vue - https://evite.netlify.app/. I tried using @logto/vue but with no good result. 
Electron in dev mode is basicly Vue SPA but the routing need to be in hash mode. I created Vue app in LogTo admin console and set redirect uri to "http://localhost:5173/#/callback" but in Electron after trying to sign in it shows the error message "redirect_uris must not contain fragments". How to solve this?

There is another question, what to do in Electron in production?

### Expected behavior
Correctly auhenticate.

### How to reproduce?
Setup Electron - https://evite.netlify.app/.
Setup Vue LogTo integration, follow tutorial.

**Comment by gao-sun** [comment]
"redirect_uris must not contain fragments", so just remove the fragment in your redirect_uri

**Comment by gao-sun** [comment]
@afk-cob currently we don't have a tutorial available, nor a SDK for Electron. you are welcome to open a new issue for it
