### ISSUE TITLE
bug: logto init error

### ISSUE THREAD

**Issue by draftpaperkw** [logto-io/logto#3770]
info Download Logto from https://github.com/logto-io/logto/releases/download/v1.2.2/logto.tar.gz
info Target /tmp/logto.tar.gz
[info] ⠦ 0.0%node:events:491
      throw er; // Unhandled 'error' event
      ^

HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (file:///home/vazgb/.npm/_npx/b593440ac822a35d/node_modules/got/dist/source/core/index.js:706:31)
    at Request._onResponse (file:///home/vazgb/.npm/_npx/b593440ac822a35d/node_modules/got/dist/source/core/index.js:765:24)
    at ClientRequest.<anonymous> (file:///home/vazgb/.npm/_npx/b593440ac822a35d/node_modules/got/dist/source/core/index.js:783:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  input: undefined,
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1682568251947,
    socket: 1682568252019,
    lookup: 1682568252066,
    connect: 1682568252145,
    secureConnect: 1682568252550,
    upload: 1682568252671,
    response: 1682568252989,
    end: 1682568253055,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 72,
      dns: 47,
      tcp: 79,
      tls: 405,
      request: 121,
      firstByte: 318,
      download: 66,
      total: 1108
    }
  },
  options: Options {
    _unixOptions: undefined,
    _internals: {
      request: undefined,
      agent: { http: undefined, https: undefined, http2: undefined },
      h2session: undefined,
      decompress: true,
      timeout: {
        connect: undefined,
        lookup: undefined,
        read: undefined,
        request: undefined,
        response: undefined,
        secureConnect: undefined,
        send: undefined,
        socket: undefined
      },
      prefixUrl: '',
      body: undefined,
      form: undefined,
      json: undefined,
      cookieJar: undefined,
      ignoreInvalidCookies: false,
      searchParams: undefined,
      dnsLookup: undefined,
      dnsCache: undefined,
      context: {},
      hooks: {
        init: [],
        beforeRequest: [],
        beforeError: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: []
      },
      followRedirect: true,
      maxRedirects: 10,
      cache: undefined,
      throwHttpErrors: true,
      username: '',
      password: '',
      http2: false,
      allowGetBody: false,
      headers: {
        'user-agent': 'got (https://github.com/sindresorhus/got)',
        'accept-encoding': 'gzip, deflate, br'
      },
      methodRewriting: false,
      dnsLookupIpVersion: undefined,
      parseJson: [Function: parse],
      stringifyJson: [Function: stringify],
      retry: {
        limit: 2,
        methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
        statusCodes: [
          408, 413, 429, 500,
          502, 503, 504, 521,
          522, 524
        ],
        errorCodes: [
          'ETIMEDOUT',
          'ECONNRESET',
          'EADDRINUSE',
          'ECONNREFUSED',
          'EPIPE',
          'ENOTFOUND',
          'ENETUNREACH',
          'EAI_AGAIN'
        ],
        maxRetryAfter: undefined,
        calculateDelay: [Function: calculateDelay],
        backoffLimit: Infinity,
        noise: 100
      },
      localAddress: undefined,
      method: 'GET',
      createConnection: undefined,
      cacheOptions: {
        shared: undefined,
        cacheHeuristic: undefined,
        immutableMinTimeToLive: undefined,
        ignoreCargoCult: undefined
      },
      https: {
        alpnProtocols: undefined,
        rejectUnauthorized: undefined,
        checkServerIdentity: undefined,
        certificateAuthority: undefined,
        key: undefined,
        certificate: undefined,
        passphrase: undefined,
        pfx: undefined,
        ciphers: undefined,
        honorCipherOrder: undefined,
        minVersion: undefined,
        maxVersion: undefined,
        signatureAlgorithms: undefined,
        tlsSessionLifetime: undefined,
        dhparam: undefined,
        ecdhCurve: undefined,
        certificateRevocationLists: undefined
      },
      encoding: undefined,
      resolveBodyOnly: false,
      isStream: true,
      responseType: 'text',
      url: <ref *1> URL {
        [Symbol(context)]: URLContext {
          href: 'https://github.com/logto-io/logto/releases/download/v1.2.2/logto.tar.gz',
          origin: 'https://github.com',
          protocol: 'https:',
          hostname: 'github.com',
          pathname: '/logto-io/logto/releases/download/v1.2.2/logto.tar.gz',
          search: '',
          username: '',
          password: '',
          port: '',
          hash: ''
        },
        [Symbol(query)]: URLSearchParams {
          [Symbol(query)]: [],
          [Symbol(context)]: [Circular *1]
        }
      },
      pagination: {
        transform: [Function: transform],
        paginate: [Function: paginate],
        filter: [Function: filter],
        shouldContinue: [Function: shouldContinue],
        countLimit: Infinity,
        backoff: 0,
        requestLimit: 10000,
        stackAllItems: false
      },
      setHost: true,
      maxHeaderSize: undefined,
      signal: undefined,
      enableUnixSockets: true
    },
    _merging: false,
    _init: [ { isStream: true } ]
  }
}

Node.js v18.16.0
npm ERR! code 1
npm ERR! path /home/vazgb
npm ERR! command failed
npm ERR! command sh -c logto-create

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-04-27T03_58_59_415Z-debug-0.log

**Comment by gao-sun** [comment]
acknowledged and fixing

**Comment by gao-sun** [comment]
i just tested locally and it should work now. thanks for reporting.
