### ISSUE TITLE
feature request: Add npm manual installation

### ISSUE THREAD

**Issue by zuohuadong** [logto-io/logto#3777]
### What problem did you meet?
npm init @logto

Then:

Download https://github.com/logto-io/logto/releases/download/v1.2.2/logto.tar.gz

But it takes about 4 hours to download in China.

### Describe what you'd like Logto to have

Can we choose to use " https://ghproxy.com/github.com/logto-io/logto/releases/download/v1.2.2/logto.tar.gz" or "Add npm manual installation?"

**Comment by gao-sun** [comment]
`@logto/create` v1.3.0 comes with the support of download url:

```bash
npm create logto -- --download-url=https://ghproxy.com/github.com/logto-io/logto/releases/latest/download/logto.tar.gz
```
