### ISSUE TITLE
bug: Button, doesn't switch.

### ISSUE THREAD

**Issue by zuohuadong** [logto-io/logto#3783]
### Describe the bug
When I click the button, it doesn't switch. But there have already been requests.

As I recall, the first entry does not exist this issue. I SUSPECT THAT THIS BUG MAY OCCUR WHEN USING TWO ADMIN USERS AT THE SAME TIME.

### Context

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

v1.2.2  & v1.2.3

### Screenshots
![image](https://user-images.githubusercontent.com/11203929/234883122-d6f90316-9712-4016-bdbe-1a06736ea611.png)

I find it :

When i  add  "user" role :

![image](https://user-images.githubusercontent.com/11203929/234885472-0d0fa86e-f904-426a-b2ae-613461d5a0f1.png)

like:

![image](https://user-images.githubusercontent.com/11203929/234885599-15464f7d-946f-4b1b-8a5b-e3cc52e5d092.png)

**Comment by gao-sun** [comment]
thanks for reporting. will take a look soon

**Comment by charIeszhao** [comment]
It should be an acknowledged issue that introduced in v1.2.2. It was a pure frontend component bug, and should have nothing do to with "using two admin users at the same time". 

The bug was fixed 4 days ago. So please double check if it works in the latest v1.2.3, thanks.
