### ISSUE TITLE
bug: [SMTP]  Error in key path "connectionTimeout":

### ISSUE THREAD

**Issue by zuohuadong** [logto-io/logto#3784]
### Describe the bug

Error in key path "connectionTimeout":
(invalid type) Expected number but received null.Error in key path "greetingTimeout:(invalid type) Expected number but received nullError in key path "socketTimeout": (invalid type)Expected number but received null.Error in key path "dnsTimeout": (invalid type)Expected number but received null.

SMTP

### Context

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots
![image](https://user-images.githubusercontent.com/11203929/234906922-fce84e7f-2ab9-4027-8bb4-966f86768bdd.png)

       

     

try sendfrid :
![image](https://user-images.githubusercontent.com/11203929/234908254-78389c78-8664-4ad8-a122-cbc9e5fa8ea0.png)

![image](https://user-images.githubusercontent.com/11203929/234908212-1732ca1c-a3ac-43b6-ad27-1cc3e70583d7.png)

**Comment by gao-sun** [comment]
isn't this a network issue?

**Comment by zuohuadong** [comment]
@gao-sun 
I tried different providers and they all reported the same error. This setup is a bit tedious for stmp, and even I don't know if my setup is correct.

I think there should be a simplified version, just enter the domain name, port, username, password, whether SSL or not.

**Comment by JustMrMendez** [comment]
Having this problem too, i can't figure out the SMTP connector, it simply does not work no matter what do I put
