### ISSUE TITLE
bug: Return Button in Audit Logs and User Logs Does Not Navigate Back Correctly

### ISSUE THREAD

**Issue by QuintinShaw** [logto-io/logto#3827]
### Describe the bug

Upon entering any specific log in Audit Logs, the return button does not correctly return to the previous page. This issue also occurs in any log in User Management's User logs.

### Expected behavior

The return button should correctly bring users back to the previous page they were on before entering a specific log.

### How to reproduce?

1. Navigate to Audit Logs.
2. Click on any specific log to view its details.
3. Click the return button.
4. Notice that it does not bring you back to the Audit Logs page.
5. Repeat steps 1-4 for User Management's User logs.

### Context

- [x] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [x] Raw Node.js

### Screenshots

![Problem of Return Button](https://p2-img.bug.im/202305/520011a13f23e.png)

**Comment by xiaoyijun** [comment]
Hi @QuintinShaw , thanks for your report. This bug has been fixed in https://github.com/logto-io/logto/pull/3805, and this fix will be deployed in the next release.

**Comment by xiaoyijun** [comment]
fixes #3805
