### ISSUE TITLE
feature request: Passkey

### ISSUE THREAD

**Issue by ImSingee** [logto-io/logto#3876]
### What problem did you meet?

N/A

### Describe what you'd like Logto to have

Though it's not essential, it will be cool.

Since Google has started supporting [passkey](https://developers.google.com/identity/passkeys), passwordless will be the future. There are also some auth provider stars supporting it. I think the feature may be interesting for logto.

**Comment by charIeszhao** [comment]
The webauthn based passkey has been officially supported. Please check our documentation for more details.
https://docs.logto.io/docs/recipes/multi-factor-auth/webauthn/

**Comment by ImSingee** [comment]
@charIeszhao Love this! By the way, seems this (passkey/webauthn) can only be used as 2FA. Is it possible to make it as the only requirements (just like password)?
