### ISSUE TITLE
bug: AADSTS700016: Application with identifier '0f81b0aa-7d4f-4e39-b336-1717df0362c3' was not found in the directory 

### ISSUE THREAD

**Issue by AlgoLaser-Developer** [logto-io/logto#3956]
### Describe the bug

AADSTS700016: Application with identifier '0f81b0aa-7d4f-4e39-b336-1717df0362c3' was not found in the directory '默认目录'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

### Expected behavior

login from personal microsoft account by logto cloud

### How to reproduce?

![image](https://github.com/logto-io/logto/assets/135088029/b47f9c05-c3e6-4100-900d-523c6dd42ba4)
![image](https://github.com/logto-io/logto/assets/135088029/ab759df6-02df-42e7-8511-f3b7a3b5db8e)
![image](https://github.com/logto-io/logto/assets/135088029/b6b0322c-66ab-4385-9411-decb20ae725b)
![image](https://github.com/logto-io/logto/assets/135088029/ee414207-bc18-45d9-b1e2-39900bbe8aed)
![image](https://github.com/logto-io/logto/assets/135088029/5a4728b6-c8b7-4a54-adf8-8dca58e6b907)

### Context

- [x] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

**Comment by simeng-li** [comment]
Looks like an AAD config error. You may want to check your connector App settings.

**Comment by AlgoLaser-Developer** [comment]
> Looks like an AAD config error. You may want to check your connector App settings.

---
According to the error message, Azure suggests that I add the user's email to the OAuth user list in advance. However, my website is originally open for registration and I cannot add every new user to the OAuth user list in advance.
---

根据错误提示，azure 建议我将用户的邮箱提前加到 oauth 用户列表中，但是我的网站本来就是公开注册的，我不可能把每个新用户提前加入 oauth 用户列表。

**Comment by wangsijie** [comment]
What is your "Supported account types"?

**Comment by tipani86** [comment]
Based on github.com/logto-io/logto/issues/5651 if you are trying to use this on personal Microsoft accounts (i.e. hotmail, outlook, live etc.), you need to (quoting the linked issue):

> Use the value "consumers" as your Directory (tenant) ID, NOT you directory ID.
