### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by wesleysanjose** [logto-io/logto#3966]
### Describe the bug

successfully signed in but cannot get user info
Failed to load resource: the server responded with a status of 400 ()
index.js:26 Error: Unexpected response error from the server.
    at requester.js:9:1
    at async fetchTokenByAuthorizationCode (fetch-token.js:14:1)
    at async LogtoClient.handleSignInCallback (index.js:111:1)
    at async index.js:45:1
(anonymous) @ index.js:26
gd4zij.logto.app/oidc/me:1     Failed to load resource: the server responded with a status of 401 ()
index.js:26 Error: Unexpected response error from the server.
    at requester.js:9:1
    at async index.js:109:1
    at async Home.js:17:1
(anonymous) @ index.js:26
Home.js:18 Home.js userInfo undefined
gd4zij.logto.app/oidc/me:1     Failed to load resource: the server responded with a status of 401 ()
index.js:26 Error: Unexpected response error from the server.
    at requester.js:9:1
    at async index.js:109:1
    at async Home.js:17:1

### Expected behavior
user info can be fethced

### How to reproduce?
signin from my own react app
redirect to your cloud and signin using email+password
successfully signed in and redirect back to my react app

### Context
https://gd4zij.logto.app/sign-in
client is a react js application based on your react sample
when creating application in the cloud, i chose the SPD

- [x] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

**Comment by wesleysanjose** [comment]
there must be some bug in @logto/react 2.0.0, once i installed 1.1.2, it works now. i can see it prints out the table of user info.

**Comment by simeng-li** [comment]
https://docs.logto.io/docs/recipes/integrate-logto/react/#fetch-user-information 

Please check whether the scopes have been set properly. Also please provide a detailed response from the server.
