### ISSUE TITLE
服务器每次重新启动logto数据消失问题

### ISSUE THREAD

**Issue by yyh1413** [logto-io/logto#4121]
服务器上每次重新启动logto（docker compose up -d）之前录入的数据就消失了，需要重新注册重新填（跳转到register页面了）
本地环境是正常的数据一直在的
（我描述的清晰了 不清晰我会重新描述）
任何回答我都感激不尽

**Comment by charIeszhao** [comment]
<img width="974" alt="image" src="https://github.com/logto-io/logto/assets/12833674/7a98cc93-0692-4623-82c0-c0f056a532b1">

**Comment by charIeszhao** [comment]
If you still prefer docker compose, then you should modify the yml and save your data in a specified docker volumn

**Comment by yyh1413** [comment]
> 如果你仍然喜欢docker compose，那么你应该修改yml并将数据保存在指定的docker卷中

谢谢，非常感谢您的回答
