### ISSUE TITLE
bug: use docker deploy logto v1.6.0 will always redirect to /unknown-session 

### ISSUE THREAD

**Issue by terry-fei** [logto-io/logto#4151]
### Describe the bug
use docker deploy logto v1.6.0 will always redirect to /unknown-session 

### Expected behavior
not redirect

### How to reproduce?
with docker
```dockerfile
FROM svhd/logto:1.6.0

RUN npx logto c add @logto/connector-github \
  @logto/connector-google \
  @logto/connector-apple \
  @logto/connector-discord

ENV ENDPOINT=https://xxx.xxx.com
ENV TRUST_PROXY_HEADER=1
ENV DB_URL=xxx
ENV NODE_ENV=production
```

### Context

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

all path cover by isSessionRequiredPath will always redirect to /unknown-session
after dig i think it cause by
https://github.com/logto-io/logto/blob/master/packages/core/src/middleware/koa-spa-session-guard.ts#L35
always throw error

**Comment by gao-sun** [comment]
you need to set `ADMIN_ENDPOINT` to access console

**Comment by gao-sun** [comment]
https://docs.logto.io/docs/tutorials/get-started/#launch-logto

**Comment by terry-fei** [comment]
It works perfectly, thank you so much!
