### ISSUE TITLE
how to use multiple tenant in oss version ?

### ISSUE THREAD

**Issue by agileago** [logto-io/logto#4156]
https://github.com/logto-io/logto/blob/01557d6bcc9ee9b01c4485a12f3d84ed115ece67/packages/console/src/containers/AppContent/components/Topbar/index.tsx#L27

**Comment by gao-sun** [comment]
Currently, it is exclusively for Logto Cloud

**Comment by agileago** [comment]
in my company. it is a very very urgent need. now we deploy two logto to achieve this purpose. and it is boring

**Comment by agileago** [comment]
hope this feature as soon as up

**Comment by gao-sun** [comment]
you can use Logto Cloud, unfortunately this is not the scope of OSS
