### ISSUE TITLE
feature request: init local dev setup with data

### ISSUE THREAD

**Issue by Kyaak** [logto-io/logto#4240]
### What problem did you meet?
I want to setup a local dev environment and use docker compose for that, but I'm facing issues to recreate data on a new startup so I do not have to open the admin console manually and define everything again. Maybe I missed that somewhere in the docs?

For example:
- Create the initial admin user
- Define users and set passwords 
- Define applications with secrets and redirects

When I close my application and delete the db data, I have to recreate everything again manually, with different IDs and secrets etc. So I have to adjust my applications again. If I store the db data locally, they will still be different for other team members and therefore also not suitable.

I tried to insert users and link admin roles after logto was running with a depending container, but then I got permission issues with that and everything was mixed up. Still asking for the initial admin and this one is then not working anymore. Also exporting and adding oidc configuration in the db did not help.
Currently it is working with a complete db dump and applying that on db startup time, but I think this will not work very long as I saw expiration times and I dont know what happens when I hit that. Also not very handy to adjust.  

### Describe what you'd like Logto to have
I would love to have a configuration available to pass to logto startup, maybe even only when in development mode?
```yaml
admin:
  name:
  password:
users:
- name:
  email:
  password:
applications:
- name:
  type:
   ...
```
Or being able to define the api endpoint secret so you could authenticate here and use the api in a startup container.

I love the first impressions I got from logto - great work ❤️

**Comment by simeng-li** [comment]
Hi, thanks for choosing Logto. Yes, the docker-compose is for demonstration use only, it has a built-in Postgres database bundled together with the Logto app in docker-compose.yml, every time you re-execute the command a new database instance will be created, and any data persisted previously will be lost.
You will need to set up your local PostgreSQL DB and pull the docker image instead. Please refer to the [get started](https://docs.logto.io/docs/tutorials/get-started/) instruction for more details.

**Comment by Kyaak** [comment]
That's okay, my way to overwrite it, is working I think.
My question was about the ability to pass initial data to that first dev database setup, so it is not empty but filled with data I can directly use for local development.

**Comment by simeng-li** [comment]
I would recommend hosting your own DB for local development, as the docker-compose is not intended for long-term development use.
