### ISSUE TITLE
bug: Error code 500 (Internal Server Error) occurred during the signin callback step.

### ISSUE THREAD

**Issue by DarinRowe** [logto-io/logto#4262]
### Describe the bug
Server: Logto Cloud
Client: Next.js v13.4.12
            logto/next v2.1.2
Error code 500 (Internal Server Error) occurred during the Signin callback step In the production  Environment, but http://localhost:3000/ is working.

### Expected behavior

Login Success.

### How to reproduce?
Server: Logto Cloud
Client: Next.js v13.4.12
            logto/next v2.1.2
	  
Use Edge Runtime to Next.js SDK
```
import LogtoClient from "@logto/next/edge";

export const logtoClient = new LogtoClient({
  appId: process.env.LOGTO_APP_ID ?? "",
  appSecret: process.env.LOGTO_APP_SECRET ?? "",
  endpoint: process.env.LOGTO_ENDPOINT ?? "http://localhost:3001",
  baseUrl: process.env.LOGTO_BASE_URL ?? "http://localhost:3000",
  cookieSecret: process.env.LOGTO_COOKIE_SECRET ?? "",
  cookieSecure: process.env.NODE_ENV === "production",
});
```

```
import { type NextRequest } from "next/server";
import { logtoClient } from "@/app/api/logto";

export async function GET(request: NextRequest) {
  return logtoClient.handleSignInCallback()(request);
}

export const runtime = "edge";

```

### Context

- [x] Logto Cloud

### Screenshots
<img width="885" alt="Screenshot 2023-07-29 at 11 14 03 AM" src="https://github.com/logto-io/logto/assets/5706314/7baa1599-ad33-41bf-92b6-99f2262e5054">

**Comment by gao-sun** [comment]
I didn't see 500 logs in Logto Cloud - would you like to double check the Next.js log to see if there's an error?

**Comment by charIeszhao** [comment]
From the code provided I see you're using `localhost:3001` instead of the cloud endpoint URL. Could this be the reason?

**Comment by DarinRowe** [comment]
> I didn't see 500 logs in Logto Cloud - would you like to double check the Next.js log to see if there's an error?

```
Error: The callback URI mismatches the redirect URI.
11:05:08    at eU (file:///app/.next/server/app/api/logto/sign-in-callback/route.js:1:25768)
11:05:08    at tr.handleSignInCallback (file:///app/.next/server/app/api/logto/sign-in-callback/route.js:1:32346)
11:05:08    at async (file:///app/.next/server/app/api/logto/sign-in-callback/route.js:1:46081)
11:05:08    at async (file:///app/.next/server/app/api/logto/sign-in-callback/route.js:16:35700)
11:39:11Error: The callback URI mismatches the redirect URI.
11:39:11    at eU (file:///app/.next/server/app/api/logto/sign-in-callback/route.js:1:25768)
11:39:11    at tr.handleSignInCallback (file:///app/.next/server/app/api/logto/sign-in-callback/route.js:1:32346)
11:39:11    at async (file:///app/.next/server/app/api/logto/sign-in-callback/route.js:1:46081)
11:39:11    at async (file:///app/.next/server/app/api/logto/sign-in-callback/route.js:16:35700)
```

**Comment by DarinRowe** [comment]
> From the code provided I see you're using `localhost:3001` instead of the cloud endpoint URL. Could this be the reason?

Server Environment Variables.Login failed. 
```
LOGTO_ENDPOINT=https://xx.logto.app/
LOGTO_BASE_URL=<app-domain>
```

Local Environment Variables. Login successful.
```
LOGTO_ENDPOINT=https://xx.logto.app/
LOGTO_BASE_URL=http://localhost:3000
```

**Comment by wangsijie** [comment]
The 500 error is happend in Next.js, by default, the SDK's `handleSignInCallback` may throw error, you can catch it and handle properly, you can see all the error codes here: https://docs.logto.io/sdk/JavaScript/js/classes/class.LogtoError/

And the edge SDK reads url from `request.url`, so please check if your production environment is behind a reverse proxy. If so, please check the official example: https://github.com/vercel/examples/tree/main/edge-functions/hostname-rewrites

**Comment by DarinRowe** [comment]
> The 500 error is happend in Next.js, by default, the SDK's `handleSignInCallback` may throw error, you can catch it and handle properly, you can see all the error codes here: https://docs.logto.io/sdk/JavaScript/js/classes/class.LogtoError/
> 
> And the edge SDK reads url from `request.url`, so please check if your production environment is behind a reverse proxy. If so, please check the official example: https://github.com/vercel/examples/tree/main/edge-functions/hostname-rewrites

THX,

The error code of `handleSignInCallback` is `callback_uri_verification.redirect_uri_mismatched`

I found that the value of `request.url` is `http://deployment-64c7756a49500b0c3171ef42-6b5df7bd8-8822m:3000/api/logto/sign-in-callback?code=wSt3OJ7M5A-eo_N0JxzHees9sFPBvZxOFPdV9ia_ZuN&state=7IaLKK2sZW1unlK4Uj9B3ejXku5-0GQZ0uNM0_a0lv0MI6zzTOdP94bVXQ2HOxc216tXDG0hZmfzFKQ5l8MbJA&iss=https%3A%2F%2Fk.logto.app%2Foidc`

**Comment by wangsijie** [comment]
@DarinRowe The value should match `baseUrl`, if the app is behind a reverse proxy (like Nginx or Ingress), please add a middleware to handle the mismatch urls, check the official example: https://github.com/vercel/examples/tree/main/edge-functions/hostname-rewrites

**Comment by DarinRowe** [comment]
> @DarinRowe The value should match `baseUrl`, if the app is behind a reverse proxy (like Nginx or Ingress), please add a middleware to handle the mismatch urls, check the official example: https://github.com/vercel/examples/tree/main/edge-functions/hostname-rewrites

OK, I have fixed it. 

It may be Next.js bug. The value of`request.headers.get("host")`is `<app-domain>`, but the value of `request.url` is `http://deployment-64c897cad86fff:3000/api/logto/sign-in-callback?code=...`

**Comment by wangsijie** [comment]
Thanks for the feedback, I'll take a look at the two values.

**Comment by wangsijie** [comment]
Thanks for the feedback, feel free to reopen if you have any further questions.
