### ISSUE TITLE
bug: use docker deploy logto v1.6 will always redirect to /unknown-session

### ISSUE THREAD

**Issue by TheresaQWQ** [logto-io/logto#4279]
### Describe the bug

bug: use docker deploy logto v1.6.0 will always redirect to /unknown-session

### Expected behavior

not redirect

### How to reproduce?

![image](https://github.com/logto-io/logto/assets/22370654/f6cd651e-fc5a-4943-a21f-e0053236af3e)
![image](https://github.com/logto-io/logto/assets/22370654/0319034c-2ded-4a87-ba58-807f87adfa40)
![image](https://github.com/logto-io/logto/assets/22370654/cc6e6612-c8ab-4829-bd76-5ec1abcaf96c)

Just like in the screenshot above.

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = v1.6
  - [x] Container (Docker image)
  - [ ] Raw Node.js

**Comment by TheresaQWQ** [comment]
Some Logs:
![image](https://github.com/logto-io/logto/assets/22370654/03cd7173-90fb-4c19-a2fc-67842e37afc3)

**Comment by xiaoyijun** [comment]
Hi @TheresaQWQ , I'm quite curious about why you're using curl to access the auth endpoint.
Authentication-related requests rely on the browser's session, and it's recommended to perform authentication using a web browser.
Logto offers a variety of SDKs and guides that helps you integrating Logto into your application.
https://docs.logto.io/docs/recipes/integrate-logto/

**Comment by leopku** [comment]
Same issue by logto 1.7 + docker compose + nginx proxy manager.
ENV had set. as below

```
RUST_PROXY_HEADER=1
ENDPOINT=https://logto.local.dev
ADMIN_ENDPOINT=https://admin-logto.local.dev
```

**Comment by petarordanoski** [comment]
Same issue here. I've been trying to make this work all day long. I'm using latest logto + docker run + nginx proxy manager.

**Comment by vordan** [comment]
Oh, well, time to look for another authentication server... :(

**Comment by charIeszhao** [comment]
> Same issue by logto 1.7 + docker compose + nginx proxy manager.
> ENV had set. as below
> 
> ```
> RUST_PROXY_HEADER=1
> ENDPOINT=https://logto.local.dev
> ADMIN_ENDPOINT=https://admin-logto.local.dev
> ```

The first env should be `TRUST_PROXY_HEADER` instead of RUST

**Comment by charIeszhao** [comment]
> Same issue here. I've been trying to make this work all day long. I'm using latest logto + docker run + nginx proxy manager.
> 
> 

Can you share your nginx config with us?

**Comment by wangsijie** [comment]
Hi guys, as you are using "https" and reverse proxy, according to the offical [doc](https://docs.logto.io/docs/recipes/deployment/#reverse-proxy), you should add `X-Forwarded-Proto` to your reverser proxy server.

```
proxy_set_header X-Forwarded-Proto https;
```

**Comment by TheresaQWQ** [comment]
> Hi guys, as you are using "https" and reverse proxy, according to the offical [doc](https://docs.logto.io/docs/recipes/deployment/#reverse-proxy), you should add `X-Forwarded-Proto` to your reverser proxy server.
> 
> ```
> proxy_set_header X-Forwarded-Proto https;
> ```

I have set all the headers mentioned in the documentation, and updated to latest version in dockerhub (1.9.0), I still got same error

**Comment by TheresaQWQ** [comment]
I tried requesting `localhost:3002` in a Docker container using curl and it looks like it works fine, it seems to be a problem only when using docker port forwarding
![image](https://github.com/logto-io/logto/assets/22370654/94472ecb-ea46-4f0e-b353-5a230d506c4d)

**Comment by wangsijie** [comment]
Could you try a http domain?

**Comment by TheresaQWQ** [comment]
> Could you try a http domain?

![image](https://github.com/logto-io/logto/assets/22370654/db4fbebd-0cbd-456d-9a37-52ab1318f7d1)

**Comment by wangsijie** [comment]
And it matches `ADMIN_ENDPOINT`?

**Comment by TheresaQWQ** [comment]
> And it matches `ADMIN_ENDPOINT`?

yes, It matches `ADMIN_ENDPOINT`.

**Comment by wangsijie** [comment]
@TheresaQWQ Can you share your Logto's env config and nginx config? In the screenshot, it seems that Logto is configured to a https endpoint.

**Comment by TheresaQWQ** [comment]
> @TheresaQWQ Can you share your Logto's env config and nginx config? In the screenshot, it seems that Logto is configured to a https endpoint.

I'm using Caddy, and my env config is above

env:
```
ADMIN_ENDPOINT=https://auth-admin.local.dev/
ADMIN_PORT=43002
DB_URL=postgres://logto:logto@127.0.0.1:45134/logto
ENDPOINT=https://auth.local.dev/
PORT=43001
TRUST_PROXY_HEADER=1
```

Caddyfile:
```
auth.local.dev {
  reverse_proxy http://127.0.0.1:43001 {
    trusted_proxies private_ranges
  }
}

auth-admin.local.dev {
  reverse_proxy http://127.0.0.1:43002 {
    trusted_proxies private_ranges
  }
}
```

**Comment by wangsijie** [comment]
@TheresaQWQ You can refer to this doc, and add `X-Forwarded-Proto` https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults

**Comment by Mohdsaleh939** [comment]
Any updates on this issue ? 
We are still blocked from installing Logto tool and got the same issue mentioned above.

**Comment by wangsijie** [comment]
@Mohdsaleh939 Is your Logto container behind a reverse proxy? Follow this [doc](https://docs.logto.io/docs/recipes/deployment/#reverse-proxy) to add X-Forwarded-Proto to your reverser proxy server.

**Comment by heng4fun** [comment]
I use the AWS alb ingress with https, got the same issue.

**Comment by wangsijie** [comment]
@heng4fun can you please share more details? especially the ingress configs

**Comment by JackyTYang** [comment]
> I use the AWS alb ingress with https, got the same issue.

me too，and i don't know where and how can I set the header like x-forwarded-proto in alb console

**Comment by JackyTYang** [comment]
> @heng4fun can you please share more details? especially the ingress configs

This is my ingress yaml. heng4fun is with me.
`apiVersion: [networking.k8s.io/v1](http://networking.k8s.io/v1)
kind: Ingress
metadata:
  annotations:
    [alb.ingress.kubernetes.io/scheme](http://alb.ingress.kubernetes.io/scheme): internet-facing
    [alb.ingress.kubernetes.io/target-type](http://alb.ingress.kubernetes.io/target-type): ip
    [kubernetes.io/ingress.class](http://kubernetes.io/ingress.class): alb
    meta.helm.sh/release-name: xxx
    meta.helm.sh/release-namespace: xxx
  creationTimestamp: "2023-12-22T06:14:50Z"
  finalizers:
  - ingress.k8s.aws/resources
  generation: 11
  labels:
    [app.kubernetes.io/managed-by](http://app.kubernetes.io/managed-by): Helm
    [app.kubernetes.io/version](http://app.kubernetes.io/version): v0.2.3
spec:
  ingressClassName: alb
  rules:
  - host: [logto.domain.com](http://logto.kubeblocks.com/)
    http:
      paths:
      - backend:
          service:
            name: my-logto-admin
            port:
              number: 3002
        path: /
        pathType: Prefix
  - host: [login.domain.com](http://login.kubeblocks.com/)
    http:
      paths:
      - backend:
          service:
            name: my-logto-core
            port:
              number: 3001
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: [k8s-xxx-191776302a-289611912.us-west-2.elb.amazonaws.com](http://k8s-kbcloud-kubebloc-191776302a-289611912.us-west-2.elb.amazonaws.com/)`

**Comment by JackyTYang** [comment]
I want to make sure that logto can only support https, not http? If  the x-forwarded-proto = "http", then it will redirect to unknown-session, right? So I need to make sure x-forwarded-proto= "https" is passed to the backend of logto then it will work.

**Comment by JackyTYang** [comment]
Solved，I added https 443 monitor to AWS ALB in which router rules are configed.

**Comment by wangsijie** [comment]
Logto employs a rigorous URL validation process that mandates the "https" protocol. This stringent requirement can lead to complications in environments based on reverse proxies. Configurations such as 'x-forwarded-proto' can mitigate these issues. However, we recognize that these solutions might not be straightforward for all users, particularly those new to Logto. In light of this, we are actively exploring options to allow the disabling of this strict URL check to facilitate a smoother initial setup experience. Please stay tuned for updates.

**Comment by yixinBC** [comment]
So any solusion to use logto with docker on development machine.
I mean,HTTP connnection on localhost.

**Comment by wangsijie** [comment]
@yixinBC You can set ADMIN_ENDPOINT to `http://localhost:3002`

**Comment by yixinBC** [comment]
> @yixinBC You can set ADMIN_ENDPOINT to `http://localhost:3002`

@wangsijie actually ADMIN_ENDPOINT on http://localhost:3002 works just fine.But when I tried to browse  http://localhost:3001/ ,I'm just redirected to http://localhost:3001/unknown-session everytime.I'm sorry I havn't clarify.

**Comment by ciphermenial** [comment]
I am experiencing this issue too. I can access admin fine but anytime I go to logto.example.net I receive unknown-session.

I installed Logto using npm-init in an LXC container.

This is how traffic flows from Cloudflare, through HAProxy, to the web server.

```mermaid
graph TD
 EU[/External User\] -."http://logto.example.net".-> CF[Cloudflare]
 CF -.-> FE_HTTPS
 IU[/Internal User\] --"http://logto.example.net"--> FE_HTTP[HTTP Frontend]
 subgraph HAProxy
 FE_HTTPS -- "Internal User?" --> INT[Internal Backend]
 FE_HTTP --> FE_HTTPS[HTTPS Frontend]
 EXT -.-> FE_EXT[External Frontend]
 INT --> FE_INT[Internal Frontend]
 FE_HTTPS -. "External User?" .-> CS_DEC[(CrowdSec Decision)]
 subgraph CrowdSec
 CS_DEC ==Require CAPTCHA==> CS_CAPTCHA[CAPTCHA Page]
 CS_DEC ==Banned IP==> CS_BAN[Ban Page]
 CS_CAPTCHA ==CAPTCHA failed==> CS_DEC
 CS_DEC ==Captcha Remediated==> EXT[External Backend]
 end
 end
 CS_DEC -.Not In Decisions.-> EXT
 FE_EXT -.-> S[Web Service]
 FE_INT --> S
```
I have `http-request set-header x-forwarded-proto https` in the frontend configuration.

**Comment by JackyTYang** [comment]
Https is a must

**Comment by ciphermenial** [comment]
It seems this issue is universal. I have now tested using localhost and still get sent to unknown-session for the login. Admin page works fine.

**Comment by wangsijie** [comment]
@ciphermenial thanks for the detailed feedback, I'll revisit this issue.

**Comment by ciphermenial** [comment]
I should mention that I could log into the demo-app.

**Comment by wangsijie** [comment]
@ciphermenial Access to the default endpoint requires initiating the sign-in flow with OIDC tools, like our SDKs. Without this, you will be redirected to an "unknown session" page.

**Comment by wangsijie** [comment]
@fleuraly I think we can add some tips to the "unknown session" page?

**Comment by wangsijie** [comment]
I am closing this issue, the reason is that you can not access the OIDC sign in endpoint directly. Feel free to reopen if you guys have any other questions.

**Comment by PeterChen1997** [comment]
same problem. the doc should notice the user if they set the reverse proxy...

**Comment by clhey** [comment]
> I tried requesting `localhost:3002` in a Docker container using curl and it looks like it works fine, it seems to be a problem only when using docker port forwarding ![image](https://private-user-images.githubusercontent.com/22370654/269286494-94472ecb-ea46-4f0e-b353-5a230d506c4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjA5ODgsIm5iZiI6MTcxNDM2MDY4OCwicGF0aCI6Ii8yMjM3MDY1NC8yNjkyODY0OTQtOTQ0NzJlY2ItZWE0Ni00ZjBlLWIzNTMtNWEyMzBkNTA2YzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAzMTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxM2ZkMjA0NWFjYzU4OWE1N2Y1NTcyMGM0YTdhNmM0MWZhOTcwMTJhYTdkOGUwYTFlNjRmMjQ2MDQ3ZTA4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KzEFaFtUmCfAX65oVkSrfSUICNz88Yo0Gh9S9NKybPw)

I have the same setup, with all headers configured according to the documentation (https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults), and I've verified through actual testing that the headers are working properly. Can anyone help solve this issue?

I suspect that logto only allows requests from http://localhost:3002/ and the specified ADMIN_ENDPOINT for security reasons. My ADMIN_ENDPOINT is similar to https://user.example.com:8443/. Does logto only support port 443?

![image](https://github.com/logto-io/logto/assets/7664669/34286f3c-7aa7-416b-a5ee-1337e034140b)

**Comment by adrianwnuk** [comment]
Unable to run with use nginx ingress on kubernetes. Same output like above "unknown-session"

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-logto
  namespace: logto
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - logto.logto.domain.com
    secretName: logto-domain-com-tls
  rules:
  - host: logto.domain.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: logto-core
            port:
              number: 3001
      - pathType: Prefix
        path: "/admin"
        backend:
          service:
            name: logto-admin
            port:
              number: 3002
```

**Comment by WooodHead** [comment]
I encountered the same "unknown-session" issue. The solution was to open xxxx.logto.app and clear all cookies in the browser console, which resolved the problem.

**Comment by nqcuong72** [comment]
Add environment setting: 'HOST=0.0.0.0' will solve the problem

**Comment by jagyas** [comment]
I am using traefik proxy. After setting **TRUST_PROXY_HEADER** to **true**, at least I am able to access admin.

**Comment by AndrewCollectGroup** [comment]
@jagyas Worked for me, thank you!

**Comment by aaron-wala** [comment]
I use traefik v3.4.4, this is the configuration that works for me:
`entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true`

Pay attention to
forwardedHeaders:
    insecure: true

**Comment by diepnghitinh** [comment]
I use traefik v3.4.4, this is the configuration that works for me:
```
entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
```

Pay attention to
forwardedHeaders:
    insecure: true
