### ISSUE TITLE
bug: OAuth Connector depends on User Info Endpoint which return special response

### ISSUE THREAD

**Issue by davideuler** [logto-io/logto#4295]
### Describe the bug
When I configure OAuth 2.0 connector for Alibaba Cloud. It failed, shows 400 error. 
After start logto by pnpm dev, and inspecting the code.

Finally that I found the oauth connector assumed that oauth User Info Endpoint will respond result contains attribute of "id". 
But it is not the case for many standard oauth implementations.  The User Info api response format is not defined in the standard.

RFC6749: ```https://datatracker.ietf.org/doc/html/rfc6749```

Get user Info in auth0:  ``` https://auth0.com/docs/api/authentication#get-user-info ```

### Expected behavior
Whatever format get user info response from the oauth 2.0 connector. It should works.

### Context
Both Docker environment, and local dev environment. svhd/logto:1.7.0, and the latest branch.

- [ ] Self-hosted,  Logto version = Latest, 7ce014d0337f95b73285cb52ee0e723697cebf79
  - [ ] Container svhd/logto:1.7.0
  - [ ] Raw Node.js v18.12.1

**Comment by darcyYe** [comment]
It's important to clarify that the `userinfo` endpoint isn't defined with a specific response format in the OAuth 2.0 protocol. Different social identity providers may have varying response structures, which means that there isn't a notion of standardized implementation, as I understand it.
Additionally, the `sub` claim you mentioned is standardized within the OIDC protocol (which is built upon OAuth 2.0), but such a standard doesn't exist within OAuth 2.0.
Moreover, the purpose of Logto social connectors is to acquire the required user profile from a social identity provider in the format required by Logto. This is achieved through user authorization, obtaining the necessary user profile data to meet the usage requirements of Logto's core functionality.

Back to your question, you can use the `Profile Map` field to map the response from your desired social identity provider userinfo endpoint to the Logto-favored format.

**Comment by davideuler** [comment]
Thanks for the detailed reply. Yes, I didn't realized that Profile Map can be configured in the OAuth 2.0 Social Connectors.
After I configured the Profile Map, it works. It's cool. Thank you guys.

**Comment by darcyYe** [comment]
Maybe we did not make that clear enough in the doc, will revisit it 😁
