### ISSUE TITLE
bug: i18n support

### ISSUE THREAD

**Issue by privacyrepo** [logto-io/logto#4405]
### Describe the bug

I have the structure of app/[lang]/(pages)/api/logto/sign-in-routes.ts

no matter what url I have tried to access, it's always 404, like localhost:3000/api/logto/sign-in   or localhost:3000/en/api/logto/sign-in

I'm currently having a working authentication with username and password, I want to use logto, but my site is multiple language, so I have no clue how to get this works, anyone can help? Thank you.

### Context

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

**Comment by simeng-li** [comment]
Hi thanks for your question. 

First of all, please to remind give a suitable title for your issue. This will help both the maintainer and our community members gain immediate insights into the nature of your concern.

There are couple of things need to check with you:

- How do you serve your Logto server instance?  
- `/api/logto/sign-in` is definitely not a valid endpoint, that is why you received a 404 response. Have you checked our integration guide?
- On the other hand, we do have i18n supported as an out-of-the-box feature. Please checkout the [doc](https://docs.logto.io/docs/recipes/customize-sie/localized-language/) for more details.

**Comment by charIeszhao** [comment]
Can you update your config when you initiate LogtoClient?
The router path is actually concatenated by `${config.baseUrl}/api/logto/sign-in` in next.js SDK. So it seems you can just update your baseUrl config everytime you switch to a new language, and refresh the page to initiate a new LogtoClient.

**Comment by charIeszhao** [comment]
Due to the inactivity of more than 80 days, I'm closing the ticket. Currently Logto does not support URL route based i18n, and we use the `react-i18n` under the hood to detect and select languages.
Please feel free to let us know if you want to reopen the issue. Thanks!
