### ISSUE TITLE
bug: alterations dont work in 1.8 and 1.7

### ISSUE THREAD

**Issue by tobiasschulz** [logto-io/logto#4411]
### Describe the bug

Deploying the DB alterations inside a docker image does not work, neither in version 1.8 or 1.7 (i only tested those two)

```
> alteration
> logto db alt deploy latest

info Deploy target 1.7.0
info Found 75 alterations to deploy
info Run alteration 1.0.0_beta.10-1-logto-config.js `up()` function succeeded
error error: type "application_type" does not exist
    at Parser.parseErrorMessage (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 99,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_type.c',
  line: '270',
  routine: 'typenameType',
  notices: []
}
fatal Error ocurred during running alteration 1.0.0_beta.10-1663923211-machine-to-machine-app.js.

  This alteration didn't change anything since it was in a transaction.
  Try to fix the error and deploy again.
```

### Expected behavior
There should be no error.

### How to reproduce?

Run a container with the image svhd/logto:1.7, svhd/logto:1.8 or ghcr.io/logto-io/logto (happens with all of them)
and execute the following command inside:
`npm run alteration deploy latest`

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 1.8 and 1.7
  - [x] Container (Docker image)
  - [ ] Raw Node.js

**Comment by simeng-li** [comment]
Hi looks like your base DB version is way too old to pick-up the alteration files. Even older than the beta version alterations.  Any DB updates beyond our db alteration scripts are not trackable. I would recommend you to seed a brand new DB using the the latest stable Logto docker.  

If you stay with your current DB, just to help you pass this specify error, you could try adding the the missing `application_type ` in your db by running the following query:

```sql
create type application_type as enum ('Native', 'SPA', 'Traditional');
```

**Comment by tobiasschulz** [comment]
Hi,

The DB can't bei old, it's empty. 

So what do i need to do when initializing the container, first seed and then apply the alterations?

I get that you want to get people to use the cloud service, but it would be really nice to have one complete example for a kubernetes deployment that actually works 😁

**Comment by simeng-li** [comment]
Oh, I see. `logto db alt deploy`  is for old version DB alteration use only. 
Use `logto db init` instead to initiate and seed your brand new DB.

**Comment by simeng-li** [comment]
Also, we do have a [Get started guide](https://docs.logto.io/docs/tutorials/get-started/#open-source) provided, you cloud follow on that. Let us know if there are anything else that still confuse you.

**Comment by tobiasschulz** [comment]
Ok, now there is another problem. I'm on version 1.8. "db seed" and then "db alteration deploy latest" worked. But when I try starting the container:


```> start
> cd packages/core && NODE_ENV=production node .

(node:16) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
warn [CACHE] No Redis client initialized, skipping
error Error while initializing app:
error Error: Row-level security has to be enforced on EVERY business table when starting Logto.
Found following table(s) without RLS: _logto_configs

Did you forget to run `npm cli db alteration deploy`?
    at checkRowLevelSecurity (file:///etc/logto/packages/core/build/tenants/utils.js:47:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async file:///etc/logto/packages/core/build/index.js:24:5
npm notice 
```

**Comment by simeng-li** [comment]
First of all, running the db seed will do all the works, you don't need to run the db alteration script again. 

Looks like you have a legacy `_logto_configs` table exist in your DB. Probably because you tried to run the db alteration at the first time.  
Simply drop the `_logto_configs` table should remove this error.

**Comment by charIeszhao** [comment]
Hi @tobiasschulz, just checking with you if your issue has been resolved? Has the instructions provided by Simeng worked for you?

**Comment by simeng-li** [comment]
Inactive for more than 30 days. Closed for now.
