### ISSUE TITLE
feature request: Setting signature algorithm HS256 or RS256 as needed

### ISSUE THREAD

**Issue by shalom-lab** [logto-io/logto#4452]
When I used Authing as ID provider for an [shinyproxy](https://www.shinyproxy.io/documentation/configuration/#openid-connect-oidc) application, I can select HS256 or RS256 as the signature algorithm of id_tokens. HS256 works for shinyproxy, but RS256 will fail.
I can not find how to select the signature algorithm in Logto. And here is the error:
```
OpenIDAuthenticationBackend    : org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_id_token] An error occurred while attempting to decode the Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found

```

**Comment by xiaoyijun** [comment]
Hi @shalom-lab, thank you for your feedback.
Currently, we are actively considering this feature in our plans, and @wangsijie is conducting relevant research. We will keep you updated as soon as there is any progress.

**Comment by charIeszhao** [comment]
@shalom-lab Can you please elaborate more on the "HS256 works for shinyproxy, but RS256 will fail"?
Can you find any documentation that listed what algorithms are supported by shinyproxy? I did some search but didn't seem to find anything on their documentation site

**Comment by shalom-lab** [comment]
Here is the github repository for shinyproxy,[https://github.com/openanalytics/shinyproxy/tree/master](https://github.com/openanalytics/shinyproxy/tree/master). I meet the same "decode the Jwt fail "error when I use the default setting in Authing in the past. After I modified the setting from RS256 toHS256, my shinyproxy application worked. How to select algorithm like this in Logto?
![image](https://github.com/logto-io/logto/assets/49271035/9a898762-33b5-435f-8424-6ef33e06fa40)
Hope this will help you.

**Comment by charIeszhao** [comment]
If you are using open source version, you can now use a CLI command to rotate your current oidc private key as well as the signing algorithm. E.g.
```
npm run cli db config rotate oidc.privateKeys -- --type=rsa
```

We are also working on a new feature update to provide this config for Logto Cloud users in admin console.

**Comment by shalom-lab** [comment]
Nice, looking forward to setting this in the admin console.

**Comment by charIeszhao** [comment]
Hi @shalom-lab, the feature is now available on Logto Cloud as well. Cloud users can go to "Settings -> SIGNING KEYS" to manage their keys for their tenant

<img width="1455" alt="image" src="https://github.com/logto-io/logto/assets/12833674/fdb7be37-3b70-47f7-a3a8-4f56cbc154d7">
