### ISSUE TITLE
feature request: Allow extending refresh token TTL for SPA

### ISSUE THREAD

**Issue by charIeszhao** [logto-io/logto#4520]
### What problem did you meet?

For enhanced safety, in Logto the refresh token has a fixed TTL (Time-to-Live) for SPAs (Single Page Applications). By default, the refresh token TTL is 14 days, and the admin user can always configure it in application details page in admin console. But the maximum value is limited to no longer than 90 days. The refresh token TTL will not be extended during refresh token rotation.

However, due to this, even though the admin has configure the refresh token TTL to 90 days, the SPA end users will experience a "force logout" after they first signed in to the app 90 days ago, no matter if they are still using it on the 89th day.

Some applications that don't have a high safety demand don't actually want to have this behavior. Therefore, it'll be nice to have another config/switch in the admin console, to allow the admin to disable this feature and allow refresh token TTL to extend (like up to 1 year or forever) during refresh token rotation.

### Describe what you'd like Logto to have

- Provide a "Renew refresh token TTL on token rotation" switch field in application details page in Admin Console.
- The default value should be "off", and thus the refresh token TTL does not extend on rotation.
- If user turn on the switch, refresh token TTL should be renewed on each rotation.
- Optional: consider adding a hard cap to refresh token TTL, like up to one year. This is also the default behavior of the refresh tokens for other application types (native and traditional web)

**Comment by charIeszhao** [comment]
Closing the ticket due to inactivity

**Comment by leoshusar** [comment]
Hi @charIeszhao, I think I'm currently running into this issue. I'm building some private / internal Flutter SPA apps and I was debugging why I'm getting logged out with an expired refresh token after a few days, even though my tokens are rotated.

Do I understand this correctly, even if I have `Rotate refresh token` enabled, and the TTL is set to 14 days, the new rotated refresh token will not have 14 days TTL? So the user will be force logged-out after 14 days even if the token was rotated on the 12th day?

If yes - can you please reconsider this feature request?

**Comment by SongRongLee** [comment]
Filed #8779 from the docs angle — same misread as @leoshusar above. That "enhance user experience" line really does push SPA devs into thinking rotation extends TTL. Hoping a fresh issue helps bump this!
