### ISSUE TITLE
bug: Unable to seed database on Neon

### ISSUE THREAD

**Issue by sorenhansendk** [logto-io/logto#4535]
### Describe the bug
I'm trying to seed the Logto database on [neon.tech](https://neon.tech/)'s managed Postgres platform, but that is not possible, due to a empty password on a role, I think gets created in the seed phase.

<pre>
> cli
> logto db seed

[info] ✔ Create tables
info [default] Generated config oidc.privateKeys
info [default] Generated config oidc.cookieKeys
info ✔ [default] Seed OIDC config
info [admin] Generated config oidc.privateKeys
info [admin] Generated config oidc.cookieKeys
info ✔ [admin] Seed OIDC config
info ✔ Cloud Service Application successfully created for: default
info ✔ Seed data

error error: Received HTTP code 400 from control plane: {"error":"Neon does not support roles with empty passwords"}
  at Parser.parseErrorMessage (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
  at Parser.handlePacket (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
  at Parser.parse (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
  at TLSSocket.<anonymous> (/etc/logto/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
  at TLSSocket.emit (node:events:514:28)
  at addChunk (node:internal/streams/readable:324:12)
  at readableAddChunk (node:internal/streams/readable:297:9)
  at Readable.push (node:internal/streams/readable:234:10)
  at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 189,
    severity: 'ERROR',
    code: 'XX000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'control_plane_connector.c',
    line: '276',
    routine: 'SendDeltasToControlPlane'
  }
</pre>

My connection string looks like this:

<pre>
postgres://[username]:[password]@ep-crimson-flower-88570255.eu-central-1.aws.neon.tech/logto?sslmode=require
</pre>

### Expected behavior
Able to seed the database and test it.

### How to reproduce?

1. Create a new user: https://console.neon.tech
2. Create new project with version 15 of Postgres
3. Copy the connection string from the neon.tech UI
4. Set `DB_URL` in [`docker-compose.yml`](https://github.com/logto-io/logto/blob/master/docker-compose.yml)
5. Add `?sslmode=require` in end of the connection string
6. Run `docker compose up` and wait for the seed error

### Context

- [x] Self-hosted, Logto version = 1.8.0
  - [x] Container (Docker image)

**Comment by charIeszhao** [comment]
Interesting, we're fully occupied at the moment but this could be a good first issue for someone to contribute in the upcoming Hacktoberfest. Would you like to give it a try?

**Comment by gao-sun** [comment]
@charIeszhao I'm not sure if it's related to encrypting, worth deep dive though.

**Comment by charIeszhao** [comment]
> @charIeszhao I'm not sure if it's related to encrypting, worth deep dive though.

Yeah, need to investigate the root cause first. But the error message is a good lead: `"Neon does not support roles with empty passwords"`
