### ISSUE TITLE
feature request: Electron SDK

### ISSUE THREAD

**Issue by simeng-li** [logto-io/logto#4541]
### Introduction
Logto offers a wide range of SDKs for various platforms, including Next, React, iOS, Android, etc. However, we acknowledge that there are still numerous uncharted platforms and frameworks beyond our current scope. We are looking forward to your contribution to help us implement the SDKs for these missing platforms.

### Describe what you'd like Logto to have

Develop an SDK for [Electron Apps](https://www.electronjs.org/).

**Basic requirements:**
1. Implement an SDK following our [SDK Convention](https://docs.logto.io/docs/references/sdk-convention/)
2. Implement a sample app for demonstration using this SDK.  
3. Use the package name: `@logto/electron`

**Resources**
- [Set up Logto](https://docs.logto.io/docs/tutorials/get-started/): The instruction guide that helps you quickly set up Logto locally. 
- [Logto SDK convention](https://docs.logto.io/docs/references/sdk-convention/): Our SDK design conventions. 
- [Logto js SDKs](https://github.com/logto-io/js): Existing js SDKs.
- [Logto js client package](https://github.com/logto-io/js/tree/master/packages/client): The base Logto client class module for all js based SDKs. 
- [Integrate Logto using SDK](https://docs.logto.io/docs/recipes/integrate-logto/): The instruction guide of using a Logto SDK

**Comment by gao-sun** [comment]
Cool, go for it
