### ISSUE TITLE
feature request: Support 'unix domain sockets'-formatted DB_URL

### ISSUE THREAD

**Issue by darcyYe** [logto-io/logto#4546]
### What problem did you meet?

Logto uses [Slonik](https://github.com/gajus/slonik#user-content-slonik-query-building-sql-array) to establish PostgreSQL database connections. To set up the connection, simply configure the DB_URL with the PostgreSQL DSN connection string (see [Logto docs](https://docs.logto.io/docs/references/core/configuration/#variables)).

In our community, some individuals use a local host-based database and wish to establish a database connection using a Unix domain socket. We can check whether the DB_URL is in the form of a DSN or a Unix domain socket when reading it and establishing the database connection. Then, we can handle the DB_URL accordingly and create the appropriate database connection.

### Describe what you'd like Logto to have

Can configure Logto environment variable DB_URL in UNIX domain sockets format and Logto should be able to automatically parse it and build DB connection.

**Comment by charIeszhao** [comment]
Closing the ticket due to inactivity
