### ISSUE TITLE
feature request: Google Cloud Storage provider

### ISSUE THREAD

**Issue by wangsijie** [logto-io/logto#4552]
### What problem did you meet?

Logto has the ability to customize [storage provider](https://docs.logto.io/docs/recipes/configure-storage-providers/) for large size assets, but it only supports Azure Storage and AWS S3, Google [Cloud Storage](https://cloud.google.com/storage) is not on the list.

### Describe what you'd like Logto to have

New storage provider for Google Cloud Storage.

### Resources

1. Official doc for provider: https://docs.logto.io/docs/recipes/configure-storage-providers/
2. Azure Storage implementation: https://github.com/logto-io/logto/blob/master/packages/core/src/utils/storage/azure-storage.ts
3. S3 implementation: https://github.com/logto-io/logto/blob/master/packages/core/src/utils/storage/s3-storage.ts
4. Google Cloud SDK for Node.js: https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-nodejs

**Comment by hussainshaikh12** [comment]
Hey @wangsijie can you assign this to me

**Comment by wangsijie** [comment]
> Hey @wangsijie can you assign this to me

It's done, looking forward to your PR
