### ISSUE TITLE
feature request: Guard text inputs for `CustomHeaderField` component

### ISSUE THREAD

**Issue by xiaoyijun** [logto-io/logto#4557]
### What problem did you meet?

In Logto, there is an input component (`CustomHeaderField`) for editing HTTP headers.
This component does not impose any constraints on the input content and the content is only guarded by the backend APIs:

![image](https://github.com/logto-io/logto/assets/10806653/d0a05a5f-f2a5-4c48-b0c8-1d0bc98587a9)

### Describe what you'd like Logto to have

We would like to adhere to the [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#section-5) and improve our input component to validate and check for invalid inputs. The error reporting should be displayed in the following format:

![image](https://github.com/logto-io/logto/assets/10806653/29f904c4-77a6-43cf-9ae3-8de38c173488)

**Comment by hussainshaikh12** [comment]
Hey @xiaoyijun i would love to work on this issue

**Comment by xiaoyijun** [comment]
Hi, @hussainshaikh12 , thank you for your interest in our project!
You just need to submit the relevant pull request to participate in our activities :)
