### ISSUE TITLE
feature request: Support searching on the `Select` component

### ISSUE THREAD

**Issue by xiaoyijun** [logto-io/logto#4558]
### What problem did you meet?

In Logto, there is a `Select` component:

![image](https://github.com/logto-io/logto/assets/10806653/04ed79f7-9981-4873-b3f0-cf3132a6fcdf)

When the `Select` contains a large number of options, it becomes difficult for users to find the option they are looking for.

### Describe what you'd like Logto to have

We would like to have a search feature for the `Select` component, allowing users to input some text to match relevant options, this feature can be enabled/disabled by an `isSearchEnabled` prop.
In Logto, there is already an implementation of an `AddLanguageSelector` that supports searching.
However, this selector is an early temporary solution.
We need to directly implement search functionality on the `Select` component to replace the old `AddLanguageSelector`.
The `AddLanguageSelector` component is as follows:

![image](https://github.com/logto-io/logto/assets/10806653/f7030935-b5bb-4759-b57c-b5ee8b94583c)

**Comment by akarsh-jain-790** [comment]
@xiaoyijun I would like to work on this issue, can you assign it to me?

**Comment by xiaoyijun** [comment]
Hi, @akarsh-jain-790 , thanks for your interest in our project!
You just need to submit the relevant pull request to participate in our activities :)

**Comment by iamakhileshmishra** [comment]
@xiaoyijun If this issue is still open I would like to work on this please assign this to me

**Comment by xiaoyijun** [comment]
Hi @iamakhileshmishra , thanks for your interest, but this issue is completed in #4638 . You can try other issues 🩷.
