### ISSUE TITLE
bug: API Resource Access Token Not Given and Indicates Resource Indicator is Missing When Provided

### ISSUE THREAD

**Issue by patakattack** [logto-io/logto#4630]
First off, thanks for all the work you do and I apologize if I misunderstood something but I think this is a bug, but hopefully it's just me doing something wrong.

### Describe the bug
When using @logto/express and following the documenation with this code:

`app.get(
  '/fetch-access-token',
  withLogto({
    ...config,
    // Fetch access token from remote, this may slow down the response time,
    // you can also add "resource" if needed.
    getAccessToken: true,
  }),
  (request, response) => {
    // Get access token here
    console.log(request.user.accessToken);
    response.json(request.user);
  }
);`

This is my code I provided with a resource:

`app.get(
    "/fetch-access-token",
    logToExpress.withLogto({
      ...logtoConfig,
      // Fetch access token from remote, this may slow down the response time,
      // you can also add "resource" if needed.
      getAccessToken: true,
      resource: "https://temp.api.example.com",
      fetchUserInfo: true,
    }),
    (request, response) => {
      // Get access token here
      console.log(request.user.accessToken);
      response.json(request.user);
    }
  );`

This is the message in the logto audit logs

`  "error": "{\"stack\":\"InvalidTarget: invalid_target\\n    at default (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/resolve_resource.js:29:13)\\n    at refreshTokenHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/grants/refresh_token.js:184:26)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async callTokenHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:70:7)\\n    at async allowedGrantTypeCheck (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:53:7)\\n    at async supportedGrantTypeCheck (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:45:7)\\n    at async stripGrantIrrelevantParams (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:33:7)\\n    at async auth (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:257:9)\\n    at async loadClient (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:152:9)\\n    at async setWWWAuthenticateHeader (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:43:11)\\n    at async selectiveBody (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/selective_body.js:49:5)\\n    at async noCache (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/no_cache.js:3:3)\\n    at async cors (/etc/logto/node_modules/.pnpm/@koa+cors@4.0.0/node_modules/@koa/cors/index.js:105:16)\\n    at async errorHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/error_handler.js:26:7)\\n    at async ensureSessionSave (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/initialize_app.js:52:7)\\n    at async contextEnsureOidc (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5)\",\"message\":\"invalid_target\",\"allow_redirect\":true,\"name\":\"InvalidTarget\",\"error\":\"invalid_target\",\"status\":400,\"statusCode\":400,\"expose\":true,\"error_description\":\"resource indicator is missing, or unknown\"}",
`

### Expected behavior
No error should be thrown as a resource indicator was provided. I should receive an access token for the api resource specified.

### How to reproduce?
Make sure an api resource is set up

Follow the documentation steps listed on this page:

[https://docs.logto.io/docs/recipes/integrate-logto/express/](url)

Provide a resource (with the name from the api resource set up) in withLogto

### Context

- [ ] Self-hosted, Logto version = 1.10
  - [ ] Container (Docker image)

**Comment by simeng-li** [comment]
Hi @patakattack ,

The error above shows the resource indicator you provided is not recognized. There are a couple of things you could check:
1. What is the resource(s) value you provided, has it(they) been registered on the Logto Admin Console
2. Do you add the resource(s) to the logtoConfig when initializing the express SDK

**Comment by patakattack** [comment]
Hi @simeng-li , 

This is what I have set up in the Admin Console
![image](https://github.com/logto-io/logto/assets/45567605/6260a50d-e83e-4f38-a283-69c3755ef0c6)

and this is what my code looks like providing the resource
![image](https://github.com/logto-io/logto/assets/45567605/376e0d3f-a009-41c2-acff-2799c74248d1)

When I initialize the logtoConfig, I do not include resource(s). This is what that looks like:

![image](https://github.com/logto-io/logto/assets/45567605/bbbe1b1f-5cff-4100-af11-4579d86e1a99)
![image](https://github.com/logto-io/logto/assets/45567605/5b7984f2-367a-4c71-b12e-66337017e70f)

**Comment by simeng-li** [comment]
https://github.com/logto-io/js/blob/master/packages/client/src/types/index.ts#L39

@patakattack could you try this:
Replace the `resource: "https://temp.api.****.com"` in your logtoConfig argument with array parameter `resources: ["https://temp.api.****.com"]`

**Comment by simeng-li** [comment]
@patakattack you will also need to specify the `resources: ["https://XXXXX.com"]` in the logtoConfig as well.

**Comment by patakattack** [comment]
Wow! Thank you!

I was following the documentation here:

[https://docs.logto.io/docs/recipes/integrate-logto/express/](https://docs.logto.io/docs/recipes/integrate-logto/express/)

Maybe the documentation could be updated here with something like (obviously the wording could be better)

```javascript
const config: LogtoExpressConfig = {
  appId: '<your-application-id>',
  appSecret: '<your-application-secret>',
  endpoint: '<your-logto-endpoint>', // E.g. http://localhost:3001
  baseUrl: '<your-express-app-base-url>', // E.g. http://localhost:3000,
  // Might need to add resources: ["https://XXXXX.com"] when calling getAccessToken for a resource
};
```

**Comment by simeng-li** [comment]
Sure we will. Thanks for your report. Did realize the same thing. Our integration doc does not provide clear instructions about the usage of resources.
