### ISSUE TITLE
bug: Infinite reload of successful login page, in Flask. Logto Cloud

### ISSUE THREAD

**Issue by afonso-pereira** [logto-io/logto#4674]
Using logto with flask, when using the @protected decorator suggested in the setup guide, the following happens:

User goes to home page;
Clicks on signin button;
Is taken to signin page;
After signing in, the user is then in a loop, where the logto page after successful login  is constantly refreshed. 

- [x] Logto Cloud

**Comment by afonso-pereira** [comment]
https://github.com/logto-io/logto/issues/4677

I created this other issue, but I will close it, as I believe it is due to the same bug.

**Comment by Dav-id** [comment]
I and a number of other users of mine have experienced this following the most recent updated Docker image. Clearing the cookies and a fresh login clears it and we are able to login as normal.

**Comment by afonso-pereira** [comment]
@Dav-id I already did it, but the issue persists. sometimes it even happens on the logto side, for example: go to sign in route -> select create account, and input an email that already exists -> logto will ask if you want to sign in, given the account already exists -> infinite reload of https://tenantid.logto.app/sign-in/consent

#4677 I also have this issue, which I think I will reopen. whenever trying to get information from the user, that same error occurs.

**Comment by afonso-pereira** [comment]
A quick update, performing this change on the code fixed the infinite reload, however, the authenticated decorator is not working, any not authenticated user is being able to reach the protected pages. Also, the home page does not show the personalized text in case the user is logged in.

![image](https://github.com/logto-io/logto/assets/54318711/a756c5d3-0d55-4d6c-88f3-17b65e2f8204)

**Comment by gao-sun** [comment]
thanks for reporting - i'll take a look soon

**Comment by afonso-pereira** [comment]
thanks @gao-sun . Let me know if you want me to test something on my side

**Comment by afonso-pereira** [comment]
@gao-sun following the setup guide, it indeed does not work, but following [this example code on your repo](https://github.com/logto-io/python/blob/master/samples/flask.py), it works perfectly. Keep on with the nice work!

**Comment by gao-sun** [comment]
@afonso-pereira thank you for letting me know! i was packed these days and didn't have time to dig the issue - will update the setup guide to match the example code. really appreciate it!

**Comment by gao-sun** [comment]
https://github.com/logto-io/python/pull/11/files

@afonso-pereira i could not repro your case, but i updated an example of using decorator. curious about how to reproduce your issue though
