### ISSUE TITLE
feature request:  can support nestjs ?

### ISSUE THREAD

**Issue by JohnLanPeluchi** [logto-io/logto#4827]

**Comment by wangsijie** [comment]
Currently there is no offical SDK for Nest JS.

Can you provide more details on your use case? Usually, there are 2 use cases:

1. Use Nest JS as pure API server (backend), then you don't actully need a SDK, simply use a front end SDK, then refer to [this doc](https://docs.logto.io/docs/recipes/protect-your-api/) to see how to check JWT and protect your API.
2. Use Nest JS as the "traditional" way, render webpage content in the server side. In this case, you'll need to do some additional work, check out Logto's JS SDK repo: https://github.com/logto-io/js, and use "@logto/node" package to integrate Logto into your app, you can take the express SDK as an example.

**Comment by xiaoyijun** [comment]
Since this issue has been inactive for over 30 days, it will be closed for now. If there are any further issues, you can reopen it. @JohnLanPeluchi
