### ISSUE TITLE
bug: Another algorithm expected, or no matching key(s) found

### ISSUE THREAD

**Issue by DiegoOrdonezBecerril** [logto-io/logto#4910]
### Describe the bug
Error protecting Spring Boot API

Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"

### How to reproduce?
Follow guide for protect API

    public JwtDecoder jwtDecoder() {
        NimbusJwtDecoder jwtDecoder = NimbusJwtDecoder.withJwkSetUri(jwksUri)
            .jwtProcessorCustomizer(customizer -> customizer.setJWSTypeVerifier(
                new DefaultJOSEObjectTypeVerifier<SecurityContext>(new JOSEObjectType("at+jwt"))))
            .build();

        jwtDecoder.setJwtValidator(new DelegatingOAuth2TokenValidator<>(
            new AudienceValidator(audience),
            new JwtIssuerValidator(issuer),
            new JwtTimestampValidator()));

        return jwtDecoder;
    }

### How to solve?
Add jwsAlgorithm(ES384) to decoder

![image](https://github.com/logto-io/logto/assets/80222346/af4ea115-dc12-4672-a6f2-d70908559531)

### Context
Windows: 11
logto/browser: 2.1.2 on angular: 17.0.0
Spring Boot: 3.1.4

- [ X] Logto Cloud
- [ ] Self-hosted, Logto version = 
- [ ] Container (Docker image)
- [ ] Raw Node.js

### Screenshots

![image](https://github.com/logto-io/logto/assets/80222346/23a19ada-bca7-411c-894a-7149559fe3d3)

**Comment by xiaoyijun** [comment]
Hi @DiegoOrdonezBecerril , Logto uses `ES384` as the algorithm by default, that means you need to specify the algorithm when decoding.
If you're using the Logto cloud, you can use another signing key with other algorithm by [signing key rotation](https://docs.logto.io/docs/recipes/signing-keys-rotation/)

Also, the guide is outdated, thanks for pointing out.
Would you mind to update the guide when you're available? @simeng-li

**Comment by simeng-li** [comment]
Thanks for the report. Yes, our SpringBoot API protection guide is outdated. Working on that. Appreciate it.
