### ISSUE TITLE
feature request: React call signIn method immediately inside a Component 

### ISSUE THREAD

**Issue by goodstuff20** [logto-io/logto#4937]
### What problem did you meet?
Instead of e.g. having a page with a button that triggers an await signIn(..), I would like to call the login page directly, e.g.:
```
export default function LoginPage() {
  const { signIn } = useLogto();

  async function login() {
    await signIn(
      `${window.location.protocol}//${window.location.host}/callback`,
    );
  }

  return (
    <>{login()}</>
  );
}

...

if (!isAuthenticated) {
  return <LoginPage />;
}
```
this works, but first throws a log warning "_Cannot update a component (`LogtoProvider`) while rendering a different component (`LoginPage`)._" and then log errors "_Objects are not valid as a React child_".

### Describe what you'd like Logto to have
Offer a fix or alternative for such as use case.

**Comment by xiaoyijun** [comment]
Hi @goodstuff20, More context is needed.
But you may try to call the `signIn` when Logto loaded.
```jsx
export default function LoginPage() {
  const { signIn, isLoading, isAuthenticated } = useLogto();
  
  useEffect(() => {
    if (!isLoading && ! isAuthenticated) {
      void signIn("...");
    }
  }, [isLoading, signIn])
  
  //...
 }

```
