### ISSUE TITLE
bug: OSS version cannot load images from external URLs for app logo and favicon customization

### ISSUE THREAD

**Issue by xiaohanyu** [logto-io/logto#4967]
### Describe the bug

Self hosted OSS version cannot load images from external origins in Sign In Experience

### Expected behavior

OSS version mandates URLs for app logo and favicon customization, and it should allow any URLs to be loaded successfully instead of applying CORS rules.

### How to reproduce?

- Run a docker version of logto in local
- try to customize app logo and favicon for Sign-in experience.

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 1.11
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

OSS version for app logo and favicon customization:

<img width="2160" alt="image" src="https://github.com/logto-io/logto/assets/1164623/3ad8805d-b178-46d4-a005-11d5ff86f419">

<img width="2160" alt="image" src="https://github.com/logto-io/logto/assets/1164623/a4919577-e048-4056-8912-d35cefa338a2">

with devtools:

<img width="2672" alt="image" src="https://github.com/logto-io/logto/assets/1164623/4e460dd6-2afb-434e-adca-a3239dde83ad">

Cloud version support image upload for app logo and favicon customization:

<img width="2160" alt="image" src="https://github.com/logto-io/logto/assets/1164623/2a77ecac-0652-4174-a5b6-91a0af44119e">

I suspect that this [commit](https://github.com/logto-io/logto/commit/1c431e7a59f79559569af6464f71f6f09d13d769) was specialized for enhance security for cloud version but lead to this bug as if you remove `crossorigin="anonymous"` attribute in `<img>`, then the image could be loaded successfully.

**Comment by xiaoyijun** [comment]
Hi @xiaohanyu , You should check the cross-origin settings for your self-hosted OSS service; this issue is not related to the value of [crossorigin](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) prop.

**Comment by xiaohanyu** [comment]
Veried, yes need to set proper CORS headers for images response in order to make logto load successfully.

Thanks for reminding!
