### ISSUE TITLE
bug: Your Vanilla JS Instructions Do Not Work

### ISSUE THREAD

**Issue by paul-go** [logto-io/logto#5030]
I'm following your instructions on this page in order to setup a Vanilla JS installation:

![Screenshot 2023-11-30 at 2 38 35 PM](https://github.com/logto-io/logto/assets/16612419/a9fb7971-e991-4433-96df-554b09e7dff6)

My suspicion is that you haven't gotten around to testing this particular part of your onboarding flow with actual users yet, because these instructions aren't sufficient to produce anything useful.

I would expect to see a working test project. I tried to download the files in this folder:
https://github.com/logto-io/js/tree/HEAD/packages/browser-sample

And ran an `npm install` (which after investigation doesn't work with npm, but rather only pnpm or yarn, despite the instructions in the screenshot stating otherwise).

However, the project doesn't build (`npm run build`), it just reports various syntax errors that are in the downloaded code.

I could continue with investigation here, and I'm happy to provide diagnostic information, but before I invest hours in this, I need to know whether there's even any interest among the maintainers to fix this.

Its worth noting that for vanilla JS development, I would expect to be given a single .js file to point to in a <script> tag, and possibly something to `npm install` in order to get the typescript typings. I shouldn't have to get into a hairy mess of installing rollup, parcel, switching node versions, installing other package managers, and debugging syntax errors that are preventing your test project from building. The appeal of vanilla JS is to avoid all this in the first place.

**Comment by charIeszhao** [comment]
Thanks for reporting. We'll take a look.

We had several major releases recently, and it might just break something. Since the browser sample is not written in TypeScript, this could happen when the core JS lib has changed. However, we do have TypeScript typing and unit tests to guarantee the quality of the `@logto/browser` lib itself. So current it seems we need to revisit the sample project and see if it is out-of-sync.

Will update the ticket once we have any progress. Thanks again for the report.

**Comment by charIeszhao** [comment]
Thanks for asking. There's no ETA on this yet, but I'm planning to improve some of the JS SDKs recently, most likely starting from this weekend or earlier next week. Please stay tuned.

**Comment by charIeszhao** [comment]
Btw, is your project a plain JavaScript application? If you are using any of the modern JS libraries, such as React, Next, you can also check on the other SDKs. Our console application is built with React and we eat our own dog food using the `@logto/react` SDK.

**Comment by paul-go** [comment]
The project is vanilla JS. I was put in charge of tearing down a dumpster fire of a React project, and rebuilding it framework-free. I'm the developer of RawJS (https://scrollapp.org/rawjs/), so as you can imagine, I'm not the biggest fan of web frameworks.

I guess I could probably pull apart your react bindings and get it to work with vanilla. Though if you're going to get to this in the next few days I'll wait.

Feel free to email me (paul at scroll app dot org) if you want some help massaging the docs for vanilla JS.

**Comment by paul-go** [comment]
I was able to get the project working by making my own sample minimal project that uses the Parcel bundler to generate a .js file bundle, and then copying that generated bundle into my Vanilla JS project. Below is a link to the repo:

https://github.com/paul-go/LogtoSample

I guess the missing piece is that the docs should say somewhere that Parcel is required, and/or a distribution `logto.min.js` file should be made available that can be easily `<script src>`'d within an index.html file.

**Comment by charIeszhao** [comment]
I'm not sure what was exactly the issue on your side, but I don't think Parcel is required, as we have other users who have integrated the browser SDK in their Svelte and Angular projects, and clearly enough they weren't using Parcel as the bundler.

But a min js would be nice to have. I'll talk to other team members to see when we can have it on our CDN. Will update you once the min js distribution is available. Thanks for the information.
