### ISSUE TITLE
feature request: how to send the custom-data of user with id_token and access_token

### ISSUE THREAD

**Issue by heng4fun** [logto-io/logto#5062]
### What problem did you meet?
I add some data into the user custom-data, and I want to add custom-data into the id_token and access_token.

So my backend service can get the custom-data from token directly.

### Describe what you'd like Logto to have
I've done this use `Auth0` and `Authing`, but I don't know how to do this in logto.

**Comment by charIeszhao** [comment]
You can have `custom_data` in your ID token, by providing the `custom_data` scope when initializing `LogtoClient`. If you use our SDK you can also import the enum `UserScope.CustomData`.

You can refer to our React Sample project for more details. https://github.com/logto-io/js/blob/master/packages/react-sample/src/App.tsx#L20

**Comment by charIeszhao** [comment]
Regarding the access token, since it is used in each and every request, we don't put custom_data in it, in order to control the token size.

**Comment by heng4fun** [comment]
I've already added `UserScope.CustomData` into the scope.
But the ID token is without custom_data either, did I miss something?

<img width="2252" alt="image" src="https://github.com/logto-io/logto/assets/4293867/5e87784d-c5a0-4551-8b4f-8403fd8ce213">

<img width="2300" alt="image" src="https://github.com/logto-io/logto/assets/4293867/d822167c-266c-44bd-a2e8-b0b76dbb7935">


<img width="1298" alt="image" src="https://github.com/logto-io/logto/assets/4293867/ce7f2191-f47d-421b-b1b7-7167de8b5521">

**Comment by charIeszhao** [comment]
Have you tried signing out and signing back in?

**Comment by heng4fun** [comment]
> Have you tried signing out and signing back in?

Yes, I tried many times, but there is still no custom data in id token.

**Comment by charIeszhao** [comment]
Yes, I can reproduce this as well. Let me check with the team if this is a bug. Will update you later, thanks!

**Comment by charIeszhao** [comment]
OK, just confirmed this is by design, no `custom_data` claim available in ID token whatsoever. For now, you can only fetch custom data from the userinfo endpoint through the `fetchUserInfo` method.

**Comment by heng4fun** [comment]
OK, got it.
