### ISSUE TITLE
bug: Translation in Sign-in Experience is incorrect

### ISSUE THREAD

**Issue by pramotetrs** [logto-io/logto#5083]
### Describe the bug
The translation of live preview in Sign-in Experience feature is incorrect when I mapped the custom value. However, I have not tested in actual sign-in process.

### Expected behavior
The error message of 'username is required' should be 'กรุณากรอกชื่อผู้ใช้งาน' that I set for custom value in Manage Language feature in Sign-in Experience menu

### How to reproduce?
You may check by the docker image of `svhd/logto:latest` on the day I posted. Note that I could not find the version of the image

### Context
I used default configuration to deploy in container. I just clone the repository, and start the docker-compose

- [ ] Logto Cloud
- [ ] Self-hosted
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

<img width="756" alt="image" src="https://github.com/logto-io/logto/assets/100534050/7db3a63a-fe29-458c-ae02-fef15b3eb870">
<img width="1237" alt="image" src="https://github.com/logto-io/logto/assets/100534050/dbfd53de-8b35-4d7d-bb70-687c1b9d7f95">

**Comment by charIeszhao** [comment]
Thanks for reporting. This is reproducible and thus confirmed as a bug. We'll let you know when it's fixed.

**Comment by charIeszhao** [comment]
Just double checked and confirmed this is currently "by design". At sign-in flow, since the "sign-in identifiers" might be more than one (you can enable username, email and phone at the same time at sign-in), so we don't actually know what the field type is. Therefore, `general_required` i18n key is used instead of the specific key `username_required`.

The `username_required` key, however, is only used at registration flow, since the sign-up identifier can only be one.

We'll still try to improve the user experience in the future.

**Comment by pramotetrs** [comment]
Thanks for workaround. However, I've changed `username` to the custom value but some part of error cannot be changed or be translated. There still be `ทดสอบ is required`.

<img width="1057" alt="image" src="https://github.com/logto-io/logto/assets/100534050/4d19b756-aff3-4ab0-ade2-9fb221c92598">

And the forgot-password flow is also affected by this bug as the following. The username in sign-in page, and email in forgot-password page are using the same `general_required` error message.

<img width="1345" alt="image" src="https://github.com/logto-io/logto/assets/100534050/b28bda56-31bf-4a4f-9654-7abe4c66459d">

Changing the value of `general_required` affect both sign-in and forgot-password page. Is there any workaround? @charIeszhao

**Comment by charIeszhao** [comment]
@pramotetrs, I don't think I get your last question, as it seems it's going work if you change the value of `general_required`, isn't it? Why do you ask for another workaround?

**Comment by charIeszhao** [comment]
Closing the ticket due to inactivity for months. Feel free to reopen if necessary.
