### ISSUE TITLE
bug: Component is using default input validation

### ISSUE THREAD

**Issue by pramotetrs** [logto-io/logto#5098]
Your component is using default input validation.

### Describe the bug

The validation is implemented incorrectly.

### Expected behavior

It should be error message of application.

### How to reproduce?

You can reproduce in docker-compose deployment

### Context
Default context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots
<img width="987" alt="image" src="https://github.com/logto-io/logto/assets/100534050/1761fcd9-36fb-4e62-bf4c-20416b29c138">

**Comment by wangsijie** [comment]
Thanks for reporting, but I think this is the expected behaviour. The default browser check comes first.

**Comment by pramotetrs** [comment]
Of course, this is browser behavior but don't you think to change to be the same style as others?

![image](https://github.com/logto-io/logto/assets/100534050/53a3e5d2-32a6-48b8-a55f-c33d839742e7)

**Comment by wangsijie** [comment]
This does not conflict. The browser's default check first performs a preliminary validation, followed by Logto's own check. The browser's check is more lenient compared to Logto's check.

**Comment by wangsijie** [comment]
Closing this, feel free to reopen if you have any questions @pramotetrs
