### ISSUE TITLE
bug: The development environment is not suitable for Windows

### ISSUE THREAD

**Issue by mrchenxxx** [logto-io/logto#5124]
I want to develop dingtalk connectors, but when I set up the development environment, I get errors, all kinds of errors

**Comment by simeng-li** [comment]
Hi, can you show us some more details? 
If you are trying to build Logto on Windows most likely the scripts will fail because the syntax is incompatible.  All the node and shell script was written under Linux/Mac. You need to adjust some of the scripts to make it work on Windows.

**Comment by mrchenxxx** [comment]
> Hi, can you show us some more details?您好，您能给我们展示更多详细信息吗？ If you are trying to build Logto on Windows most likely the scripts will fail because the syntax is incompatible. All the node and shell script was written under Linux/Mac. You need to adjust some of the scripts to make it work on Windows. 如果您尝试在 Windows 上构建 Logto，脚本很可能会失败，因为语法不兼容。所有节点和shell脚本都是在Linux/Mac下编写的。您需要调整一些脚本才能使其在 Windows 上运行。

like： prepare$ if test "$NODE_ENV" != "production" && test "$CI" != "true" ; then husky install ; fi
│ "$NODE_ENV" was unexpected at this time.

**Comment by simeng-li** [comment]
Yep, that won't work on Windows. As mentioned we don't have Windows build scripts provided out of the box. You have to make some tweaks.  Sth like 

`if not \"%NODE_ENV%\"==\"production\" if not \"%CI%\"==\"true\" (husky install)` .
