### ISSUE TITLE
feature request: if I can restrict the app to an organization?

### ISSUE THREAD

**Issue by corvofeng** [logto-io/logto#5183]
### What problem did you meet?

I have lots of apps, and I don't every one login with the logto can access them all.

### Describe what you'd like Logto to have

Here is my solution after checking the code:

1. Add a checkbox in app setting page, if it's an organized-orient app. 
2. Add the logic: when user want to get authorized token for that app. 

```
if user or its organization has permission like app:<TestApp>:
   allow the process
else:
   deny and terminate
```

3. Add an API(optional): User could get the apps they have permission. it should return a list and we can embed it into the demo-app.

Please let me know if you have another way to restrict apps for user.

**Comment by fleuraly** [comment]
@corvofeng If I understood correctly, do you mean you have a universal login experience for multiple apps? Some apps don't need organization enabled but some need?

To clarify, do you want to maintain one single-user identity system for those apps?

**Comment by corvofeng** [comment]
Consider a scenario:

There is a web page that displays various applications. Depending on the user's permissions, they can only see the applications that they are authorized to use. Some applications are only visible to developers, while others are only visible to designers.

**Comment by fleuraly** [comment]
For your use cases, you can utilize [Logto API's role-based access control](https://docs.logto.io/docs/recipes/rbac/) to achieve your goals. 

1. First, define the API resources for your different apps and create permissions under those resources. 
2. Meanwhile, create two roles: one for developers and the other for designers. Each role will contain different permissions based on the API resources you've defined. 
3. Next, assign the roles to the users. Users assigned a specific role will then have access to the corresponding resources.

In Logto, authorization isn't directly tied to apps, but you can flexibly define API resources, offering a more granular level of access control.
To check out Logto API RBAC, check our doc:

1. https://docs.logto.io/docs/recipes/rbac/
2. Our real-world example: https://blog.logto.io/mastering-rbac/

If I understand correctly, are you creating an internal tool or platform for a company, allowing different employee groups to have flexible access control over multiple apps within the platform?

**Comment by KevinGage** [comment]
I believe I have a similar issue but I am not sure if it can be solved with RBAC.  Maybe I am wrong but I would appreciate any guidance.  I have multiple Next.js applications.  Each one uses its own unique front end and back end data.  They are not interconnected in any way.  I would like to use the same Logto instance to manage users for all of the applications.  I would like to limit which applications each user can log into, not just their access after logging in.

For instance "User1" should be able to log into "App1" and "App2".  When they try to login to App3 it should reject their credentials.
"User2" should be able to log into "App2" and "App3".  When they try to log into App1 it should reject their credentials.

**Comment by charIeszhao** [comment]
> I would like to use the same Logto instance to manage users for all of the applications. I would like to limit which applications each user can log into, not just their access after logging in.

These two requirements are somehow conflict. If you want a one-login-system, then all the apps that connects to it should be able to authenticate all users in the system. If you want to limit user access to a certain app, then this is authorization level stuff.

I think we should de-couple authentication and authorization here. And access control should only be handled by the RBAC feature upon successful authentication.

**Comment by corvofeng** [comment]
Thanks for your reply. I found that keycloak(with plugin) can limit user permission for every client:

https://github.com/sventorben/keycloak-restrict-client-auth


```yaml
services:
  keycloak:
      image: quay.io/keycloak/keycloak:23.0.4
      command: ['start', '--import-realm', '--features=client-policies']
      # add your env.
      ports:
        - 8080:8080
      volumes:
      - ./target/keycloak-restrict-client-auth.jar:/opt/keycloak/providers/keycloak-restrict-client-auth.jar
```

**Comment by u0x01** [comment]
For new users or those with similar requirements:

In the latest version of logto (currently v1.22.0), you can implement similar requirements using the **Custom Jwt** - FOR USER - **User access token** feature.

Here's an example implementation:
```javascript
const getCustomJwtClaims = async ({ token, context, environmentVariables, api }) => {
  // restrict user can sigin some app by role resource url
  if (token.clientId === '<your-app-id>') {
    const matchingResource = context.user.roles.find(role => 
      role.scopes.some(scope => 
        scope.resource?.indicator === '<https://your.resource.com>'
      )
    );

    if (!matchingResource) {
      return api.denyAccess('Access denied');
    }
  }

  // restrict user can sigin some app by organizations
  if (token.clientId === '<your-app-id>') {
    const matchingOrganization = context.user.organizations.find(organization => 
      organization.id === '<your-organization-id>'
    );

    if (!matchingOrganization) {
      return api.denyAccess('Access denied');
    }
  }

  // You can even make API calls here to implement a pre-login hook:
  try {
    const { apiKey } = environmentVariables;
    const response = await fetch('https://<logoto-endpoint>/webhook/logto/before-sign-in/'+token.clientId, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(context.user)
    });

    const data = await response.json();
    if (data.error) {
      return api.denyAccess(data.error_description || data.error);
    }
  } catch (error) {
    return api.denyAccess(`Access denied: backend error: ${data.error_description || data.error}`);
  }
  return {}
}
```

After configuration, save and test if it works.

Pro tip: If you need to test the actual application context, you can debug using:
```javascript
return api.denyAccess(JSON.stringify({token, context}));
```
This will help you inspect the available context data.


For more details about custom token claims, please check the [documentation](https://docs.logto.io/developers/custom-token-claims/create-script).

**Comment by chark1es** [comment]
Going based off the previous comment, you can also check to see if the user has the required scopes. Here's a simplified example:

```js

const getCustomJwtClaims = async ({ token, context, environmentVariables, api }) => {
  const REQUIRED_SCOPE = 'CHANGE_THIS_SCOPE'; // The required scope for access (e.g. access:app)
  const APPLICATION_ID = 'CHANGE_THIS_APP_ID'; // Application ID

  // Check if the client ID matches the application.
  if (token.clientId === APPLICATION_ID) {
    // Check if any of the user's roles contains the required scope.
    const hasRequiredScope = context.user.roles.some(role =>
      role.scopes.some(scope => scope.name === REQUIRED_SCOPE)
    );

    if (!hasRequiredScope) {
      return api.denyAccess(`Access denied: Missing required scope "${REQUIRED_SCOPE}"`);
    }
  }

  return {};
};
```
