### ISSUE TITLE
bug: no applicable key found in the JSON Web Key Set

### ISSUE THREAD

**Issue by cong5** [logto-io/logto#5186]
Hello!

I ran logto in kubernetes using the docker image: svhd/logto:latest, but when I tried to log into the console, an error occurred and I was unable to log in.

Oops! Something went wrong.
f: no applicable key found in the JSON Web Key Set
    at c.getKey (https://xxxx.shop/console/index.b0698af2.js:3:29786)
    at https://xxxx.shop/console/index.b0698af2.js:3:30333
    at #c (https://xxxx.shop/console/index.b0698af2.js:3:44747)
    at o.getKey (https://xxxx.shop/console/index.b0698af2.js:3:44304)
    at async u (https://xxxx.shop/console/index.b0698af2.js:3:16240)
    at async a (https://xxxx.shop/console/index.b0698af2.js:3:14004)
    at async a (https://xxxx.shop/console/index.b0698af2.js:3:18868)
    at async l (https://xxxx.shop/console/index.b0698af2.js:3:40765)
    at async c.verifyIdToken (https://xxxx.shop/console/index.b0698af2.js:1:532057)
    at async c.handleSignInCallback (https://xxxx.shop/console/index.b0698af2.js:1:530082)

**Comment by cong5** [comment]
Console backend login no longer reports an error, but the return value from Machine-to-Machine application requesting Machine-to-Machine is：
```
{
    "message": "未经授权。请检查凭据及其范围。",
    "code": "auth.unauthorized",
    "data": {
        "code": "ERR_JWKS_NO_MATCHING_KEY",
        "name": "JWKSNoMatchingKey",
        "message": "no applicable key found in the JSON Web Key Set"
    }
}
```

**Comment by darcyYe** [comment]
Hi @cong5 , could you please elaborate on your setup and how you make M2M requests?

**Comment by cong5** [comment]
> Hi @cong5 , could you please elaborate on your setup and how you make M2M requests?

first request https://xxx.shop/oidc/token get access_token:
<img width="1286" alt="image" src="https://github.com/logto-io/logto/assets/5463514/eb94b37a-b749-4399-aa56-11f0030745fa">

second request any Logto Management API response this error.

<img width="1264" alt="image" src="https://github.com/logto-io/logto/assets/5463514/5c0eb9f8-a086-43e2-923b-70f5c904f0d2">

**Comment by darcyYe** [comment]
Are you using a self-hosted OSS version? or you are using Logto Cloud.

**Comment by cong5** [comment]
> Are you using a self-hosted OSS version? or you are using Logto Cloud.
using a self-hosted version

**Comment by darcyYe** [comment]
Did you or someone with access to your Logto localhost change the `oidc.privateKeys` after the instance started but before you requested the Logto management API?

**Comment by darcyYe** [comment]
I can not reproduce your issue on my machine. I started a brand new OSS Logto instance with a new DB, created a m2m app, can hence successfully get the access token and access the management API. It could be helpful if you can provide a step by step guide to reproduce this issue.

**Comment by darcyYe** [comment]
You can also check whether you have assigned the scope `all` to the M2M app via an m2m role.
