### ISSUE TITLE
research: configure eslint to prefer `return next()` when no `await` is needed

### ISSUE THREAD

**Issue by gao-sun** [logto-io/logto#53]

**Comment by wangsijie** [comment]
Koa's middleware uses `ctx` instead of return value, is not "pure function", so return value may not be important.

**Comment by gao-sun** [comment]
yes, just wanna align our code style.

**Comment by gao-sun** [comment]
agreed with you that return value doesn't matter.

**Comment by wangsijie** [comment]
disallow return has an adventage: prevent treating the return value as useful staff by mistake

**Comment by gao-sun** [comment]
agreed, so i added the following type in `packages/core/src/include.d/koa.d.ts`:

```ts
export type KoaMiddleware<T, R> = (context: T, next: KoaNext<R>) => Promise<void>;
```

this makes sure that middleware is a `void` promise which means nothing. plus, return can enable eslint check for unreachable code and save 1 LOC for every middleware that doesn't need operations after `next`.

also check out the [official example](https://github.com/koajs/koa#common-function) of using `return next()`.

**Comment by gao-sun** [comment]
tracked in https://linear.app/silverhand/issue/LOG-37/configure-eslint-to-prefer-return-next-when-no-await-is-needed
