### ISSUE TITLE
feature request: Redirect uri for hybrid apps that involve both a web version and a native app

### ISSUE THREAD

**Issue by TheLonelinessOfHS** [logto-io/logto#5376]
### What problem did you meet?
For a hybrid APP with a web version and a native APP version, it is not possible to specify a standard https URL and one with a custom scheme as redirect_uri at the same time. Example: [Immich ](https://immich.app/docs/administration/oauth/)

### Describe what you'd like Logto to have
Support hybrid APP that allows standard https URL and custom scheme to work together.

**Comment by darcyYe** [comment]
A hybrid app is a straightforward solution for your case. But for now, you can create a Logto web app for your web version and a Logto native app for your native app to unblock. Both of these two Logto apps rely on a single identity system.

**Comment by TheLonelinessOfHS** [comment]
> A hybrid app is a straightforward solution for your case. But for now, you can create a Logto web app for your web version and a Logto native app for your native app to unblock. Both of these two Logto apps rely on a single identity system.

I understand that. However, in the Immich example it only allows me to specify a single set of client id & secret while I am a user but not a developer.

**Comment by darcyYe** [comment]
Try to make it clear: you want to use the immich app, but at the same time, use Logto to manage the user identities for your self-hosted immich app, is that correct? Your statement that "immich allows only one set of client ID and secret" confuses me a bit, could you please elaborate on this? Also, related documents could be helpful.

**Comment by TheLonelinessOfHS** [comment]
> Try to make it clear: you want to use the immich app, but at the same time, use Logto to manage the user identities for your self-hosted immich app, is that correct? Your statement that "immich allows only one set of client ID and secret" confuses me a bit, could you please elaborate on this? Also, related documents could be helpful.

Thanks a lot for your response. I am just using Immich as an example but I believe some other APPs and developers will have the same issue. In the solution you provided above, we will need to create two sets of OIDC credentials (Logto APPs I mean). However, Immich (docs provided above) only takes a single OIDC provider. You cannot specify two oidc providers at the same time. 

Please NOTE that I am fully aware that Immich has already provided a solution for this kind of hybrid APP, by using a HTTP redirection link (see the docs). However, I feel that this is an issue that logto as the identity provider should address. Otherwise, it might cause some additional complexity to APP developers and users (what if Immich did not provide such a solution?).

**Comment by darcyYe** [comment]
Need to correct that: even if you create multiple apps in the Logto console. There is only one OIDC provider and all the apps rely on it.
We will discuss whether this feature should be supported. The solution provided earlier is to prevent any currently unimplemented features from blocking your use of Logto, which does not mean this feature request is meaningless.
You've mentioned that Immich offers a solution for hybrid apps; would you be willing to provide a link? This could be very helpful during our discussion of requirements or use cases. Thank you very much!

**Comment by TheLonelinessOfHS** [comment]
> Need to correct that: even if you create multiple apps in the Logto console. There is only one OIDC provider and all the apps rely on it. We will discuss whether this feature should be supported. The solution provided earlier is to prevent any currently unimplemented features from blocking your use of Logto, which does NOT mean this feature request is meaningless. You've mentioned that Immich offers a solution for hybrid apps; would you be willing to provide a link? This could be very helpful during our discussion of requirements or use cases. Thank you very much!

Sorry that I did not make it clear. By an OIDC provider I mean a set of credentials involve 'oidc end point' + 'APP ID' + 'APP secret' + 'redirect uri'. In logto, different APPs obviously have different sets of id + secret, despite that they share an endpoint.

The link to the documentation is [here](https://immich.app/docs/administration/oauth/). Please read the 'Mobile Redirect URI' section.

**Comment by darcyYe** [comment]
Close this issue since this is not planned. The universal URL format proposed in this issue violates the OIDC protocol, that's why we are not going to implement this.
For apps that does not accept multiple redirect URIs in the config, developers can manually apply one redirection as the Immich app does to workaround.

**Comment by wildsylvan** [comment]
@darcyYe does this mean that support for [android app links](https://developer.android.com/training/app-links) (with https:// scheme) won't be supported?
