### ISSUE TITLE
bug: UX navigation loading state

### ISSUE THREAD

**Issue by mrfrase3** [logto-io/logto#5391]
### Describe the bug
After the user has completed signing in, regardless of type (password, social, sso), the frontend causes a navigation to start going to the redirect URL.

The redirect URL involves several redirects which takes a while for things to happen. I've timed 1s on logto servers, 3s on my local backend, the user may also have a slow internet connection. The fact that setting up a users login takes a second isn't the issue though.

While the redirects are happening, the browser is still sitting on the sign in page waiting for a response, leaving the user questioning what is going on, to them it appears as though the login attempt has failed and they need to resubmit.

### Expected behaviour
When triggering the redirect off of the sign-in flow, forms should go away and a loading splash should be displayed so the user is aware that something is happening.

### How to reproduce?
complete a sign in, any method, and before the redirect, notice the lack of loading state before navigation resolves.

### Context

- [x] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots
Here's a gif of what I mean, ignore the localhost:3001 stuff.
![Peek 2024-02-05 19-49](https://github.com/logto-io/logto/assets/3320430/bf8d7bcf-08e4-4ead-8837-67edaf4a9c49)

**Comment by darcyYe** [comment]
Hi @mrfrase3 , thanks for letting us know about the issue. We will fix this.

**Comment by simeng-li** [comment]
The fix has been released.  see https://github.com/logto-io/logto/pull/5774
