### ISSUE TITLE
bug: It conflicts with postgis

### ISSUE THREAD

**Issue by zuohuadong** [logto-io/logto#5428]
### Describe the bug

![image](https://github.com/logto-io/logto/assets/11203929/8c408607-cfa8-43d6-ba37-01274351b9d3)

PostGIS automatically generates a table: spatial_ref_sys. When I start logto, it says:

![image](https://github.com/logto-io/logto/assets/11203929/00f6ffcf-bb76-45ea-9641-6fd8b4876db8)

I can't delete this table.

### Context

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 1.13
  - [x] Container (Docker image)   
  - [ ] Raw Node.js

**Comment by wangsijie** [comment]
Can you try to seed the table in a local postgres database and then import data to PostGIS? The seed requires a clean database.

**Comment by wangsijie** [comment]
@zuohuadong I am closing this issue, feel free to reopen if you still have questions.
