### ISSUE TITLE
bug: CloudFlare Captcha in Admin Panel `is not valid JSON` error

### ISSUE THREAD

**Issue by shadeov** [logto-io/logto#5429]
### Describe the bug
CloudFlare sometimes triggers a captcha verification, and this captcha can also be present at the API node. Therefore, sometimes an error like `Unexpected token '<', "<!DOCTYPE "... is not valid JSON` appears in the admin panel.

### Expected behavior
It would be great if the error handler could recognize this and open the captcha within a "modal" window, for example.

### How to reproduce?
Enable "Under Attack Mode" in CloudFlare, open the admin panel using a VPN/Proxy. The API and Admin panel should be on different subdomains.

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [x] Raw Node.js

### Screenshots
![image](https://github.com/logto-io/logto/assets/144587546/f8394a06-3ec9-4174-8807-5032314790e9)

**Comment by Tc-001** [comment]
Cloudflare has a solution!
https://blog.cloudflare.com/integrating-turnstile-with-the-cloudflare-waf-to-challenge-fetch-requests

I am unsure if it works across domains though, it maybe does? The documentation is not that clear. 
But if it does and gets implemented then logto can be protected with an aggressive WAF  rule but also let the admin console still access it.

**Comment by wangsijie** [comment]
@shadeov I am closing this issue, feel free to reopen if you still have questions.
