### ISSUE TITLE
bug: First access registration issues in private network deployment environment

### ISSUE THREAD

**Issue by sailwebs** [logto-io/logto#5477]
### Describe the bug

In a private network deployment environment, due to isolation from the public network, password verification fails when a registered user is accessed for the first time.

### Possible Causes
/logto/packages/toolkit/core-kit/src/password-policy.ts

These codes rely on a public network environment, which may cause verification failure.

![image](https://github.com/logto-io/logto/assets/804734/c2ea77f7-0931-43ba-8d66-2760ed662581)

![image](https://github.com/logto-io/logto/assets/804734/1d988869-d0f3-4c13-a3e3-1d39839ac119)

**Comment by xiaoyijun** [comment]
Hi @sailwebs , thank you for reporting this issue. We will take a look later. 
Before we have a solution, you can bypass this error by configing the password policy directly in your database (see `sign-in-experiences` table), the policy config is as follows:
```
{
    "length": {
      "min": 8,
      "max": 256
    },
    "characterTypes": {
      "min": 1
    },
    "rejects": {
      "pwned": true,
      "repetitionAndSequence": true,
      "userInfo": true,
      "words": []
    }
  }
```

**Comment by xiaoyijun** [comment]
@gao-sun maybe we need to improve this mechanism.

**Comment by xiaoyijun** [comment]
Hi @sailwebs , after our discussion, the initial solution is to support setting a password policy when executing the seed database command, but we currently have no plans to make related updates in the near future. If you have time, feel free to contribute your code. 😎

**Comment by wangsijie** [comment]
I can take a look and see if we can turn it off

**Comment by sailwebs** [comment]
> I can take a look and see if we can turn it off

thanks

**Comment by wangsijie** [comment]
You can run this SQL command after seeding the database and before running Logto:

```sql
UPDATE sign_in_experiences
SET password_policy = password_policy || 
'{
  "rejects": {
    "pwned": false
  }
}'::jsonb
WHERE tenant_id = 'admin'
```

This will turn off the pwned check.

I am closing this, feel free to reopen if you have any further questions.
