### ISSUE TITLE
bug: Inconsistency in Storing MFA Setup Skip Flag between custom_data and logto_config Fields

### ISSUE THREAD

**Issue by glzjin** [logto-io/logto#5482]
### Describe the bug

There's an inconsistency in the Logto repository regarding where the flag for skipping multi-factor authentication (MFA) setup is stored. Specifically:

- In one instance, the flag is stored in the `custom_data` field as seen in the code [here](https://github.com/logto-io/logto/blob/172411946a3a39bc412c802855b7ab8b97810264/packages/core/src/routes/interaction/verifications/mfa-verification.ts#L144).
- In another instance, the flag is mentioned to be stored in the `logto_config` field, as indicated [here](https://github.com/logto-io/logto/blob/172411946a3a39bc412c802855b7ab8b97810264/packages/core/src/routes/interaction/actions/submit-interaction.ts#L123).
- The logic for checking the flag uses `logto_config`, as seen [here](https://github.com/logto-io/logto/blob/172411946a3a39bc412c802855b7ab8b97810264/packages/core/src/routes/interaction/verifications/mfa-verification.ts#L129).

This inconsistency could lead to confusion or incorrect behavior in how MFA setup skipping is handled.

### Expected behavior

The codebase should consistently use either `custom_data` or `logto_config` for storing and checking the flag that indicates whether a user has opted to skip MFA setup. This consistency is crucial for the reliability and security of the MFA feature.

### How to reproduce?

1. Examine the use of `custom_data` for storing the MFA skip flag [here](https://github.com/logto-io/logto/blob/172411946a3a39bc412c802855b7ab8b97810264/packages/core/src/routes/interaction/verifications/mfa-verification.ts#L144).
2. Note the mention of `logto_config` for storing the same flag [here](https://github.com/logto-io/logto/blob/172411946a3a39bc412c802855b7ab8b97810264/packages/core/src/routes/interaction/actions/submit-interaction.ts#L123).
3. Observe the use of `logto_config` for checking the flag [here](https://github.com/logto-io/logto/blob/172411946a3a39bc412c802855b7ab8b97810264/packages/core/src/routes/interaction/verifications/mfa-verification.ts#L129).

### Context

- [x] Logto Cloud
- [x ] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [x] Raw Node.js

### Screenshots

![image](https://github.com/logto-io/logto/assets/7975407/5c84f112-c9a3-4101-9aff-ba309ccf5c6a)

![image](https://github.com/logto-io/logto/assets/7975407/b893e238-bfcb-4e2b-b655-425d0b310ec1)

**Comment by darcyYe** [comment]
@wangsijie would you like to take a look?
