### ISSUE TITLE
feature request: Signing out user after deletion/suspension from Admin. 

### ISSUE THREAD

**Issue by abrahimzaman360** [logto-io/logto#5572]
### What problem did you meet?
I want the user to be signed out from the app if he/she has been deleted from the Console (admin).
isAuthenticated always shows true, even account is deleted!

**Comment by wangsijie** [comment]
The local auth state will stay online, but the user is unable to grant access tokens anymore. By deleting, Logto will revoke refresh tokens of the user.

You can use [Webhooks](https://docs.logto.io/docs/recipes/webhooks/) to customize the behavior.

**Comment by Joozty** [comment]
@wangsijie I quite don't understand how to use webhooks to customize behavior.

Additionally, I've run into a similar problem. When a user is deleted, I can distinguish this case and clear the cookies on my site, but when I click the sign-in button again, it returns an error callback_`uri_verification.error_found`. Logto still thinks I want to sign in with the same user, which is not true. I want to show the user the sign-in screen and give them the possibility to use a different account or create a new one, but I don't have control over clearing the cookies on the Logto domain auth. Hopefully, this makes sense.

![image](https://github.com/logto-io/logto/assets/12775440/d0f7f8fd-9b36-47b6-97f4-44aa07a3c93e)
