### ISSUE TITLE
oauth2.0 connector: support parse nested userInfo in Profile Map config

### ISSUE THREAD

**Issue by keisni** [logto-io/logto#5580]
### What problem did you meet?
my identity provier, reponse user info like this:
{
  "code": 10000,
  "data": {
	"uid": "alice"
  },
  "msg": success
}
i tried to config Profile Map like this:
{
  "id": "data.uid"
}
but it doesn`t work.

### Describe what you'd like Logto to have
Support Profile Map config in this case.
Or please tell me how to do this if this feature alreay exists.

**Comment by ignasbernotas** [comment]
This is preventing me from using Zendesk as one of the connectors, they nest their user response in a "user" object.

**Comment by devtekve** [comment]
> This is preventing me from using Zendesk as one of the connectors, they nest their user response in a "user" object.

Same issue for me here, except with Patreon. My workaround was to setup a small proxy to flatten the userinfo and configure logto to go to it. 

For reference, I found your post on discord https://discord.com/channels/965845662535147551/1272623933186637997 
and I made mine too https://discord.com/channels/965845662535147551/1274821740840878120
