### ISSUE TITLE
bug: Expo Application not issuing refresh_token even if "offline_access" scope is added

### ISSUE THREAD

**Issue by artalat** [logto-io/logto#5640]
### Describe the bug
Expo Application client does not issue refresh_token even if "offline_access" scope is added. Moreover, in the token response, the 'offline_access' scope is also ommitted.

### Expected behavior
The token response should have a refresh_token

### How to reproduce?

Token Request:

```
{
    "body": {
        "client_id": "09ubc2areumr5mm0kfwwq",
        "code": "BcNfIzLMlCr0x3F5geP-yh8aPnFiNtaQLvAzQ_4VsTX",
        "code_verifier": "TZDNmRGuAMJMosmMDsM7SI65wHqEtoXwfVhEpRz3AB1wa8uE80fCDXQBNrU1ENrHU5iH5eeMgCFwMcs3nHXHLqeMXYq3IhYKSI1xq8qKG8WWPD2WOLQMt3SdH02ypExT",
        "grant_type": "authorization_code",
        "redirect_uri": "io.app://auth/redirect",
        "scope": "openid offline_access"
    },
    "dataType": "json",
    "headers": {
        "Content-Type": "application/x-www-form-urlencoded"
    },
    "method": "POST"
}
```

Token Response:

```
{
    "access_token": "84prydQ74uh9DOloIIPghbZqR-0aVpSqvu5IBYM_xik",
    "expires_in": 3600,
    "id_token": "eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCIsImtpZCI6IjFMNHVHcTQwWkV3R1VDb1M4RUp0dWZQNURaNDJXWG55UmRpTXNSMDl3eU0ifQ.eyJzdWIiOiJibm1lbzduN3p3ZWIiLCJhdF9oYXNoIjoiRl8tSWUzUEI1WUNtX2xfUnAzUEs0cDBIeFUtVmxwX1kiLCJhdWQiOiIwOXViYzJhcmV1bXI1bW0wa2Z3d3EiLCJleHAiOjE3MTI0MzEzNjAsImlhdCI6MTcxMjQyNzc2MCwiaXNzIjoiaHR0cHM6Ly9jYzUwLTEyNS0yMDktNzMtMjQ3Lm5ncm9rLWZyZWUuYXBwL29pZGMifQ.rXu208JEk6Ps5FqkO58YZ_72eumV1N4SzAVYNV5VnqZqgK5DGU-uVSp4vPv2Wc3_PfO9kWTry_M52TqIwk1RPXRYlqXl6WDM9N5L2XuDiNJlgtjNkjcbnHcugbrs5rWt",
    "scope": "openid",
    "token_type": "Bearer"
}
```

### Context
- Self-hosted, Logto version = ghcr.io/logto-io/logto

**Comment by simeng-li** [comment]
Hi there. Are you using the Logto React Native (Expo) SDK for your Expo client? I've tested it briefly with the sample project provided under the SDK and it functions as expected. 

<img width="154" alt="image" src="https://github.com/logto-io/logto/assets/36393111/3f732652-225f-4277-9082-ec268e67924f">

Also, you could check the initial authorization request to see whether the `offline_access` scope is properly sent.

**Comment by artalat** [comment]
Hi, no we are not using Logto SDK as we needed to implement some additional logic on the client side. But I did however test on postman. I have shared my request and response in the main description

**Comment by artalat** [comment]
For reference, I'm attaching postman screenshots.

# Request

<img width="598" alt="Screenshot 2024-04-08 at 10 29 18 AM" src="https://github.com/logto-io/logto/assets/295630/b3bcfa03-bd5f-464c-80ce-92e7749c6d16">

# Response

<img width="586" alt="Screenshot 2024-04-08 at 10 29 42 AM" src="https://github.com/logto-io/logto/assets/295630/b783c18a-ad2f-4b71-978e-01cbe40c6893">

<img width="577" alt="Screenshot 2024-04-08 at 10 29 53 AM" src="https://github.com/logto-io/logto/assets/295630/5b1c0274-a41e-48a0-8c6e-87d8af1186fb">

**Comment by simeng-li** [comment]
Can you share the[ authorization request ](https://docs.expo.dev/versions/latest/sdk/auth-session/#authrequest)body as well? Just to make sure the offline_access scope is included in the auth request not just the following token exchange request.

**Comment by artalat** [comment]
I have created a demo app for your to test.

Here is the auth endpoint called by the app:

```
https://nci2y1.logto.app/oidc/auth?code_challenge=wqjinZnJvRaB2DZzgVZBu_mkQZ0xKRtvtY-UYfFu83o&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A19007&client_id=wee3ntpyuq5nq7tsmts8g&response_type=code&state=lUmeHNgNAL&scope=openid%20profile%20email%20offline_access
```

Response from auth endpoint

```json
{
  "type": "success",
  "error": null,
  "url": "http://localhost:19007/?code=RfgnYkG8LoILR_xmW-LqLkvHUDBJMS1X-0jfNYbp1bM&state=lUmeHNgNAL&iss=https%3A%2F%2Fnci2y1.logto.app%2Foidc",
  "params": {
    "code": "RfgnYkG8LoILR_xmW-LqLkvHUDBJMS1X-0jfNYbp1bM",
    "state": "lUmeHNgNAL",
    "iss": "https://nci2y1.logto.app/oidc"
  },
  "authentication": null,
  "errorCode": null
}
```

Payload for token endpoint

```
grant_type=authorization_code&client_id=wee3ntpyuq5nq7tsmts8g&scope=openid%20profile%20email%20offline_access&code_verifier=UZYnfbGahiCPPH5MDQJcFSK6rs9f9MEUJIkI7rPcHs9Zva1Pr3lj1UDnmC8mqKv7bHY1VXeBCz4Nk8mMV1DK7ICgVlYAXZdrwEQJ73affMNOUpeu1WAWheBlG9WK51zB&redirect_uri=http%3A%2F%2Flocalhost%3A19007&code=fPivx0McMsy9_g3oe5DBXq19af-6JuvNsD9neNXqpmS
```

Token Endpoint Response

```json
{
  "accessToken": "uXQBIl7Vw91Hjy_iJBzusMNLiGqJmbKnQVufsGcID0n",
  "tokenType": "Bearer",
  "expiresIn": 3600,
  "scope": "openid profile email",
  "idToken": "eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCIsImtpZCI6InBWUnAtZUFZSlRGRm5RaGsweF9xZFJRTjVpR05LM1JTbUdKc0E5QzFHRDAifQ.eyJzdWIiOiJlcnRiZmluNHJmb2IiLCJuYW1lIjpudWxsLCJwaWN0dXJlIjpudWxsLCJ1cGRhdGVkX2F0IjoxNzEyOTE3ODE2MzE1LCJ1c2VybmFtZSI6InRlc3QiLCJjcmVhdGVkX2F0IjoxNzAyMzk0NjAyMjY2LCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6IkNVem9uaTRuWWxKRGw3WVpVSGVDTFh0b21sVGNhMlduIiwiYXVkIjoid2VlM250cHl1cTVucTd0c210czhnIiwiZXhwIjoxNzEyOTIzODYwLCJpYXQiOjE3MTI5MjAyNjAsImlzcyI6Imh0dHBzOi8vbmNpMnkxLmxvZ3RvLmFwcC9vaWRjIn0.ztfzH-P4ThnloMTMHDnqSm52IA56SOfd6jIra3piBC3dSjgpObaBT6eeLTOiaNmv0sd0KgJYoaxVis6NsyicFp6Cqh7cjTWFvxMydiT7e0VU7j7BJre88r15gCsgRiLM",
  "issuedAt": 1712920260
}
```

## How to reproduce?
I have created a demo app here: https://github.com/artalat/expo-logto

Here are the credentials to test:

Username: test
Password: hYh2IOn-

Command to run in browser `yarn web`

**Comment by simeng-li** [comment]
I see. Looks like the prompt parameter is missing from the auth request.  Please check the [specs](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess). 
Could you add a `prompt=consent`  at your auth request, and try again?

**Comment by artalat** [comment]
Yes that was the problem. Adding prompt solved the issue. I have updated the example repo for future reference. 

Thanks for your help.
