### ISSUE TITLE
bug: Error in documentation on Microsoft Social Connector

### ISSUE THREAD

**Issue by KyvosUser** [logto-io/logto#5651]
Logto OSS, installed with npm.
When setting up Microsoft as a **social connector** the documentation ("check readme" on the connector's page) states that you should use the "Directory (tenant) ID" that you get from Azure AD (or Entra AD), which is a specific string that refers to your organization. This is wrong: to enable login with Microsoft accounts that are personal (e.g. Skype, Xbox, and consumer products) you should:

- Use the value **"consumers"**  as your Directory (tenant) ID, NOT you directory ID.

Source [https://github.com/microsoftgraph/msgraph-beta-sdk-go/issues/50#issuecomment-1047316410](https://github.com/microsoftgraph/msgraph-beta-sdk-go/issues/50#issuecomment-1047316410)

This was buried in a support request. For some reason it is almost impossible to find it in Microsoft docs. Just wanted to report it, bc your work is incredible, and I wanted to make onboarding as smooth as possible.

There are other minor edits or problems I encountered while testing Logto. I don't consider them bugs and I definitely don't want to litter the "issues" page with such minor observations. How would I go about reporting them to you?

Again, thanks for a great product!

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [x] Raw Node.js

### Screenshots

<img width="800" alt="Screenshot 2024-04-08 at 19 26 46" src="https://github.com/logto-io/logto/assets/98225063/a452993a-7bce-438e-b504-eabd9013bec1">

**Comment by simeng-li** [comment]
Hi, thanks for your reports we'll take a look at it. Please feel free to join our [discord channel](https://discord.com/invite/UEPaF3j5e6) and shoot any questions you may have, we would love to help.
