### ISSUE TITLE
bug: Local machine-to-machine permissions are different from those in the cloud

### ISSUE THREAD

**Issue by cuixiaorui** [logto-io/logto#5665]
I was deploying locally via docker. 
I found that the logto api I created was never accessible, and I got a permissions problem.
I'm not sure if it's just me or if there's a bug in the existing program.
I'm not sure if it's just me or a bug in the existing program, because I've tried the same procedure on the cloud and it's not a problem.
I need your help, thank you very much!

My Steps:
1. create a  logto api   http://localhost:3001/api
<img width="1247" alt="image" src="https://github.com/logto-io/logto/assets/12064746/cdcb6514-dc90-4f45-99c8-db397d7c2602">

2. create  earthworm-m2m 
<img width="1246" alt="image" src="https://github.com/logto-io/logto/assets/12064746/82308e48-febd-42ef-940f-210a0fb57d75">

3. Permissions assigned. role created.

<img width="1197" alt="image" src="https://github.com/logto-io/logto/assets/12064746/c07dfecc-4f6f-47d6-9947-9738b99013fc">
<img width="1260" alt="image" src="https://github.com/logto-io/logto/assets/12064746/53ce3ba7-53e4-4a07-8766-65de450ea5ce">

4. get token

<img width="1491" alt="image" src="https://github.com/logto-io/logto/assets/12064746/fe1d974b-228f-4935-8183-fb97c047ba13">

token：eyJhbGciOiJFUzM4NCIsInR5cCI6ImF0K2p3dCIsImtpZCI6InJ4MHUxdzQ1bkYyYzNrZ24wWVNLdjRqaGxQUlFDRllBbjdWNHd6d2Q0Z0UifQ.eyJqdGkiOiJYQjB6dHBIU0ZmRnR5SGJOTU1xY3YiLCJzdWIiOiJ5ZGRpdGYyZHRnd3p5ZTlsaWtwMWkiLCJpYXQiOjE3MTI2NjI5NzIsImV4cCI6MTcxMjY2NjU3Miwic2NvcGUiOiJhbGwiLCJjbGllbnRfaWQiOiJ5ZGRpdGYyZHRnd3p5ZTlsaWtwMWkiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDEvb2lkYyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMS9hcGkifQ.vojaMk9PD7--QhUYLJWWGPLa_ilHKoiChCSGd7pmZEb5So2-Kki-oY8khwyEyN-VxFzc4_jWciAKCaH-3eS9rBX0Xqg5YqlqErQ4N6d-wsy5ZGa9acYSad4QkJWKNEyL

this is a content of token：
<img width="1343" alt="image" src="https://github.com/logto-io/logto/assets/12064746/448207e0-e38b-4508-b4de-9f270627569e">

5. get `/api/applications` api

<img width="1432" alt="image" src="https://github.com/logto-io/logto/assets/12064746/a10895c5-71e1-4fb1-92d9-c7aab54bb4c1">

Finally, tell me:  Unauthorized. Please check credentials and its scope.

## BUT

I have no problem using the same operation on the cloud side

But on the cloud side, I didn't create a new logto api.

Instead, I used the default Logto Management API

<img width="1266" alt="image" src="https://github.com/logto-io/logto/assets/12064746/d8aca3b7-728b-4f5a-aed8-284236e35455">

I'm not sure if it's just me or if it's a logto bug.

I need help from the logto team thank you very much!!!!

**Comment by simeng-li** [comment]
Hi @cuixiaorui Logto management APIs are reserved APIs. The identifier is shown above `https://default.logto.app/api`. Please use that as the resource identifier in your access token request.

**Comment by xiaoyijun** [comment]
Hi @cuixiaorui , your question seems kinda similar to #5607 . There's a detailed setup process outlined in that issue that you might find helpful to check out.

**Comment by cuixiaorui** [comment]
thx very much @xiaoyijun @simeng-li 
I found the problem.
<img width="866" alt="image" src="https://github.com/logto-io/logto/assets/12064746/6de77458-f171-461c-9bf8-7bed92e07e89">
`resouce` should not change
