### ISSUE TITLE
bug:  It doesn't work correctly in Electron with vue

### ISSUE THREAD

**Issue by Liszt-Fly** [logto-io/logto#5706]
### Describe the bug

It works not correctly in electron with vue. In fact, we can logged in and logged out ,but the state doesn't change. For example ,even though i logged in ,the `isAuthenticated` is stilled false. I find it doesn't store in local storage correctly. 

### Expected behavior
after logging, the local storage and the cookie should contains data 
### How to reproduce?
just need do as the vue documentation. 

### Context

- [x ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

**Comment by boustanihani** [comment]
Having the same issue with a SPA App using hash based routing.

Redirect URIs and Post sign-out URIs all point to "/".
