### ISSUE TITLE
bug: Username is empty and no prompt to modify username when creating a new user via email

### ISSUE THREAD

**Issue by cuixiaorui** [logto-io/logto#5707]
Version: v1.15.0

Description: When creating a new user through the email registration process, the following issues were observed:

Empty Username: Upon completing the email registration flow, the system does not assign or prompt for a username, resulting in the username field being empty for newly created users.
Missing Username Modification Popup: Typically, if a user does not set a username during registration, the system should prompt with a popup to enter or modify the username. However, this popup does not appear when registering via email.
In contrast, when registering through the username and password method, neither of these issues occurs. Users can set their username normally, and the username modification popup appears when necessary.

Steps to Reproduce:
Click on the register button and choose to register via email.
Enter the email address, receive and input the verification code.
Complete the registration process and observe whether the username is set and if the username modification popup appears.
Expected Result: Whether registering via email or username and password, users should have a non-empty username after completing the registration process, and the system should prompt for username modification when needed.

Actual Result: When registering via email, the username remains empty, and no username modification popup appears.

<img width="1346" alt="image" src="https://github.com/logto-io/logto/assets/12064746/c521b93d-6fb2-401f-b0f0-93bec79e7368">

<img width="1253" alt="image" src="https://github.com/logto-io/logto/assets/12064746/69db0a7e-7d38-4abb-ba41-a6bb6299085b">

**Comment by simeng-li** [comment]
Users may use the email + password sign-in method directly based on your current SIE settings.  
Is there any particular reason you would like to make the username mandatory for email-registered users?

**Comment by baboon-king** [comment]
> Users may use the email + password sign-in method directly based on your current SIE settings. Is there any particular reason you would like to make the username mandatory for email-registered users?

The general idea is to give users a recognizable logo when they register.
Using Github as an example: my e-mail address is xxx.@gmail.com, but my public username is "baboon-king", and my nickname is "BaboonKing".

**Comment by simeng-li** [comment]
You may implement a user profile fulfilling page on your app side using Logto management API.  Please check this [doc](https://docs.logto.io/docs/recipes/user-profile/) for reference.

**Comment by simeng-li** [comment]
Profile fulfillment on registration has been added to the [roadmap](https://logto.productlane.com/roadmap).
