### ISSUE TITLE
feature request: Impersonation Functionality

### ISSUE THREAD

**Issue by jafarijason** [logto-io/logto#5722]
I hope this message finds you well. Firstly, I want to express my sincere gratitude for the exceptional product you've developed. LogTo has proven to be an invaluable tool for our team, revolutionizing the way we handle logging processes.

I have another feature request that I believe could significantly enhance our administrative capabilities within the platform. It would be immensely beneficial to introduce an impersonation functionality, allowing administrators to log in on behalf of users when necessary.

This feature could be implemented through a simple toggle switch in the admin console, giving administrators the ability to enable or disable impersonation as needed. When enabled, administrators would be able to select a user from a list and seamlessly log in to the platform using their credentials. This would provide invaluable support for troubleshooting, user assistance, and administrative tasks that require direct access to user accounts.

By incorporating impersonation functionality into LogTo, you would not only empower administrators with greater control and flexibility but also streamline support processes and enhance overall user experience.

I believe this feature would be a game-changer for our team and would greatly appreciate your consideration in implementing it. Thank you for your continued dedication to innovation and excellence.

**Comment by charIeszhao** [comment]
Admin users can go to "user management" page and reset any user's password. Then the admin can use the new password to sign-in on behalf of the user. Would this be something that can work for your cases?

**Comment by jafarijason** [comment]
@charIeszhao, No I dont belive reset password might be the case fo 2 reasons, first what if user only used social login, second if admin change the password after that user again need to change password, also with impersoate functionality you can add a more filed like `impersonateId` that after that in app layer you can infore someone else is controlling user account and then can keep logs record for that on app side which will be a powerful tool.

**Comment by cayter** [comment]
Can refer to https://workos.com/docs/user-management/impersonation.

**Comment by marwie** [comment]
+1

**Comment by hybridherbst** [comment]
I'd also be interested in this. One important use case is debugging user access rights and so on. Resetting someone's password to investigate why that person can or can't see something doesn't sound good!

**Comment by ImSingee** [comment]
not stale

**Comment by wangsijie** [comment]
Update: we are working on this.

**Comment by wangsijie** [comment]
Update: will be ready in July.

**Comment by jonsamwell** [comment]
Hi @wangsijie this will be an awesome feature! How is it going to work?
Will there be an additional claim on the jwt with the user id of the user
being impersonated and the expiry time?

**Comment by wangsijie** [comment]
You can reuse the feature of "custom JWT", check this file to learn more: https://github.com/logto-io/rfcs/blob/master/draft/0005-impersonation.md

**Comment by ianrtracey** [comment]
+1 would love this as well

**Comment by wangsijie** [comment]
🚀 https://docs.logto.io/docs/recipes/impersonation/
