### ISSUE TITLE
feature request: deploy on vercel

### ISSUE THREAD

**Issue by tahaghafuri** [logto-io/logto#5768]
### What problem did you meet?
Support For Deploy Logto On Vercel

### Describe what you'd like Logto to have
Can install logto in vercel

**Comment by charIeszhao** [comment]
I have tried it personally, but it would be great if we can support it.

Have you tried it, though? Is there anything missing or not supported from our side?

**Comment by charIeszhao** [comment]
After some research and internal discussions, we are afraid that Logto cannot be deploy on Vercel, due to the technical limitations of Vercel platform. Therefore, I'm closing the ticket.

Please contact us if you have any thoughts. Thanks.
