### ISSUE TITLE
How to correctly access scopes in the nextjs server action situation

### ISSUE THREAD

**Issue by Haiananan** [logto-io/logto#5781]
I have configured the Config according to the document. 
```js
import { UserScope } from "@logto/next";
export const logtoConfig = {
  endpoint: "https://auth.aice.chat/",
  appId: "ej4nih6c4rm9jql612y5c",
  appSecret: "4BJEw1akolM3zYmTh2CDcfu7idlPXdS1",
  baseUrl: "http://localhost:3000", // Change to your own base URL
  cookieSecret: "T0UoSIiPUIs9pO8Mpu74tRtiWmadwBHI",
  cookieSecure: process.env.NODE_ENV === "production",
  scopes: [
    UserScope.CustomData,
    UserScope.Roles,
    UserScope.Email,
    UserScope.Phone,
    UserScope.Organizations,
    UserScope.OrganizationRoles,
    UserScope.Identities,
    "read:app",  // Already configured in the console.
  ],
  resources: ["http://no.com/api"],
};
```

However, when I call
```js
getLogtoContext(logtoConfig, {
    getAccessToken,
  });
```
The result does not include scopes.
I also tried using the `/oidc/me` API, but it didn't return any scopes either.
```js
{
    "sub": "y7xm0wj0jv2p",
    "name": "beyond",
    "picture": null,
    "updated_at": 1713879215359,
    "username": null,
    "created_at": 1713457888679,
    "email": "1628089948@qq.com",
    "email_verified": true,
    "phone_number": null,
    "phone_number_verified": false,
    "identities": {},
     ...
}
```
The above is my test case. How can I retrieve user information with the `scopes` parameter included?

**Comment by charIeszhao** [comment]
When you call
```ts
getLogtoContext(logtoConfig, {
  getAccessToken,
});
```
You can also pass the resource indicator as an additional param, like this:
```ts
getLogtoContext(logtoConfig, {
  getAccessToken: true,
  resource: 'http://no.com/api'
});
```

**Comment by Lennart01** [comment]
This could definitely be clarified in the docs.
I just stumbled across this as well while trying to get JWTs for my backend.

**Comment by wangsijie** [comment]
@Lennart01 An access_token is meant to be used by a specific audience, typically defined by the resource parameter. In your case, since no resource is specified, the default audience is the “Authorization Server.” As a result, this access_token is opaque to your client, meaning the client cannot access or retrieve the scopes associated with it. I am closing this, feel free to reopen if you have any further questions.
