### ISSUE TITLE
bug: Logto Webhooks not firing when using SSO

### ISSUE THREAD

**Issue by poster983** [logto-io/logto#5795]
### Describe the bug

When creating a Logto account using SSO (Tested with google workspace) the "Create Account" Webhook is not fired.  I have also tested creating an account manually 

### Expected behavior

I expect for my endpoint to be called when the user signin/up for the first time using enterprise SSO.  It works fine when creating it outside of sso. 

### How to reproduce?

1. Setup a google workspace enterprise SSO connection 
2. Setup a webhook that has event "Create new account" 
3. Try signing in with an SSO account that has not signed in before.

RESULT: Logto will not fire the webhook when signing in for the first time

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

**Comment by simeng-li** [comment]
Thanks for the report. We have identified the bug. A post-sign-in event was triggered instead of register. Working on a fix.
