### ISSUE TITLE
bug: useHandleSignInCallback not call

### ISSUE THREAD

**Issue by cuixiaorui** [logto-io/logto#5806]
Hello, I would like to know what could be the reason why useHandleSignInCallback does not call back.

When I was testing with the online address, I realized that after the registration is done and my callback url is called, but the function useHandleSignInCallback is not executed, I don't know how to troubleshoot this problem.

I don't know how to troubleshoot this problem right now ! ！！

<img width="919" alt="image" src="https://github.com/logto-io/logto/assets/12064746/4dc540a2-de1d-4c0f-ae40-57e93625140c">

**Comment by narasimhajupally** [comment]
@cuixiaorui what was the issue? facing something similar.
