### ISSUE TITLE
bug: logto/rn is not compatible with latest expo version

### ISSUE THREAD

**Issue by JakimLi** [logto-io/logto#5890]
### Describe the bug
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: mstore_mobile@1.0.0
npm error Found: expo-web-browser@13.0.3
npm error node_modules/expo-web-browser
npm error   expo-web-browser@"~13.0.3" from the root project
npm error
npm error Could not resolve dependency:
npm error peer expo-web-browser@"^12.8.2" from @logto/rn@0.1.0
npm error node_modules/@logto/rn
npm error   @logto/rn@"*" from the root project

### Expected behavior
Expected to has no error .

### How to reproduce?
1. `npx create-expo-app@latest`
2. `npm i @logto/rn`

### Context
React native with Expo and expo dev client. with Container on my local machine

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

**Comment by xiaoyijun** [comment]
@gao-sun would you like to take a look?

**Comment by gao-sun** [comment]
opened a pull (the linked item above) for this
