### ISSUE TITLE
feature request: LOgto on .net core microservice using microUI demo

### ISSUE THREAD

**Issue by vitalybrandes** [logto-io/logto#5892]
Hi all, I have a question related to using LogTo in .net core microservice architecture  where I am also using microUI as containers. I am lost in using the API as a resource to get access token.  I need access token to be available for me in UI. Using access token I call multiple apis for the same ui. Does the access token for user have access to multiple resources and can I forward it to apis? If yes, is there any demo of code? For now I found that in razor pages example the access token only available in UI (page itself) what if I have DO service that need this token to contact api?

**Comment by xiaoyijun** [comment]
Cloese for duplicated of https://github.com/logto-io/logto/discussions/5893
