### ISSUE TITLE
bug: CORS errors in admin console

### ISSUE THREAD

**Issue by hades200082** [logto-io/logto#5896]
### Describe the bug
Running LogTo using Docker compose locally I get CORS errors in the admin console on localhost:3001 when it calls the API on localhost:3002.

### Expected behavior
Admin console should work without CORS errors

### How to reproduce?
1. Run docker compose in docker desktop on windows.
2. Go to http://localhost:3001/console/api-resources
3. See CORS error in browser console and no results shown

### Context

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = "latest" tag from docker
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

![image](https://github.com/logto-io/logto/assets/1023581/1c3e0557-27b3-4c9b-a2f2-b97c563d54ff)
![image](https://github.com/logto-io/logto/assets/1023581/130a652c-1d77-44e6-89f3-6b9cfb9b42b4)

**Comment by xiaoyijun** [comment]
Hi @hades200082 , could you please provide more information about how you start your Logto instance? Since the admin console is running at `localhost:3002` by default, but what I see from your snapshots is `localhost:3001`.

**Comment by hades200082** [comment]
I was just replying to close this issue when your reply popped in.

I was using .Net Aspire to replicate the docker compose so I could spin this up in my development stack. I had the two port bindings the wrong way around (I thought 3001 was admin console for some reason). It was odd that both ports were returning the admin console at that point.

The docker compose docs could be a little clearer around this, and around the ENDPOINT/ADMIN_ENDPOINT usage more generally (i.e. if you're running it in Coolify or with a proxy in front, etc.).

Anyway, I now have it working in Aspire using the following (in case anyone else finds this post and is trying the same)

```csharp
IResourceBuilder<IResourceWithConnectionString> db;
var dbPassword = builder.AddParameter("DatabasePassword", true);

var postgres = builder.AddPostgres("Database", password: dbPassword)
    .WithDataVolume("AppHost-PostgreSQL-data")
    .WithHealthCheck()
    .WithPgAdmin();

var logtopg = postgres.AddDatabase("logtodb").ExcludeFromManifest();
var pgEndpoint = logtopg.Resource.Parent.PrimaryEndpoint;
var logto = builder.AddContainer("Logto", "svhd/logto", "latest")
    .WithEntrypoint("sh")
    .WithArgs("-c", "npm run cli db seed -- --swe && npm start")
    .WithEnvironment("TRUST_PROXY_HEADER", "1")
    .WithEnvironment(async context => {
        var connectionStringExpression = ReferenceExpression.Create($"postgres://postgres:{logtopg.Resource.Parent.PasswordParameter}@{pgEndpoint.Property(EndpointProperty.Host)}:{pgEndpoint.Property(EndpointProperty.Port)}/logtodb");
        var cs = await connectionStringExpression.GetValueAsync(context.CancellationToken);
        context.EnvironmentVariables["DB_URL"] = new HostUrl(cs);
    })
    .WithEndpoint(port: 3001, targetPort: 3001, scheme: "http", name: "auth")
    .WithEndpoint(port: 3002, targetPort: 3002, scheme: "http", name: "https")
    .WithEnvironment("ENDPOINT", "")
    .WithEnvironment("ADMIN_ENDPOINT", "")
    .ExcludeFromManifest()
    .WithReference(logtopg)
    .WaitOn(logtopg);
```

I'm using David Fowlers [WaitForDependenciesAspire](https://github.com/davidfowl/WaitForDependenciesAspire) repo as an example for the `.WithHealthCheck()` and `.WaitOn(logtopg)` elements.
