### ISSUE TITLE
feature request: MFA for admin UI?

### ISSUE THREAD

**Issue by CatStudioApp** [logto-io/logto#5916]
### What problem did you meet?

The auth method of the admin UI is just username and password, which is not strong enough.

### Describe what you'd like Logto to have

It would be great to add MFA like email verification code and or Passkey / Yubikey.

**Comment by darcyYe** [comment]
Which version are you using? Cloud or OSS?

**Comment by darcyYe** [comment]
If you are a OSS user, you can direct update your DB SIE config to achieve this. Also, in order to benefit all Logto OSS users, you are very welcomed to contribute this option. The idea is to add a CLI option when seeding the DB.

**Comment by CatStudioApp** [comment]
> If you are a OSS user, you can direct update your DB SIE config to achieve this. Also, in order to benefit all Logto OSS users, you are very welcomed to contribute this option. The idea is to add a CLI option when seeding the DB.

Yes. I'm an OSS user.
Oh I see! Thanks!

**Comment by CatStudioApp** [comment]
> your DB SIE config to achieve this

I'd like to contribute!
Btw, that's SIE?
