### ISSUE TITLE
feature request: Ruby on Rails SDK?

### ISSUE THREAD

**Issue by imWildCat** [logto-io/logto#5971]
### What problem did you meet?

I have a project with Ruby on Rails and I'd like to use Logto in it.

### Describe what you'd like Logto to have

Similar to <https://docs.logto.io/quick-starts/php/>, we could have a rails based SDK

**Comment by wangsijie** [comment]
Thanks for the suggestion. Feel free to submit a PR.

**Comment by imWildCat** [comment]
which repo do you recommend?

**Comment by wangsijie** [comment]
Thanks for your interest in contributing! Could you please prepare a draft in any of your public repos? Once that's done, we will create a new repo for Ruby.

**Comment by imWildCat** [comment]
I'm trying https://github.com/omniauth/omniauth_openid_connect first

If it doesn't work, I'll implement mime

**Comment by incorvia** [comment]
@imWildCat how'd it go?

**Comment by imWildCat** [comment]
haven't tried yet.

**Comment by gao-sun** [comment]
Check this out: https://github.com/logto-io/ruby

**Comment by imWildCat** [comment]
@gao-sun you're genius!
