### ISSUE TITLE
feature request: How to use custom jwt My deployed logto cannot be used, I deployed with docker，Is this feature for a fee?

### ISSUE THREAD

**Issue by mrchenxxx** [logto-io/logto#5972]
How to use custom jwt My deployed logto cannot be used, I deployed with docker，Is this feature for a fee?

**Comment by wangsijie** [comment]
Custom JWT is supported in OSS version, please check this doc: https://docs.logto.io/docs/recipes/custom-jwt/

It is available in the latest docker image, maybe you can try to update it in docker hub: svhd/logto:latest

**Comment by mrchenxxx** [comment]
It's the cache. Sorry
