### ISSUE TITLE
bug: Newly created user cannot be found by username via user search API

### ISSUE THREAD

**Issue by TheLonelinessOfHS** [logto-io/logto#5990]
### Describe the bug
Cannot find newly created user by username via /api/users

### Expected behavior
API returns users info

### How to reproduce?
1. Create a new user with username 'aaa' through the admin console.
2. Call the search API with parameters: search.name=aaa&mode.name=exact&isCaseSensitive=false
3. The API returns with status 200 but an empty array.
Please note: 1. My code works on older accounts but not newly created accounts. I didn't quite see their differences. 2. Not sure if it is caused by upgrades from older versions with DB migration.

Please see below my code:

```
const params = new URLSearchParams([
                ['search.name', username],
                ['mode.name', 'exact'],
                ['isCaseSensitive', 'false'],
            ]);

            const resp = await fetch(
                `${this.#logtoEndpoint}/api/users?` + params,
                {
                    method: 'GET',
                    headers: {
                        'Authorization': `Bearer ${this.#token}`,
                    },
                }
            );

            if (resp.status === 200) {
                const data = await resp.json();
                if (Array.isArray(data)) {
                    for (const obj of data) {
                        if (obj.username?.toLowerCase() === username.toLowerCase()) {
                            return obj.id ? obj.id : undefined;
                        }
                    }
                }

                return undefined;
            }

```
### Context
Self-hosted, Logto version = 1.17.0 as well as the previous version 1.16.0

**Comment by wangsijie** [comment]
The field `name` is more like "nick name" actually, it is different from `username`. Could you please try to change `search.name` to `search.username` and see if it works?

**Comment by TheLonelinessOfHS** [comment]
> The field `name` is more like "nick name" actually, it is different from `username`. Could you please try to change `search.name` to `search.username` and see if it works?

Wow, thanks! It's my fault.
