### ISSUE TITLE
feature request: a wrong part of the doc of Nuxt SDK

### ISSUE THREAD

**Issue by gaojunran** [logto-io/logto#6006]
https://docs.logto.io/quick-starts/nuxt/#get-user-information

<img width="708" alt="image" src="https://github.com/logto-io/logto/assets/121377123/2a729e3d-c226-4722-93ed-fe4c3cec3cbd">

I found that `[UserScope.email, UserScope.phone]` doesn't work in Nuxt.

The type definition infers `UserScope.Email` instead of `UserScope.email`, but it still doesn't work.

I've tried many times, and after searching for NextJS doc, I found that it should be `["email", "phone"]`.

I wonder if the usage in the doc is right. If not, please correct it.

The document of Nuxt SDK is a little confusing, for me who have much experience in frontend programming, it's a great effort to totally figure it out. In comparison, the document of Nextjs SDK is much better.

**Comment by lyykfi** [comment]
Hey.

I have faced the problem as well.
I was used this way to fix it 

import { UserScope } from "@logto/vue";
  scopes: [
        UserScope.CustomData,
        UserScope.Roles,
        UserScope.Email,
        UserScope.Phone,
        UserScope.Organizations,
        UserScope.OrganizationRoles,
        UserScope.Identities,
      ],

**Comment by gaojunran** [comment]
> Hey.
> 
> I have faced the problem as well. I was used this way to fix it
> 
> import { UserScope } from "@logto/vue"; scopes: [ UserScope.CustomData, UserScope.Roles, UserScope.Email, UserScope.Phone, UserScope.Organizations, UserScope.OrganizationRoles, UserScope.Identities, ],

It works, thank you!
It seems there's something wrong with Nuxt SDK, so Vue SDK is borrowed.

**Comment by wangsijie** [comment]
https://github.com/logto-io/js/pull/742
