### ISSUE TITLE
bug: authorization code not found

### ISSUE THREAD

**Issue by lyykfi** [logto-io/logto#6007]
Hey everyone.
I've deployed my project to a prod env and I've faced the errors.
Could you advice please, whata I am doing wrongly :-)

{
  "key": "ExchangeTokenBy.AuthorizationCode",
  "result": "Error",
  "error": "{\"stack\":\"InvalidGrant: invalid_grant\\n    at authorizationCodeHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/grants/authorization_code.js:42:11)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async callTokenHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:70:7)\\n    at async allowedGrantTypeCheck (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:53:7)\\n    at async supportedGrantTypeCheck (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:45:7)\\n    at async stripGrantIrrelevantParams (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:33:7)\\n    at async auth (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:257:9)\\n    at async loadClient (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:152:9)\\n    at async setWWWAuthenticateHeader (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:43:11)\\n    at async selectiveBody (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/selective_body.js:49:5)\\n    at async noCache (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/no_cache.js:3:3)\\n    at async cors (/etc/logto/node_modules/.pnpm/@koa+cors@4.0.0/node_modules/@koa/cors/index.js:105:16)\\n    at async errorHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/error_handler.js:26:7)\\n    at async ensureSessionSave (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/initialize_app.js:52:7)\\n    at async contextEnsureOidc (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5)\\n    at async file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/initialize_app.js:222:5\",\"message\":\"invalid_grant\",\"allow_redirect\":true,\"name\":\"InvalidGrant\",\"error\":\"invalid_grant\",\"status\":400,\"statusCode\":400,\"expose\":true,\"error_description\":\"grant request is invalid\",\"error_detail\":\"authorization code not found\"}",
  "ip": "89.223.70.114",
  "userAgent": "node",
  "applicationId": "ev8tg4zaxm2sujedns7os",
  "params": {
    "code": "8nw03ZceGaggubS_cRkn1SpflLdmkw1b17-3vSH4t03",
    "client_id": "ev8tg4zaxm2sujedns7os",
    "grant_type": "authorization_code",
    "redirect_uri": "***/callback",
    "code_verifier": "-tAHJS6BVQ_HrfsvI2c1vKZWBp_fq2m1OzsZa2e8zasTX-9UfJ_J6-PESarh0IRpiCdhFY4RlBHulprk6sdCOQ"
  },
  "tokenTypes": []
}

**Comment by cheezone** [comment]
I also encountered this problem. How did you solve it? @lyykfi
