### ISSUE TITLE
bug: Logto sign in flow crashes on Safari 17+, a show stopper bug

### ISSUE THREAD

**Issue by xiaohanyu** [logto-io/logto#6019]
### Describe the bug

Logto sign in flow with next.js pages router (no server actions) crashes on Safari 17+

### Expected behavior

Logto should be able to sign in or give user a warning if user use Safari 17+

### How to reproduce?

I've created a dedicated repo for showing the live demo, screenshots and reproducible steps for this bug, check it here: https://github.com/xiaohanyu/logto-next-safari-demo

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version: svhd/logto:1.16
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

NA

**Comment by wangsijie** [comment]
I just tested in Safari 17.5, and every thing worked fine.

I am closing this, feel free to reopen if you have any further questions.

**Comment by xiaohanyu** [comment]
@wangsijie did you test on self hosted logto intance? 

For me, logto cloud works well however self hosted version don't work.

**Comment by wangsijie** [comment]
@xiaohanyu I just did a test in self-hosted logto, and it worked.

**Comment by xiaohanyu** [comment]
@wangsijie this is weird. OK then I will verify it again. Maybe this is due to some deployment issue. Thanks!
