### ISSUE TITLE
bug: (Nuxt) no isAuthentiated?

### ISSUE THREAD

**Issue by moshetanzer** [logto-io/logto#6056]
### Describe the bug

Hi,

In the Nuxt docs there is no explanation of howe to check if a route has been authenticated. 

is this the way to authenticate in middleware?

export default defineNuxtRouteMiddleware(async () => {
  const user = useLogtoUser()
  if (!user) return navigateTo('/sign-in')
})

Update: this doesnt work - this causes infinite redirect...

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

**Comment by xiaoyijun** [comment]
@wangsijie could you please take a look about this issue?

**Comment by ysemennikov** [comment]
Hey @moshetanzer, you can try this:
```ts
const client = useLogtoClient();
isAuthenticated = await client.isAuthenticated()
```

**Comment by wangsijie** [comment]
Could you please try the solution mentioned above? If you have any further questions or if the issue persists, feel free to reopen this issue.
