### ISSUE TITLE
bug: cannot connect twitch oauth2

### ISSUE THREAD

**Issue by Satont** [logto-io/logto#6068]
### Describe the bug

Cannot add twitch as oauth2 connector. 
Getting just unhelpful error from logto patch request on login.

```json
{"message":"Error occurred in connector: {\"message\":\"{}\"}","code":"connector.general","data":{"message":"{}"}}
```

### Expected behavior

Should at least say what is wrong.
### How to reproduce?

Try to setup twitch. Also might be helpful some logging? I'm not sure logto have debug mode, but i do not see any erros in logto process console.

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

![image](https://github.com/logto-io/logto/assets/42675886/13aaf8ac-7587-4db5-a30f-ff97d159893a)

**Comment by xiaoyijun** [comment]
Hi @Satont , thanks for your feedback. You can try to checkout the interaction logs in the "Audit Logs" page to see if there is some related errors.

It's a good point that some useful error messages should be returned, and we're just working on it.

**Comment by Satont** [comment]
@xiaoyijun ok, found audit, thanks.

But it;'s still not helpful for me.

On login i got 2 those failed logs there.

![image](https://github.com/logto-io/logto/assets/42675886/3a8c9071-4274-4110-98fa-294be0cc425c)
![image](https://github.com/logto-io/logto/assets/42675886/2d039dcf-5a14-4158-8269-f16f0c5fdb0c)

**Comment by xiaoyijun** [comment]
Hi @Satont , since you're using the oss version, so you can try to modify the source code to print some logs.

<img width="1313" alt="image" src="https://github.com/logto-io/logto/assets/10806653/260e7e60-ab7c-47a6-a286-3931f46b9afc">
then rebuild the oauth2 connector by:
```
cd logto/packages/connectors/connector-oauth2
pnpm build
```
then restart your Logto instance and try to see the logs you just added.

**Comment by Satont** [comment]
@xiaoyijun cannot run `logto` via `npm init @logto`

Got error, even on clean database.

```
info ✖ Create tables
error error: role "logto_tenant_logto" already exists
```

**Comment by xiaoyijun** [comment]
Hi @Satont , ensure you've completely cleared all related data and roles from your database.
Or try to setup a new database.

**Comment by xiaoyijun** [comment]
Closing due to prolonged inactivity and lack of updates.
