### ISSUE TITLE
bug: Custom JWT Claims not being included in id token claims

### ISSUE THREAD

**Issue by jonsamwell** [logto-io/logto#6070]
### Describe the bug

Hi, I have added a simple script to add additional information to the jwt however, this is not appearing the token when received by the client app. I have added the 'custom_data' scope when logging in but still the additional data is not included.

```
const getCustomJwtClaims = async ({ token, context, environmentVariables }) => {
  return {
    someProperty: 123
  };
}
```

If I get the \`idToken' string value and inspect it using [jwt.io](http://jwt.io) I do not see the additional claims I added? Have I misunderstood how this feature works. From the documentation ([https://docs.logto.io/docs/recipes/custom-jwt/](https://docs.logto.io/docs/recipes/custom-jwt/)) I would expect the additional claims to be available to the client.

### Expected behavior

The additional claims are included in the JWT access token

### Context

Logto Cloud with Flutter SDK

- [X] Logto Cloud
- [ ] Self-hosted, Logto version =
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

**Comment by darcyYe** [comment]
Hi @jonsamwell , the custom JWT feature add additional claims to `access token` not `ID token`, since developers are actually using access token to access business services APIs.

**Comment by jonsamwell** [comment]
Hi @darcyYe, 

Thanks for the reply. I can get the accessToken in Flutter but there is nothing on it or no way of deserialising the `token` property.

![image](https://github.com/logto-io/logto/assets/3694497/e65d4dcf-031e-4b9b-8d57-778487bf441f)

I send the value of the idToken up to my API to authorised API calls should I be sending up the access token?

**Comment by xiaoyijun** [comment]
If you want to get JWT format access token, you get the access token by a specific resource indicator. please checkout https://docs.logto.io/quick-starts/flutter/#api-resources

**Comment by darcyYe** [comment]
I think @xiaoyijun was right. You should specify resource indicator when using `getAccessToken(resourceIndicator)` method in SDK(s) to make the access token JWT formatted, otherwise, an opaque access token should be returned and you need to call `/introscpection` endpoint to check/get details of an opaque token.

**Comment by jonsamwell** [comment]
Thanks for the clarification.
