### ISSUE TITLE
bug: 2FA Redirection Issue after Third-Party Login with Same Email

### ISSUE THREAD

**Issue by TheresaQWQ** [logto-io/logto#6111]
### Describe the bug
After registering an account on Logto and enabling 2FA, logging in using a third-party login with the same email does not redirect to the 2FA page after email verification.

### Expected behavior
The frontend should redirect to the 2FA page after verifying the email during third-party login.

### How to reproduce?
1. Register an account on Logto and enable 2FA.
2. Log out and try to log in using a third-party login (e.g., GitHub) with the same email.
3. Complete the email verification step.
4. Notice that the frontend does not redirect to the 2FA page.

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 1.17.0
  - [ ] Container (Docker image)
  - [x] Raw Node.js

### Screenshots

![image](https://github.com/logto-io/logto/assets/22370654/1fe9919e-0bcf-47f1-9271-9d145ead8095)
![image](https://github.com/logto-io/logto/assets/22370654/d503f23b-4e4b-401d-a3a5-654de855427b)

**Comment by darcyYe** [comment]
There seems to be some issues in your `reproduce` flow:
1. After the Logto OSS deployment, the first registered user serves as Logto's Administrator. It seems that the only available login method for the Administrator is `username` + `password`.
2. In Step 2, you mentioned "sign in with third-party login with the 'same email'". However, "email" is not mentioned in either Steps 1 or 2.
3. If you use the "third-party login" you mentioned and can successfully get the returned email, then email verification is not needed in the sign-in flow.
