### ISSUE TITLE
feature request: prefill email field on register screen

### ISSUE THREAD

**Issue by johngrimsey** [logto-io/logto#6194]
### What problem did you meet?
If there is a way to prefill an email field on the register form, I haven't found it yet. 

### Describe what you'd like Logto to have
This would be very helpful in reducing friction - some contexts a user will be responding to an invitation email. My app can then send them to the register page and has knowledge of their (verified) email address. The ability to prefill the register form with this email address (via a query parameter or a POST?) would be very useful to me.

Thanks!

**Comment by johngrimsey** [comment]
Commenting to keep alive!

**Comment by johngrimsey** [comment]
@wangsijie I think I'm requesting "progressive registration" – whereby an app will have verified an email as part of a user journey. Then all that is needed is for them to add a password to complete their registration. This is a low-friction registration experience for users, and pivotal in driving conversions.

**Comment by wangsijie** [comment]
This is a valid feature request, maybe something like "login_hint"?

**Comment by jonsamwell** [comment]
@wangsijie I believe this is already in the JS API under the property `loginHint` but it is not implemented  [see
](https://github.com/logto-io/js/blob/7c65c7ba52f73aeaee8a7e93a5d1f92ef5b63d54/packages/js/src/core/sign-in.ts#L41) It would be great to get it working!

**Comment by wangsijie** [comment]
@jonsamwell you are right, the server side haven't implemented it yet.

**Comment by wangsijie** [comment]
@xiaoyijun is working on this

**Comment by xiaoyijun** [comment]
Hi @johngrimsey , we will release this feature in the next version ( related PR: https://github.com/logto-io/logto/pull/6400).
For Cloud users, please stay tuned to our updates on Discord, where we will announce the feature’s availability on Cloud.

**Comment by johngrimsey** [comment]
Thanks @xiaoyijun
