### ISSUE TITLE
feature request: disable auto-prompt of 2fa setup for the first-time login

### ISSUE THREAD

**Issue by CatStudioApp** [logto-io/logto#6213]
### What problem did you meet?

For the first-time signup, is that a way to disable the prompt to set up 2fa?
It might be overwhelming for our users to set up 2fa for the first time.

### Describe what you'd like Logto to have

Add an option to disable prompt. Only for the 2nd time or set up it manually

**Comment by wangsijie** [comment]
You can choose either to disable the prompt or enable, but you can not disable for only first time at this moment. But I think this is a valid use case.

**Comment by CatStudioApp** [comment]
thank you, @wangsijie !

How to disable the prompt? I haven't found it

**Comment by CatStudioApp** [comment]
gentle ping @wangsijie 
<img width="1355" alt="image" src="https://github.com/user-attachments/assets/594a63fa-44df-49b0-96db-9ca6dc37712e">
how to disable it?

**Comment by wangsijie** [comment]
After verification, we confirm that this prompt cannot be turned off. This is a reasonable feature request, and we will add it to our roadmap.

**Comment by CatStudioApp** [comment]
@github-actions this issue is not stale.

**Comment by CatStudioApp** [comment]
no

**Comment by CatStudioApp** [comment]
not stale!

**Comment by wangsijie** [comment]
We are in active development of the feature Account API, and after this is ready, we'll revisit this feature request.

**Comment by wangsijie** [comment]
Hi @CatStudioApp, this is done in https://github.com/logto-io/logto/pull/6880
