### ISSUE TITLE
bug: Access Denied when uploading image/logo in onboarding flow

### ISSUE THREAD

**Issue by jnovermars** [logto-io/logto#6233]
### Describe the bug
As a new user i am starting the flow and in the flow where i can customize the sign-ing experience i would like to upload the logo of the company the tenant is for. When i upload the image i directly get a Access Denied error and i am singed out.

### Expected behavior
When i upload the image i can continue to customize the page

### How to reproduce?
Create new account and while in the onboarding flow upload a logo

### Context
-> Logto Cloud

### Screenshots
![Screenshot 2024-07-12 at 09 05 14](https://github.com/user-attachments/assets/e222b9a1-7a56-459d-9051-63adeee90232)
![Screenshot 2024-07-12 at 09 07 52](https://github.com/user-attachments/assets/db657b1a-3cd8-490e-a796-0f5613bf97e7)
![Screenshot 2024-07-12 at 09 08 03](https://github.com/user-attachments/assets/f1a91b65-fea7-47cd-b701-49630272273b)

**Comment by wangsijie** [comment]
I am unable to reproduce this issue. Could you please try again later or send an email to `contact@logto.io` with your account info?

**Comment by jnovermars** [comment]
i created a video on how to reproduce: https://youtu.be/a5Khh0sgCy0

**Comment by wangsijie** [comment]
Thanks for the video, it is very helpful.
