### ISSUE TITLE
bug: WordPress Logout error

### ISSUE THREAD

**Issue by EriTang** [logto-io/logto#6291]
{"code":"oidc.invalid_request","message":"请求无效","error":"invalid_request","error_description":"post_logout_redirect_uri not registered"}

 
![CleanShot 0006-07-21 at 11 02 36@2x](https://github.com/user-attachments/assets/8f55f4bd-a158-432d-8eab-bb1bb9fdaa38)

Version:latest
WordPress:6.6.0
Use OpenID Connect - Generic Client Last version

**Comment by xiaoyijun** [comment]
Hi @EriTang , have you pass the post_logout_redirect_uri to the sign out method ?

**Comment by xiaoyijun** [comment]
Hi @EriTang , when signing out, the page will be redriected to the home page.

**Comment by EriTang** [comment]
Sorry How to do?

> 你好@EriTang，您是否已将 post_logout_redirect_uri 传递给退出方法？

**Comment by EriTang** [comment]
Oh I have fix it
Thank you so much. 
> Hi @EriTang , when signing out, the page will be redriected to the home page.
