### ISSUE TITLE
bug: Can not use redirect URI other than /callback in next app

### ISSUE THREAD

**Issue by Klucherev** [logto-io/logto#6353]
### Describe the bug
I've changed default callback URI for my next.js app in LogTo admin console from http://localhost:4000/callback to  http://localhost:4000/auth/callback and get error 'redirect_uri did not match any of the client's registered redirect_uris'. Is it possible to use random callback uri with LogTo? Maybe i missed some settings in LogtoNextConfig?

### Expected behavior

- [ ] Logto Cloud
- [- ] Self-hosted, Logto version = 
  - [- ] Container (Docker image)
  - [ ] Raw Node.js

**Comment by MauruschatM** [comment]
Same issue for me. Still a bug?

**Comment by joaofaveri** [comment]
I'm encountering the exact same issue when trying to change the default callback URI. The error message 'redirect_uri did not match any of the client's registered redirect_uris' appears, preventing me from using a custom callback URI.

```json
{
"code": "oidc.invalid_redirect_uri",
"message": "`redirect_uri` não corresponde a nenhum `redirect_uris` registrado do cliente.",
"error": "invalid_redirect_uri",
"error_description": "redirect_uri did not match any of the client's registered redirect_uris",
"state": "***************************************",
"iss": "**************************************"
}
```

I'm wondering why this issue was closed without a clear solution or explanation. It would be incredibly helpful if someone could provide more information on how to properly configure custom callback URIs in Logto or if there are any known limitations.

**Comment by du2333** [comment]
I have the same issue. Even if I set the redirect Uri in the admin dashboard other than "/callback", the client sign in always set the redirect uri to "/callback", however I found a work around, you can specify the uri in the parameters, for example:
```typescript
await signIn(logtoConfig, {
  redirectUri: "http://localhost:3000/api/auth/callback",
});
```

**Comment by eelkevdbos** [comment]
This is still an issue. I "fixed" it by updating my `baseUrl` like below to support a callback url like `'http://localhost:3000/auth/callback'`.

```ts
// lib/logto.ts
export const logtoConfig = {
      ...
      baseUrl: 'http://localhost:3000/auth' // before: 'http://localhost:3000'
}
```

```ts
// app/auth/login/route.ts
export async function GET(request: NextRequest) {
    const redirectUri = new URL("/auth/callback", request.url);
    await signIn(logtoConfig, { redirectUri });
}
```

```ts
// app/auth/callback/route.ts
export async function GET(request: NextRequest) {
    const searchParams = request.nextUrl.searchParams;
    await handleSignIn(logtoConfig, searchParams);
    redirect("/");
}
```

I do consider this a workaround, because setting the 'baseUrl' like that makes little sense to me.
