### ISSUE TITLE
bug: user roles update via PUT always throws invalid body error

### ISSUE THREAD

**Issue by jay-dee7** [logto-io/logto#6378]
### Describe the bug

When using the `PUT /api/users/{userId}/roles` endpoint to update user roles, I always get the following error:
```json
{
  "message": "The request body is invalid.",
  "code": "guard.invalid_input",
  "data": {
    "issues": [
      {
        "code": "invalid_type",
        "expected": "array",
        "received": "undefined",
        "path": [
          "roleIds"
        ],
        "message": "Required"
      }
    ],
    "name": "ZodError"
  },
  "details": "Error in key path \"roleIds\": (invalid_type) Expected array but received undefined."
}
```

### Expected behavior
The request should succeed

### How to reproduce?
- Using curl:
```bash
curl -XPUT -d '{"roleIds":["some-role-id"]}' -H 'Content-Type: application/json' -H 'Authorization: Bearer <AUTH_TOKEN_HERE>' '<logto-deployment-url>/api/users/{USER_ID}/roles'
```

#### Additional context:
This only seems to occur when a user has existing roles and we try to remove some roles.
1. User as `roleA`, `roleB`, and `roleC`
2. We put the `PUT` call to make it `roleA` and `roleB` only (removing `roleC`)
3. We only get this error in this particular scenario

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = [v1.18.0](https://github.com/logto-io/logto/releases/tag/v1.18.0) 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

**Comment by darcyYe** [comment]
API should work fine, please check your cURL command. Should remove double quote in the configuration of content-type?

**Comment by jay-dee7** [comment]
Hey @darcyYe, this isn't a curl only issue, when I programatically use it, it still happens.

**Comment by darcyYe** [comment]
You could show us how you call this API. I tried with both API client ([Bruno](https://www.usebruno.com/)) and cURL command line, they worked fine on my machine. Since you are developing with OSS, you can see details in console log for easier debugging experience.
