### ISSUE TITLE
bug: Not able to work as OIDC to Cloudflare Zero Trust (2)

### ISSUE THREAD

**Issue by a-w-1806** [logto-io/logto#6428]
Same as #6242. I have tried but the issue still persists.

**Comment by MoreMLDev** [comment]
I just tried restarting the container, and it worked. So basically, switch it to RSA, then bring it down and up again.

**Comment by wangsijie** [comment]
I'll do another test.

**Comment by wangsijie** [comment]
Follow the [docs](https://docs.logto.io/docs/references/using-cli/rotate-signing-keys/) to rotate signing keys to "RSA" and remember to restart Logto if you are using OSS version.
