### ISSUE TITLE
bug: Localization error on sing-up experience in Polish

### ISSUE THREAD

**Issue by mbablok** [logto-io/logto#6480]
### Describe the bug
There is a non-translated/not-found text on the sing-in process using Polish language. Regardless of password policy it renders as 
`Wymagania dotyczące hasła description.password_requirement.length.` The translation is there, I tried to play around with overriding them but no success.

### Expected behavior
It should be rendered as
`Wymagania dotyczące hasła wymaga co najmniej {{count}} znaku.` or rather
`Wymagania dotyczące hasła wymaga co najmniej 8 znaków.`

### How to reproduce?
In Sing-in experience
* Change the language to Polish
* Disable auto-detect
* Live Preview
* Go to create account and password creation

### Context

- [x] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

<img width="644" alt="image" src="https://github.com/user-attachments/assets/ea1a741f-314b-4288-91aa-d93c4fd5ecf5">
<img width="1198" alt="Screenshot 2024-08-20 at 16 40 45" src="https://github.com/user-attachments/assets/02da680a-671b-4fc4-b46f-037a02dc01f1">

**Comment by simeng-li** [comment]
Hi, thx for the report. Turns out the `pl` does not read the `_other` key for plural phrases. 

https://github.com/logto-io/logto/pull/6510

**Comment by mbablok** [comment]
Thank you 👍
