### ISSUE TITLE
bug: logto service is getting restarted and not running in self hosted Coolify

### ISSUE THREAD

**Issue by capsmagick** [logto-io/logto#6535]
When I pulled the latest release and updated the logto image in coolify the postgress container is working but the logto container is getting restarted continuously

### Expected behaviour
should be able to login to logto admin console.

### How to reproduce?
Selfhost Coolify
Deploy Logto 

### Context
- [ ] Logto Cloud
- [# ] Self-hosted, Logto version = 
  - [ #] Container (Docker image)
  - [ ] Raw Node.js

**Comment by JustMrMendez** [comment]
problem continues

**Comment by charIeszhao** [comment]
Make sure you have run the database alteration scripts to upgrade your database too.
https://docs.logto.io/docs/references/using-cli/database-alteration/

**Comment by skyturtleio** [comment]
I'm having a similar issue when attempting to upgrade from `v1.19.0` to `v1.20.0`. After Logto is upgraded, it keeps restarting. Reverting back to `v1.19.0` fixed the infinite restarts.

To revert, I had to go from the latest to the `1.19` tag:

Previous Docker Compose with latest:

```yaml
image: svhd/logto:${TAG-latest}
```

Docker Compose to revert back to `v1.19.0`:

```yaml
image: 'svhd/logto:1.19'
```

I also shelled into the Docker container running Logto to check for database alterations, and there were not any:

```shell
/etc/logto # npx @logto/cli db alteration deploy
info Found 0 alteration to deploy
```

**Comment by charIeszhao** [comment]
@skyturtleio @JustMrMendez Have you guys upgrade your `@logto/cli` package to v1.20.0 too?

**Comment by skyturtleio** [comment]
@charIeszhao you're right on the database alterations. Sorry about that. When I was shelling into my Docker container, it had already reverted back to `v1.19.0` to get back into a healthy state.

Here is the error log when attempting to upgrade to `v1.20.0`:

```shell
2024-09-20T19:12:36.498573264Z 
    2024-09-20T19:12:36.498664206Z > cli
    2024-09-20T19:12:36.498673673Z > logto db seed --swe
    2024-09-20T19:12:36.498677382Z 
    2024-09-20T19:12:37.560505928Z info Seeding skipped
    2024-09-20T19:12:37.587172549Z npm notice
    2024-09-20T19:12:37.587202065Z npm notice New patch version of npm available! 10.8.2 -> 10.8.3
    2024-09-20T19:12:37.587206212Z npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
    2024-09-20T19:12:37.587208897Z npm notice To update run: npm install -g npm@10.8.3
    2024-09-20T19:12:37.587211233Z npm notice
    2024-09-20T19:12:37.768354301Z 
    2024-09-20T19:12:37.768382305Z > start
    2024-09-20T19:12:37.768388737Z > cd packages/core && NODE_ENV=production node .
    2024-09-20T19:12:37.768393746Z 
    2024-09-20T19:12:38.699741189Z (node:44) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
    2024-09-20T19:12:38.699778308Z (Use `node --trace-warnings ...` to show where the warning was created)
    2024-09-20T19:12:40.919728328Z cache    warn No Redis client initialized, skipping
    2024-09-20T19:12:41.380557457Z pre      error Found undeployed database alterations, you must deploy them first by npm run alteration deploy command.
    2024-09-20T19:12:41.380576324Z 
    2024-09-20T19:12:41.380579419Z  See https://docs.logto.io/docs/references/using-cli/database-alteration for reference.
    2024-09-20T19:12:41.380581954Z 
    2024-09-20T19:12:41.380611069Z index    error Error while initializing app:
    2024-09-20T19:12:41.384797522Z index    error Error: Undeployed database alterations found.
    2024-09-20T19:12:41.384809636Z     at checkAlterationState (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26444:9)
    2024-09-20T19:12:41.384812421Z     at async Promise.all (index 0)
    2024-09-20T19:12:41.384814526Z     at async checkPreconditions (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26408:3)
    2024-09-20T19:12:41.384817020Z     at async Promise.all (index 3)
    2024-09-20T19:12:41.384819094Z     at async file:///etc/logto/packages/core/build/main-F72FFTZD.js:26480:3
```

Is there a way to run the CLI command for database alterations, e.g. `logto db alteration deploy`, from your link above during the deploy? I have included the stock Coolify Docker Compose file below. I noticed the database alteration command is  interactive so I wasn't sure that would be possible. 

If not, I also saw an [example job](https://docs.logto.io/docs/recipes/deployment/#database-alteration-1) to run for database alterations in the deployment section of the Logto docs. I'm not too familiar with jobs in a Docker Compose file. Any chance you know where I could place this in the Docker Compose file? I've tried updating my Docker Compose a few times, but the build keeps failing.

Coolify Docker Compose for Logto:

```yaml
services:
  logto:
    image: 'svhd/logto:${TAG-latest}'
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - sh
      - '-c'
      - 'npm run cli db seed -- --swe && npm start'
    environment:
      - TRUST_PROXY_HEADER=1
      - 'DB_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-logto}'
      - ENDPOINT=$LOGTO_ENDPOINT
      - ADMIN_ENDPOINT=$LOGTO_ADMIN_ENDPOINT
    healthcheck:
      test:
        - CMD-SHELL
        - 'exit 0'
      interval: 5s
      timeout: 20s
      retries: 10
  postgres:
    image: 'postgres:14-alpine'
    user: postgres
    environment:
      POSTGRES_USER: '${SERVICE_USER_POSTGRES}'
      POSTGRES_PASSWORD: '${SERVICE_PASSWORD_POSTGRES}'
      POSTGRES_DB: '${POSTGRES_DB:-logto}'
    volumes:
      - 'logto-postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-U'
        - $SERVICE_USER_POSTGRES
        - '-d'
        - $POSTGRES_DB
      interval: 5s
      timeout: 20s
      retries: 10
```

Example database alteration from docs:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: alteration
spec:
  template:
    spec:
      containers:
        - name: alteration
          image: ghcr.io/logto-io/logto
          imagePullPolicy: Always
          env:
            - name: CI
              value: 'true'
            - name: DB_URL
              value: postgresql://user:password@localhost:5432/logto
          command:
            - /bin/sh
          args:
            - '-c'
            - 'npm run alteration deploy latest'
      restartPolicy: Never
```

**Comment by charIeszhao** [comment]
> @charIeszhao you're right on the database alterations. Sorry about that. When I was shelling into my Docker container, it had already reverted back to `v1.19.0` to get back into a healthy state.
> 
> Here is the error log when attempting to upgrade to `v1.20.0`:
> 
> ```shell
> 2024-09-20T19:12:36.498573264Z 
>     2024-09-20T19:12:36.498664206Z > cli
>     2024-09-20T19:12:36.498673673Z > logto db seed --swe
>     2024-09-20T19:12:36.498677382Z 
>     2024-09-20T19:12:37.560505928Z info Seeding skipped
>     2024-09-20T19:12:37.587172549Z npm notice
>     2024-09-20T19:12:37.587202065Z npm notice New patch version of npm available! 10.8.2 -> 10.8.3
>     2024-09-20T19:12:37.587206212Z npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
>     2024-09-20T19:12:37.587208897Z npm notice To update run: npm install -g npm@10.8.3
>     2024-09-20T19:12:37.587211233Z npm notice
>     2024-09-20T19:12:37.768354301Z 
>     2024-09-20T19:12:37.768382305Z > start
>     2024-09-20T19:12:37.768388737Z > cd packages/core && NODE_ENV=production node .
>     2024-09-20T19:12:37.768393746Z 
>     2024-09-20T19:12:38.699741189Z (node:44) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
>     2024-09-20T19:12:38.699778308Z (Use `node --trace-warnings ...` to show where the warning was created)
>     2024-09-20T19:12:40.919728328Z cache    warn No Redis client initialized, skipping
>     2024-09-20T19:12:41.380557457Z pre      error Found undeployed database alterations, you must deploy them first by npm run alteration deploy command.
>     2024-09-20T19:12:41.380576324Z 
>     2024-09-20T19:12:41.380579419Z  See https://docs.logto.io/docs/references/using-cli/database-alteration for reference.
>     2024-09-20T19:12:41.380581954Z 
>     2024-09-20T19:12:41.380611069Z index    error Error while initializing app:
>     2024-09-20T19:12:41.384797522Z index    error Error: Undeployed database alterations found.
>     2024-09-20T19:12:41.384809636Z     at checkAlterationState (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26444:9)
>     2024-09-20T19:12:41.384812421Z     at async Promise.all (index 0)
>     2024-09-20T19:12:41.384814526Z     at async checkPreconditions (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26408:3)
>     2024-09-20T19:12:41.384817020Z     at async Promise.all (index 3)
>     2024-09-20T19:12:41.384819094Z     at async file:///etc/logto/packages/core/build/main-F72FFTZD.js:26480:3
> ```
> 
> Is there a way to run the CLI command for database alterations, e.g. `logto db alteration deploy`, from your link above during the deploy? I have included the stock Coolify Docker Compose file below. I noticed the database alteration command is  interactive so I wasn't sure that would be possible. 
> 
> If not, I also saw an [example job](https://docs.logto.io/docs/recipes/deployment/#database-alteration-1) to run for database alterations in the deployment section of the Logto docs. I'm not too familiar with jobs in a Docker Compose file. Any chance you know where I could place this in the Docker Compose file? I've tried updating my Docker Compose a few times, but the build keeps failing.
> 
> Coolify Docker Compose for Logto:
> 
> ```yaml
> services:
>   logto:
>     image: 'svhd/logto:${TAG-latest}'
>     depends_on:
>       postgres:
>         condition: service_healthy
>     entrypoint:
>       - sh
>       - '-c'
>       - 'npm run cli db seed -- --swe && npm start'
>     environment:
>       - TRUST_PROXY_HEADER=1
>       - 'DB_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-logto}'
>       - ENDPOINT=$LOGTO_ENDPOINT
>       - ADMIN_ENDPOINT=$LOGTO_ADMIN_ENDPOINT
>     healthcheck:
>       test:
>         - CMD-SHELL
>         - 'exit 0'
>       interval: 5s
>       timeout: 20s
>       retries: 10
>   postgres:
>     image: 'postgres:14-alpine'
>     user: postgres
>     environment:
>       POSTGRES_USER: '${SERVICE_USER_POSTGRES}'
>       POSTGRES_PASSWORD: '${SERVICE_PASSWORD_POSTGRES}'
>       POSTGRES_DB: '${POSTGRES_DB:-logto}'
>     volumes:
>       - 'logto-postgres-data:/var/lib/postgresql/data'
>     healthcheck:
>       test:
>         - CMD
>         - pg_isready
>         - '-U'
>         - $SERVICE_USER_POSTGRES
>         - '-d'
>         - $POSTGRES_DB
>       interval: 5s
>       timeout: 20s
>       retries: 10
> ```
> 
> Example database alteration from docs:
> 
> ```yaml
> apiVersion: batch/v1
> kind: Job
> metadata:
>   name: alteration
> spec:
>   template:
>     spec:
>       containers:
>         - name: alteration
>           image: ghcr.io/logto-io/logto
>           imagePullPolicy: Always
>           env:
>             - name: CI
>               value: 'true'
>             - name: DB_URL
>               value: postgresql://user:password@localhost:5432/logto
>           command:
>             - /bin/sh
>           args:
>             - '-c'
>             - 'npm run alteration deploy latest'
>       restartPolicy: Never
> ```

How about shelling into your docker container and upgrading `@logto/cli` to 1.20.0 first?

**Comment by skyturtleio** [comment]
@charIeszhao how do I upgrade the `@logto/cli` when I've shelled into the container? I think I'm missing something basic. In the docs and when I run `--help`, I only see options for `init`, `db`, `connector`, `translate`, and `proxy`.

**Comment by charIeszhao** [comment]
> @charIeszhao how do I upgrade the `@logto/cli` when I've shelled into the container? I think I'm missing something basic. In the docs and when I run `--help`, I only see options for `init`, `db`, `connector`, `translate`, and `proxy`. 

Can you do `npm install -g @logto/cli`?

**Comment by skyturtleio** [comment]
@charIeszhao thanks for the help, really appreciate it. I was able to run `npm install -g @logto/cli` in my Docker container.

Yeah, I know the latest Docker image includes the CLI, but it was kind of a chicken and egg problem. When upgrading to the latest image (for Coolify at least), the container would keep restarting because there were database alterations that needed to be run. Because the container kept restarting, I wasn't able to shell into a container with `v1.20.0` running to actually run `logto db alt deploy`. In my post above, my Logto container was running `v1.19.0` so its CLI was not seeing any new database alterations.

Anyway, here is how I was able to upgrade Logto in Coolify:

- On a working Logto `v1.19.0` Docker container, shell into your container and run `npm install -g @logto/cli` to get the latest CLI
- After the Logto CLI is updated, run `logto db alt deploy` and select `1.20.0`
- After database alterations have been made, then pull the latest image for Logto and deploy

**Comment by charIeszhao** [comment]
> @charIeszhao thanks for the help, really appreciate it. I was able to run `npm install -g @logto/cli` in my Docker container.
> 
> Yeah, I know the latest Docker image includes the CLI, but it was kind of a chicken and egg problem. When upgrading to the latest image (for Coolify at least), the container would keep restarting because there were database alterations that needed to be run. Because the container kept restarting, I wasn't able to shell into a container with `v1.20.0` running to actually run `logto db alt deploy`. In my post above, my Logto container was running `v1.19.0` so its CLI was not seeing any new database alterations.
> 
> Anyway, here is how I was able to upgrade Logto in Coolify:
> 
> * On a working Logto `v1.19.0` Docker container, shell into your container and run `npm install -g @logto/cli` to get the latest CLI
> * After the Logto CLI is updated, run `logto db alt deploy` and select `1.20.0`
> * After database alterations have been made, then pull the latest image for Logto and deploy

@skyturtleio Thanks for the explaination and detailed steps!

@capsmagick It seems we have a solution now, and I'm closing the ticket. Feel free to reopen it if necessary.
