### ISSUE TITLE
bug: 你好我在部署logto，创建next.js应用时一直在转圈可以帮我看下为什么嘛

### ISSUE THREAD

**Issue by zhangleijun111** [logto-io/logto#6546]
### Context

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

我的docker-compose
logto：
image： registry.us-west-1.aliyuncs.com/jg-images/logto:latest
container_name： lobe-logto
ports：
'3001：3001'
'3002：3002'
depends_on：
PostgreSQL：
条件： service_healthy
环境：
'TRUST_PROXY_HEADER=1'
'DB_URL=postgresql：//postgres：uWNZugjBqixf8dxC@postgresql：5432/logto'
'ENDPOINT=https://lobe-auth-api.jiu-guang.com'
'ADMIN_ENDPOINT=https://lobe-auth-ui.jiu-guang.com'
入口点： ['sh'， '-c'， 'npm run cli db seed -- --swe & npm start']

我的env
NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg
NEXT_AUTH_SSO_PROVIDERS=logto
NEXTAUTH_URL=https://lobe.jiu-guang.com/api/auth
LOGTO_CLIENT_SECRET=YOUR_LOGTO_CLIENT_SECRET
LOGTO_ISSUER=https://lobe-auth-api.jiu-guang.com/oidc

报错截图
![Uploading b1c819c221227a68e209381d316f7e1.png…]()

**Comment by darcyYe** [comment]
Hi @zhangleijun111 , before posting an issue, you should follow our issue format and description your problems with English. You can add translation in your native language, but we need full context in English so that all other community members can get information from the issue.

**Comment by zhangleijun111** [comment]
> 您好，在发布问题之前，您应该遵循我们的问题格式并用英语描述您的问题。您可以添加母语的翻译，但我们需要英语的完整上下文，以便所有其他社区成员都可以从问题中获取信息。
Hello, when I was deploying Logto and creating an application, it kept spinning. Can you help me check why
