### ISSUE TITLE
bug: Page 404

### ISSUE THREAD

**Issue by 37809874** [logto-io/logto#6554]
I have defined the HTTPS domain name in my compose file
- ENDPOINT
- ADMIN_ENDPOINT
And it has already been added to my nginx configuration file
location / {
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_pass  http://127.0.0.1:3001 ;
}
But when I access the domain name, it is blank F12 and I see 404. Why is this
![image](https://github.com/user-attachments/assets/7fe3d433-5387-4dce-ba9b-5137cbca2649)

**Comment by 37809874** [comment]
# This compose file is for demonstration only, do not use in prod.
version: "3.9"
services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:${TAG-latest}
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - DB_URL=postgres://postgres:p0stgr3s@postgres:5432/logto
      # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
      # Or, you can leverage it for local testing.
      - ENDPOINT=https://domain（This is the complete domain name）
      - ADMIN_ENDPOINT=https://domain（This is the complete domain name）
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

这是我的完整文件
我需要添加什么配置吗？

**Comment by charIeszhao** [comment]
https://docs.logto.io/docs/recipes/deployment/#reverse-proxy
Make sure you check this one out.

**Comment by charIeszhao** [comment]
Closing the ticket due to inactivity for more than 3 weeks. Feel free to reopen if necessary.
