### ISSUE TITLE
bug: OpenAPI spec contains duplicate operationIds, which is not allowed

### ISSUE THREAD

**Issue by mmurto** [logto-io/logto#6573]
### Describe the bug

The OpenAPI spec available for download from https://openapi.logto.io/ at least two duplicate values for `operationId`: `VerifyVerificationCode` and `UpdateUserProfile`.

[OpenAPI spec states](https://swagger.io/specification/) the following for `operationId`:

> The id MUST be unique among all operations described in the API.

This leads to some client generators for the API not working with Logto's OpenAPI spec.

### Expected behavior

Use unique `operationId` for all operations.

### How to reproduce?

Download Logto's OpenAPI spec and search for `operationId: VerifyVerificationCode`.

### Context

- [x] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

**Comment by simeng-li** [comment]
Thanks for the report. Looking into it.

**Comment by simeng-li** [comment]
@mmurto we have split the Management API and client-side Experience API into two different openapi endpoints:

`/api/.well-known/management.openapi.json` and `/api/.well-known/experienec.openapi.json`.

The original `/api/swagger.json` includes both the Management API and Experience API endpoints. I’ve identified some duplicate operationId definitions shared between the Management and Experience API endpoints, as they serve similar purposes in different use cases. I’ll resolve these issues shortly.

In the meantime, please use the new /api/.well-known/management.openapi.json to exclusively generate the Management API SDK.

**Comment by simeng-li** [comment]
#6574

**Comment by mmurto** [comment]
Thanks! The `.well-known/` files work for now, I assume the fix in #6574 is not yet live.

**Comment by simeng-li** [comment]
The fix is live now. Feel free to update. Thx again.
