### ISSUE TITLE
bug: Error on create a password 

### ISSUE THREAD

**Issue by yincangshiwei** [logto-io/logto#6577]
create a pawssword error：
![image](https://github.com/user-attachments/assets/529c7429-7223-497d-b541-a21d585d9fd1)

**Comment by charIeszhao** [comment]
Same as #6582 

It seems your database does not have access to the breach database. Either allow the network access on your server, or turn it off in "Password policy"

**Comment by charIeszhao** [comment]
I don't think we have breached DB checking in password policy by default for the admin. But you can always check it out by directly accessing the Logto DB.
Go to `sign_in_experiences` table and there should be a record associated with `admin` tenant. Check its `password_policy` column, and change it to `{}` to disable it.

**Comment by 7788jay** [comment]
> > It seems your database does not have access to the breach database. Either allow the network access on your server, or turn it off in "Password policy"
> 
> When I tried to disable the password policy, I found that I need to log into the console to do so. However, the issue occurred when I started Docker and attempted to create a password for the first time, which resulted in this error and now I cannot log into the console. How should I proceed in this case?

You can roll back the previous versions, register one first

**Comment by charIeszhao** [comment]
Sorry I made a mistake that even though we don't have default values for password policy in DB for admin, we still enforced that in source code level. So you need to have internet connection for your Logto server instance in order to make it work.
Is there any limitation for you to do that? Is your server deployed in an internal network environment?

**Comment by charIeszhao** [comment]
OK, got it. Seems it's a problem enabling it by default. Will bring it to the team and see if we can have it disabled

**Comment by charIeszhao** [comment]
Do you have access to the DB? Let me know if you can update the table directly

**Comment by charIeszhao** [comment]
If you do have access to the database, you can turn off the pwned check by:
```sql
update sign_in_experiences set password_policy='{"rejects": {"pwned": true}}' where tenant_id='admin';
```
