### ISSUE TITLE
bug: Error while updating Docker version 1.20.0

### ISSUE THREAD

**Issue by Matinal111** [logto-io/logto#6585]
As the title suggests, I self deployed Logto 1.19.0 via Docker, everything was working fine during this period, after upgrading to 1.20.0 it became unavailable, here are the error logs, I'm not sure if there are any bugs in this version, please help me to get it back to normal use!

```
(node:44) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
cache    info Connected to Redis
pre      error Found undeployed database alterations, you must deploy them first by npm run alteration deploy command.
 See https://docs.logto.io/docs/references/using-cli/database-alteration for reference.
index    error Error while initializing app:
index    error Error: Undeployed database alterations found.
    at checkAlterationState (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26444:9)
    at async Promise.all (index 0)
    at async checkPreconditions (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26408:3)
    at async Promise.all (index 3)
    at async file:///etc/logto/packages/core/build/main-F72FFTZD.js:26480:3
cache    info Disconnected from Redis
```

**Comment by hoopan007** [comment]
> As the title suggests, I self deployed Logto 1.19.0 via Docker, everything was working fine during this period, after upgrading to 1.20.0 it became unavailable, here are the error logs, I'm not sure if there are any bugs in this version, please help me to get it back to normal use!
> 
> ```
> (node:44) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
> (Use `node --trace-warnings ...` to show where the warning was created)
> cache    info Connected to Redis
> pre      error Found undeployed database alterations, you must deploy them first by npm run alteration deploy command.
>  See https://docs.logto.io/docs/references/using-cli/database-alteration for reference.
> index    error Error while initializing app:
> index    error Error: Undeployed database alterations found.
>     at checkAlterationState (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26444:9)
>     at async Promise.all (index 0)
>     at async checkPreconditions (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26408:3)
>     at async Promise.all (index 3)
>     at async file:///etc/logto/packages/core/build/main-F72FFTZD.js:26480:3
> cache    info Disconnected from Redis
> ```

Same problem

**Comment by simeng-li** [comment]
Please refer to this [doc](https://docs.logto.io/docs/references/using-cli/database-alteration) and run the database alterations first.
