### ISSUE TITLE
bug: Aliyun SMS connector not working, Report invalid Signature while testing.

### ISSUE THREAD

**Issue by nanbingxyz** [logto-io/logto#6593]
### Describe the bug
I set up Aliyun SMS connector base on the document, however I couldn't pass the test, the error is "
Error occurred in connector: Specified signature is not matched with our calculation."

### Expected behavior
The test was successful and the test SMS was received

### How to reproduce?
1. Setup Aliyun Short Message Service with Access Key ID, Access Key Secret, Signature Name and Templates, 
2. Input my photo number and run the test
3. Got "Error occurred in connector: Specified signature is not matched with our calculation..."

### Context
Logto Cloud

![CleanShot 2024-09-18 at 16 08 29@2x](https://github.com/user-attachments/assets/27f513f7-dd95-4df6-8fb5-b790dbfcc48b)

**Comment by wangsijie** [comment]
I did a test and everything worked as expected, please check your access keys and try again.

Feel free to reopen if you have any further questions.
