### ISSUE TITLE
Integrate with Apache Answer

### ISSUE THREAD

**Issue by AllinProgram** [logto-io/logto#6595]
### Describe the bug
[Apache Answer](https://github.com/apache/incubator-answer) is an effort undergoing incubation at The Apache Software Foundation.
**I hope to use Logto as the user center of Answer and provide authorization for Answer.**

**Logto provides OIDC, and Answer supports OAuth2.0**. 
I understand that OIDC is a superset of OAuth2.0, but when I use it together, it return an error. I wonder if these two great tools can be used together.

### Expected behavior
I have fully configured the information of Logto in Answer, so I can jump to the login page. After the login callback, this process returns invalid request information.
``` log
ERROR	controller/connector_controller.go:130	connector received failed, error info: code exchange failed: oauth2: cannot fetch token: 400 Bad Request
Response: {"code":"oidc.invalid_request","message":"Request is invalid.","error":"invalid_request","error_description":"missing required parameter 'code'"}, response data is:
```

### How to reproduce?
1. Open Logto and create a OIDC Application;
2. Set Logto info into Answer Oauth2.0 plugin;
3. Set [Answer callback uri](https://github.com/apache/incubator-answer-plugins/tree/main/connector-basic) into Logto;
4. Start Login, input correct account info and click login.
5. wait callback, then log error info.

### Context

- [x] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### More
- Thank you for your efforts to make such a great tool.
- If you think this is not a bug of Logto, please give me some information to help me, and you can close this issue directly.
- If you are interested in this scenario, I can provide Logto instance and Answer instance for your investigation.

**Comment by wangsijie** [comment]
Hi, I believe this is a valid feature request, it is on the roadmap now. And pull request is always welcomed.

**Comment by charIeszhao** [comment]
I'm curious what is an "OIDC application" in step 1

**Comment by allinprogram** [comment]
@charIeszhao 
Console -> Applications -> Create Application -> Third-party app -> OIDC.
