### ISSUE TITLE
bug: 这个怎么解决呀

### ISSUE THREAD

**Issue by zhangleijun111** [logto-io/logto#6598]
### Context

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

[
![捕获](https://github.com/user-attachments/assets/aa42ea0f-0552-4250-ac1a-717aa5e4cd4d)
](url)

**Comment by wangsijie** [comment]
Please enable HTTPs for Logto.
