### ISSUE TITLE
bug: translation missing: `en.logto.login_hint`

### ISSUE THREAD

**Issue by imWildCat** [logto-io/logto#6613]
### Describe the bug
when logging in, there's missing hint.
it also appears on other languages like Chinese

<img width="498" alt="image" src="https://github.com/user-attachments/assets/fa4ef1df-4bbb-452c-9992-bde0045d4b76">

it is also not a placeholder...

### Expected behavior
no such an error

### How to reproduce?
not reproducible on https://auth.logto.io/sign-in

but this error happens on self host instances

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

**Comment by xiaoyijun** [comment]
Hi @imWildCat , the hint content is retrieved from the URL, and it seems that the current page’s URL already contains this error message. Could you let me know where you initiated the authentication process? Would you mind sharing the search parameters from the current page’s URL?

**Comment by imWildCat** [comment]
@xiaoyijun my apologies! yes, you're right. that's from the host app's login hint
