### ISSUE TITLE
bug: i uploaded a customize UI zip .the zip included a mp4 as background.but the mp4 can not play in  safari and an error in chrome as below:

### ISSUE THREAD

**Issue by dyan1992** [logto-io/logto#6623]
### Context

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

**Comment by dyan1992** [comment]
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://accounts.google.com/gsi/". Either the 'unsafe-inline' keyword, a hash ('sha256-A8/6BuTyjjyLe5qIPQhhR//yqMwG6kS/IU7vsY8YI8U='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by charIeszhao** [comment]
I've been working on a fix for the mp4 not playable issue on Safari. (#6630)

As for the CSP error, I think the "unsafe-inline" has been allowed for the experience pages. Can you elaborate more on this?
