### ISSUE TITLE
how to use logto in nextjs middleware

### ISSUE THREAD

**Issue by nexa-li** [logto-io/logto#6624]
### Describe the bug
I am trying to use Logto for authentication in Next.js 14. In the middleware, I intercept the route, and if the user is not logged in, they are redirected to the login page. Everything works fine when I develop and run it on macOS, but when I deploy it to Ubuntu, the error shown in the image occurs. I then tried to reproduce it on Windows, and both the development and deployed versions show the same error. I would like to know, if it’s not possible to use middleware, how can I globally check the user’s login status and then redirect accordingly?

### Expected behavior
Retrieve the user’s login status in the middleware and proceed with subsequent actions.

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = latest
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots
![longshot20240924110159](https://github.com/user-attachments/assets/572aac3b-26a1-4d8c-81e8-b4c4ea026ff1)

**Comment by wangsijie** [comment]
I'll take a look.

**Comment by wangsijie** [comment]
Resolved in https://github.com/logto-io/js/pull/813
