### ISSUE TITLE
bug: redirect_uri` did not match any of the client's registered `redirect_uris when using Cloudflare Tunnel

### ISSUE THREAD

**Issue by clho40** [logto-io/logto#6648]
### Describe the bug
The background is, I have a VPS, installed Coolify on it, and used Coolify's template to deploy a Logto application.
My custom domain is parked on Cloudflare, and I use Cloudflare Tunnel to point the DNS to my VPS.
and I have used Cloudflare's SSL/TLS redirect in order to redirect all the traffic from HTTP to HTTPS.

So the problem is, when I configure the `ADMIN_ENDPOINT` as `http://logto-admin.mydomain.com`, Cloudflare will automatically redirect the traffic to `https://logto-admin.mydomain.com` and when I click the Create Account button I get the following error

```
{
    "code": "oidc.invalid_redirect_uri",
    "message": "`redirect_uri` did not match any of the client's registered `redirect_uris`.",
    "error": "invalid_redirect_uri",
    "error_description": "redirect_uri did not match any of the client's registered redirect_uris",
    "state": "JKtuiY1FXwScYAPeMEGwBCFX80oyLtMx3C2oS9E-9ohfbboh9qorZCsSDzfkaGBb3bV4lAZIWUqmIecTtKdjHg",
    "iss": "http://logto-admin.mydomain.com/oidc"
}
```

It seems like Logto does not recognize the redirected URL? How do I solve this problem?

### Context

- [ ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [-] Container (Docker image)
  - [ ] Raw Node.js

**Comment by xiaoyijun** [comment]
Hi @clho40 , set `ADMIN_ENDPOINT` to the URL you finally visited (`https://logto-admin.mydomain.com`).

And check the error content from the URL where you see the error json page:
```
{
    "code": "oidc.invalid_redirect_uri",
    "message": "`redirect_uri` did not match any of the client's registered `redirect_uris`.",
    "error": "invalid_redirect_uri",
    "error_description": "redirect_uri did not match any of the client's registered redirect_uris",
    "state": "JKtuiY1FXwScYAPeMEGwBCFX80oyLtMx3C2oS9E-9ohfbboh9qorZCsSDzfkaGBb3bV4lAZIWUqmIecTtKdjHg",
    "iss": "http://logto-admin.mydomain.com/oidc"
}
```

The URL will be like:
```
http://localhost:3001/oidc/auth?client_id=???&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Facallback&code_challenge=....
```

from the URL, you will see the callback uri actually used, and add the URI to the application's redirect uri field:

<img width="875" alt="image" src="https://github.com/user-attachments/assets/04e28c3d-d8f0-480f-affe-06547cca1dda">

**Comment by clho40** [comment]
Hello,

I can't set the `ADMIN_ENDPOINT` to https - I get the error `logto-admin.mydomain.com redirected you too many times.` because Cloudflare redirects the traffic.

I get this even before I can login to the portal
![Screenshot 2024-10-01 093851](https://github.com/user-attachments/assets/fc32768b-5efe-48c2-b0bd-8183ca6b247e)
![Screenshot 2024-10-01 093947](https://github.com/user-attachments/assets/b5e58282-2aab-44b8-ac36-d2a154959665)

**Comment by a0zzy** [comment]
+1 Same exact issue

**Comment by a0zzy** [comment]
I was able to get around this by changing "https" to "http" for a quick workaround and it allowed me to create an account and login, but I was not able to get to the dashboard because I get this error: 
<img width="1440" alt="Screenshot 2024-10-04 at 13 09 10" src="https://github.com/user-attachments/assets/c6c119d7-d726-4428-87fb-18fcc93b41e8">
<img width="1440" alt="Screenshot 2024-10-04 at 13 09 33" src="https://github.com/user-attachments/assets/f0552208-bc94-431e-b992-e8bbc92eba09">

**Comment by xiaoyijun** [comment]
Try set both `ENDPOINT` and `ADMIN_ENDPOINT` to `https`, these endpoints should be the final endpoints you access. As long as your external access to Logto is via HTTPS, these endpoints should be https, regardless of whether you are using HTTP + proxy internally or directly using HTTPS.

**Comment by xiaoyijun** [comment]
@a0zzy what's the error message from the console or the network request?

**Comment by a0zzy** [comment]
I'm out of office right now, but both endpoint and admin_endpoint are set to https. I can get logs soon.

**Comment by clho40** [comment]
If we set both `ENDPOINT` and `ADMIN_ENDPOINT` to https, we get into infinite https redirect loop. That's because Cloudflare redirects to https, and Logto application seemingly also performs redirect

**Comment by clho40** [comment]
One potential solution could be adding an `ENFORCE_HTTPS` environment variable. This would ensure the application automatically replaces http with https when retrieving values from `ENDPOINT` and `ADMIN_ENDPOINT`.

**Comment by xiaoyijun** [comment]
Yes, the main issue is actually related to the network’s HTTPS configuration. Logto Console cannot run in a non-HTTP environment (except for localhost) for security reasons.

**Comment by xiaoyijun** [comment]
I’m planning to close this issue, as it stems from Cloudflare or network configuration rather than Logto itself. We have an article (https://blog.logto.io/local-https) explaining how to use enable HTTPS for debugging Logto, and the deployment process should be the same.
@clho40
