### ISSUE TITLE
bug: error [load-connector] Kubernetes cluster

### ISSUE THREAD

**Issue by SyntaxJuggler** [logto-io/logto#6752]
Good afternoon, I am using Kubernetes cluster to deploy your open source version of logto. I encountered some very strange error, I wrote about it on discord, could you please take a look at it? The bottom line is that some connectors do not load for me, but I use almost entirely your deployment example and I have no idea what could be the reason

Link - https://discord.com/channels/965845662535147551/965845662979719198/1299488477079015504

**Comment by wangsijie** [comment]
I am closing this now,  all the contents are in discord.
